# This file is auto-generated by alef. DO NOT EDIT.
defmodule TreeSitterLanguagePack.DiagnosticSeverity do
  @moduledoc "Severity level of a diagnostic produced during parsing."

  @type t :: :error | :warning | :info

  @error :error
  @warning :warning
  @info :info

  @spec error() :: t()
  def error, do: @error
  @spec warning() :: t()
  def warning, do: @warning
  @spec info() :: t()
  def info, do: @info
end
