# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:03bb7022f098da64d400582d9f1086318c07fa2b90284b7db3c79fe1fbdab065
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule TreeSitterLanguagePack.DiagnosticSeverity do
  @moduledoc """
  Severity level of a diagnostic produced during parsing.

  Used to classify parse errors, warnings, and informational messages
  found in the syntax tree.
  """

  @typedoc "Severity level of a diagnostic produced during parsing."
  @type t :: :error | :warning | :info

  @error :error
  @warning :warning
  @info :info

  @doc "A parse error (e.g., an `ERROR` or `MISSING` node in the tree)."
  @spec error() :: t()
  def error, do: @error
  @doc "A warning-level diagnostic."
  @spec warning() :: t()
  def warning, do: @warning
  @doc "An informational diagnostic."
  @spec info() :: t()
  def info, do: @info

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:error), do: "Error"
  def wire_value(:warning), do: "Warning"
  def wire_value(:info), do: "Info"
end
