# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.DocSection do
  @moduledoc "A section within a docstring (e.g., Args, Returns, Raises)."

  defstruct kind: "",
            name: "",
            description: ""
end
