# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b11772b9bad21ed2eadf3f8bd62d51e19589ada550650aca39c8cfcab12c76b0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule TreeSitterLanguagePack.ExportKind do
  @moduledoc """
  The kind of an export statement found in source code.

  Covers named exports, default exports, and re-exports from other modules.
  """

  @typedoc "The kind of an export statement found in source code."
  @type t :: :named | :default | :re_export

  @named :named
  @default :default
  @re_export :re_export

  @doc "A named export (e.g., `export { foo }`)."
  @spec named() :: t()
  def named, do: @named
  @doc "A default export (e.g., `export default foo`)."
  @spec default() :: t()
  def default, do: @default
  @doc "A re-export from another module (e.g., `export { foo } from 'bar'`)."
  @spec re_export() :: t()
  def re_export, do: @re_export

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:named), do: "Named"
  def wire_value(:default), do: "Default"
  def wire_value(:re_export), do: "ReExport"
end
