# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8043c7c04874b573c9d2f7d336eb6a99855dd911b57327337cd4ac60d454207a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule TreeSitterLanguagePack.ExportInfo do
  @moduledoc "An export statement extracted from source code."

  @typedoc "An export statement extracted from source code."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          kind: TreeSitterLanguagePack.ExportKind.t(),
          span: TreeSitterLanguagePack.Span.t()
        }

  defstruct name: nil,
            kind: :named,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
