# This file is auto-generated by alef. DO NOT EDIT.
defmodule TreeSitterLanguagePack.ExtractionPattern do
  @moduledoc "Defines a single extraction pattern and its configuration."

  defstruct query: "",
            capture_output: :full,
            child_fields: [],
            max_results: 0,
            byte_range: []
end
