# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c67517c6eb3fd3461ef481e59b7717df319a492db9aea10017c9e8f71d249c87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
