# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcf7927316e7a41a4dc67cf83987ee404372d93e50d08a0debb811b0f5e4ab4f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
