# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.StructureItem do
  @moduledoc "A structural item (function, class, struct, etc.) in source code."

  defstruct kind: :function,
            name: "",
            visibility: "",
            span: nil,
            children: [],
            decorators: [],
            doc_comment: "",
            signature: "",
            body_span: nil
end
