# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.SymbolKind do
  @moduledoc "The kind of a symbol definition found in source code."

  @type t :: term()

  @type variable :: :variable
  @type constant :: :constant
  @type function_variant :: :function
  @type class :: :class
  @type type :: :type
  @type interface :: :interface
  @type enum :: :enum
  @type module_variant :: :module
  @type other :: %{type: :other, value_0: term()}
end
