# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22c16871a1e8cb0ed7322532d04150ac1cad9be3e0909b9330e2370ef3beb50f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule TreeSitterLanguagePack.SymbolInfo do
  @moduledoc "A symbol (variable, function, type, etc.) extracted from source code."

  @typedoc "A symbol (variable, function, type, etc.) extracted from source code."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          kind: TreeSitterLanguagePack.SymbolKind.t(),
          span: TreeSitterLanguagePack.Span.t(),
          type_annotation: String.t() | nil,
          doc: String.t() | nil
        }

  defstruct name: nil,
            kind: :variable,
            span: nil,
            type_annotation: nil,
            doc: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
