// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ecb35114882450388c9a1befcc10489e435e399909f2fe321de5e90855a05f81
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 60000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
