<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c67517c6eb3fd3461ef481e59b7717df319a492db9aea10017c9e8f71d249c87
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * Manages downloading and caching of pre-built parser shared libraries.
 */
final class DownloadManager
{
    /**
     * List languages that are already downloaded and cached.
     * @return array<string>
     */
    public function installedLanguages(): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Download the platform bundle and extract every library file it contains.
     */
    public function downloadAllBestEffort(): int
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Remove all cached parser libraries.
     */
    public function cleanCache(): void {}

    /**
     * Create a new download manager for the given version.
     */
    public static function new(string $version): DownloadManager
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
