<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0d51a59da5b6fc6f630e3eb3eb9f86f18679a9080b2ea2fc8b931e66fe6ab2ad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

final class Language
{
}
