<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:af15a38e88d62b4efbc30ea6c7c9c61dbdc29c42c5242fc89f7e44ff1ce3f365
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

final class Language
{
}
