// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:50dbc39a0b541cc4654793dc92ba9a682b44395932ed1550399ca897a290d584
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using TreeSitterLanguagePack;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: error-handling.</summary>
public class ErrorHandlingTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_ErrorDetectContentEmpty()
    {
        // Detect language from empty content returns null
        var result = TreeSitterLanguagePack.DetectLanguageFromContent("");
        Assert.True(string.IsNullOrEmpty(result?.ToString()));
    }

    [Fact]
    public void Test_ErrorDetectExtensionEmpty()
    {
        // Detect language from empty extension returns null
        var result = TreeSitterLanguagePack.DetectLanguageFromExtension("");
        Assert.True(string.IsNullOrEmpty(result?.ToString()));
    }

    [Fact]
    public void Test_ErrorDetectPathEmpty()
    {
        // Detect language from empty path returns null
        var result = TreeSitterLanguagePack.DetectLanguageFromPath("");
        Assert.True(string.IsNullOrEmpty(result?.ToString()));
    }

    [Fact]
    public void Test_ErrorEmptyLanguageName()
    {
        // Parsing with empty language name should error
        Assert.Throws<TreeSitterLanguagePackException>(() => TreeSitterLanguagePack.ParseString("", "hello"));
    }

    [Fact]
    public void Test_ErrorExtractUnknownLanguage()
    {
        // Extract patterns with unknown language returns error
        Assert.Throws<TreeSitterLanguagePackException>(() => TreeSitterLanguagePack.ExtractPatterns("x = 1", "{\"language\":\"nonexistent_language_xyz\",\"patterns\":{}}"));
    }

    [Fact]
    public void Test_ErrorHandlingEmptySource()
    {
        // Parsing an empty string should still produce a tree.
        var tree = TreeSitterLanguagePack.ParseString("javascript", "");
    }

    [Fact]
    public void Test_ErrorHandlingInvalidSyntax()
    {
        // Parsing invalid syntax should produce a tree with error nodes.
        var tree = TreeSitterLanguagePack.ParseString("javascript", "function function function @@@ %%%");
        Assert.True(TreeSitterLanguagePack.TreeHasErrorNodes(tree));
    }

    [Fact]
    public void Test_ErrorHandlingUnknownLanguage()
    {
        // Loading a nonexistent language should produce an error.
        Assert.Throws<TreeSitterLanguagePackException>(() => TreeSitterLanguagePack.ParseString("nonexistent_xyz", ""));
    }

    [Fact]
    public void Test_ErrorProcessEmptySource()
    {
        // Process empty source code succeeds with zero metrics
        var result = TreeSitterLanguagePack.Process("", "{\"language\":\"python\"}");
        Assert.Equal(0, result.Metrics.TotalLines);
    }

    [Fact]
    public void Test_ErrorRunQueryInvalidSyntax()
    {
        // Run query with invalid S-expression syntax produces error
        var tree = TreeSitterLanguagePack.ParseString("python", "x = 1");
        Assert.Throws<TreeSitterLanguagePackException>(() => { TreeSitterLanguagePack.RunQuery(tree, "python", "(((", source); });
    }

    [Fact]
    public void Test_ParseEmptyLanguage()
    {
        // parse_string() returns error with empty language name
        Assert.Throws<TreeSitterLanguagePackException>(() => TreeSitterLanguagePack.ParseString("", "x = 1"));
    }

    [Fact]
    public void Test_ProcessUnknownLanguage()
    {
        // process() returns error when config language is unknown
        Assert.Throws<TreeSitterLanguagePackException>(() => TreeSitterLanguagePack.Process("x = 1", "{\"language\":\"nonexistent_xyz\"}"));
    }
}
