# This file is auto-generated by alef. DO NOT EDIT.
# frozen_string_literal: true

require 'tree_sitter_language_pack'
require 'json'

RSpec.describe 'smoke' do
  it 'smoke_abl: Smoke test: load abl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_actionscript: Smoke test: load actionscript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('var x:int = 1;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ada: Smoke test: load ada and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('procedure Main is begin null; end Main;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_agda: Smoke test: load agda and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('module Main where', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_al: Smoke test: load al and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_angular: Smoke test: load angular and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_apex: Smoke test: load apex and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('public class Main {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_arduino: Smoke test: load arduino and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('void setup() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_asciidoc: Smoke test: load asciidoc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("= Title\n\nParagraph.", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_asm: Smoke test: load asm and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('mov eax, 1', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_astro: Smoke test: load astro and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("---\n---\n<p>hello</p>", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_awk: Smoke test: load awk and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('BEGIN { print "hello" }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_bash: Smoke test: load bash and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('echo hello', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_bass: Smoke test: load bass and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_batch: Smoke test: load batch and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("@echo off\necho hello", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_beancount: Smoke test: load beancount and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('2024-01-01 open Assets:Bank USD', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_bibtex: Smoke test: load bibtex and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('@article{key, title={A}}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_bicep: Smoke test: load bicep and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('param name string', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_bitbake: Smoke test: load bitbake and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('DESCRIPTION = "hello"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_blade: Smoke test: load blade and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_brightscript: Smoke test: load brightscript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_bsl: Smoke test: load bsl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('Procedure Main() EndProcedure', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_c: Smoke test: load c and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('int main() { return 0; }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_c3: Smoke test: load c3 and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_caddy: Smoke test: load caddy and parse a simple snippet' do
    result = TreeSitterLanguagePack.process(":8080 {\n\trespond \"Hello\"\n}", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cairo: Smoke test: load cairo and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('fn main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_capnp: Smoke test: load capnp and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('@0xabcdef1234567890;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cedar: Smoke test: load cedar and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('permit(principal, action, resource);', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cedarschema: Smoke test: load cedarschema and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('entity User;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cel: Smoke test: load cel and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cfml: Smoke test: load cfml and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_chatito: Smoke test: load chatito and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("%[greeting]\n    hello", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_chuck: Smoke test: load chuck and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_circom: Smoke test: load circom and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_clarity: Smoke test: load clarity and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(define-public (hello) (ok true))', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_clojure: Smoke test: load clojure and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(def x 1)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cmake: Smoke test: load cmake and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('cmake_minimum_required(VERSION 3.0)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cobol: Smoke test: load cobol and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO.", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_comment: Smoke test: load comment and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('TODO: fix this', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_commonlisp: Smoke test: load commonlisp and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(defun hello () (print "hello"))', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cooklang: Smoke test: load cooklang and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_corn: Smoke test: load corn and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{ key = "value" }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cpon: Smoke test: load cpon and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{"key": 1}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cpp: Smoke test: load cpp and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('int main() { return 0; }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_crystal: Smoke test: load crystal and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_csharp: Smoke test: load csharp and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('class Main {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_css: Smoke test: load css and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('body { color: red; }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cst: Smoke test: load cst and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_csv: Smoke test: load csv and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("a,b,c\n1,2,3", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cuda: Smoke test: load cuda and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('__global__ void kernel() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cue: Smoke test: load cue and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_cylc: Smoke test: load cylc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_d: Smoke test: load d and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('void main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_dart: Smoke test: load dart and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('void main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_desktop: Smoke test: load desktop and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_devicetree: Smoke test: load devicetree and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("/dts-v1/;\n/ { };", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_dhall: Smoke test: load dhall and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_diff: Smoke test: load diff and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("--- a/file\n+++ b/file\n@@ -1 +1 @@\n-old\n+new", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_djot: Smoke test: load djot and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_dockerfile: Smoke test: load dockerfile and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('FROM alpine', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_dot: Smoke test: load dot and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('digraph G { A -> B; }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_doxygen: Smoke test: load doxygen and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('/** @brief A function */', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_dtd: Smoke test: load dtd and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<!ELEMENT note (body)>', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_earthfile: Smoke test: load earthfile and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ebnf: Smoke test: load ebnf and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_editorconfig: Smoke test: load editorconfig and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_eds: Smoke test: load eds and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_eex: Smoke test: load eex and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_elisp: Smoke test: load elisp and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(defun hello () (message "hello"))', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_elixir: Smoke test: load elixir and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('IO.puts("hello")', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_elm: Smoke test: load elm and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('module Main exposing (..)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_elsa: Smoke test: load elsa and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_elvish: Smoke test: load elvish and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_embeddedtemplate: Smoke test: load embeddedtemplate and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<%= value %>', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_enforce: Smoke test: load enforce and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_erlang: Smoke test: load erlang and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('main() -> ok.', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_facility: Smoke test: load facility and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_faust: Smoke test: load faust and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_fennel: Smoke test: load fennel and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(fn hello [] (print :hello))', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_fidl: Smoke test: load fidl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_firrtl: Smoke test: load firrtl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('circuit Main :', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_fish: Smoke test: load fish and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('echo hello', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_foam: Smoke test: load foam and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_forth: Smoke test: load forth and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_fortran: Smoke test: load fortran and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("program main\nend program main", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_fsharp: Smoke test: load fsharp and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('let x = 1', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_fsharp_signature: Smoke test: load fsharp_signature and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('val x: int', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_func: Smoke test: load func and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('() recv_internal() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gap: Smoke test: load gap and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gdscript: Smoke test: load gdscript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("extends Node\nfunc _ready():\n\tpass", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gdshader: Smoke test: load gdshader and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_git_config: Smoke test: load git_config and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_git_rebase: Smoke test: load git_rebase and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gitattributes: Smoke test: load gitattributes and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('*.txt text', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gitcommit: Smoke test: load gitcommit and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("feat: add feature\n\nBody text", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gitignore: Smoke test: load gitignore and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("*.o\n*.log", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gleam: Smoke test: load gleam and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('pub fn main() { }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_glimmer: Smoke test: load glimmer and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_glsl: Smoke test: load glsl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('void main() { gl_Position = vec4(0.0); }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gn: Smoke test: load gn and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('group("hello") {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gnuplot: Smoke test: load gnuplot and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_go: Smoke test: load go and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('package main', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_godot_resource: Smoke test: load godot_resource and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gomod: Smoke test: load gomod and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("module example.com/hello\n\ngo 1.21", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gosum: Smoke test: load gosum and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('example.com/pkg v1.0.0 h1:abc=', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gotmpl: Smoke test: load gotmpl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gowork: Smoke test: load gowork and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gpg: Smoke test: load gpg and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_graphql: Smoke test: load graphql and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('type Query { hello: String }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gren: Smoke test: load gren and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('module Main exposing (..)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_groovy: Smoke test: load groovy and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('def x = 1', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_gstlaunch: Smoke test: load gstlaunch and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('fakesrc ! fakesink', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hack: Smoke test: load hack and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("<?hh\nfunction main(): void {}", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hare: Smoke test: load hare and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('export fn main() void = void;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_haskell: Smoke test: load haskell and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('main = putStrLn "hello"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_haxe: Smoke test: load haxe and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('class Main { static function main() {} }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hcl: Smoke test: load hcl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('variable "name" { type = string }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_heex: Smoke test: load heex and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<%= @greeting %>', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hjson: Smoke test: load hjson and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hlsl: Smoke test: load hlsl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('float4 main() : SV_Target { return 0; }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hocon: Smoke test: load hocon and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hoon: Smoke test: load hoon and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_html: Smoke test: load html and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<p>hello</p>', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_htmldjango: Smoke test: load htmldjango and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_http: Smoke test: load http and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hurl: Smoke test: load hurl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_hyprlang: Smoke test: load hyprlang and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('general { border_size = 1 }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_idris: Smoke test: load idris and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('module Main', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ini: Smoke test: load ini and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("[section]\nkey = value", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ispc: Smoke test: load ispc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('export void main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_jai: Smoke test: load jai and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_janet: Smoke test: load janet and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(print "hello")', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_java: Smoke test: load java and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('class Main {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_javadoc: Smoke test: load javadoc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_javascript: Smoke test: load javascript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('console.log(\'hello\');', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_jinja2: Smoke test: load jinja2 and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{{ variable }}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_jq: Smoke test: load jq and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('.[] | select(.key)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_jsdoc: Smoke test: load jsdoc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('/** @param {string} name */', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_json: Smoke test: load json and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{"key": "value"}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_json5: Smoke test: load json5 and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_jsonnet: Smoke test: load jsonnet and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{ key: \'value\' }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_julia: Smoke test: load julia and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('function main() end', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_just: Smoke test: load just and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_kcl: Smoke test: load kcl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_kconfig: Smoke test: load kconfig and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("config FOO\n\tbool \"Enable foo\"", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_kdl: Smoke test: load kdl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('node "value"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_kotlin: Smoke test: load kotlin and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('fun main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_latex: Smoke test: load latex and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("\\documentclass{article}\n\\begin{document}\nHello\n\\end{document}", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_lean: Smoke test: load lean and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('def main : IO Unit := pure ()', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ledger: Smoke test: load ledger and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_less: Smoke test: load less and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_linkerscript: Smoke test: load linkerscript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('SECTIONS { .text : { *(.text) } }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_liquid: Smoke test: load liquid and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_llvm: Smoke test: load llvm and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('define i32 @main() { ret i32 0 }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_lua: Smoke test: load lua and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('print(\'hello\')', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_luadoc: Smoke test: load luadoc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('---@param name string', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_luap: Smoke test: load luap and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('[a-z]+', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_luau: Smoke test: load luau and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('local x: number = 1', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_magik: Smoke test: load magik and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("_method object.hello\n_endmethod", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_make: Smoke test: load make and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("all:\n\techo hello", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_markdown: Smoke test: load markdown and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("\# Hello\n\nWorld", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_markdown_inline: Smoke test: load markdown_inline and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('**bold** and *italic*', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_matlab: Smoke test: load matlab and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("function y = hello(x)\ny = x;\nend", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_mermaid: Smoke test: load mermaid and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("graph TD\nA --> B", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_meson: Smoke test: load meson and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('project(\'hello\', \'c\')', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_mlir: Smoke test: load mlir and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_mojo: Smoke test: load mojo and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_move: Smoke test: load move and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_nasm: Smoke test: load nasm and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_netlinx: Smoke test: load netlinx and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('PROGRAM_NAME=\'hello\'', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_nginx: Smoke test: load nginx and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_nickel: Smoke test: load nickel and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_nim: Smoke test: load nim and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('echo "hello"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ninja: Smoke test: load ninja and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("rule cc\n  command = cc $in -o $out", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_nix: Smoke test: load nix and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{ pkgs ? import <nixpkgs> {} }: pkgs.hello', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_norg: Smoke test: load norg and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_norg_meta: Smoke test: load norg_meta and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_nqc: Smoke test: load nqc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('task main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_nushell: Smoke test: load nushell and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_objc: Smoke test: load objc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('@interface Main @end', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ocaml: Smoke test: load ocaml and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('let () = print_endline "hello"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ocaml_interface: Smoke test: load ocaml_interface and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('val x : int', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ocamllex: Smoke test: load ocamllex and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_odin: Smoke test: load odin and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('package main', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_openscad: Smoke test: load openscad and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_org: Smoke test: load org and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("* Hello\nWorld", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_pascal: Smoke test: load pascal and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('program Hello; begin end.', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_pem: Smoke test: load pem and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("-----BEGIN CERTIFICATE-----\ndata\n-----END CERTIFICATE-----", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_perl: Smoke test: load perl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('print \'hello\';', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_pgn: Smoke test: load pgn and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('1. e4 e5 *', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_php: Smoke test: load php and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<?php echo \'hello\'; ?>', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_phpdoc: Smoke test: load phpdoc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_pkl: Smoke test: load pkl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('name = "hello"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_po: Smoke test: load po and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("msgid \"hello\"\nmsgstr \"world\"", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_poe_filter: Smoke test: load poe_filter and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_pony: Smoke test: load pony and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("actor Main\n  new create(env: Env) => None", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_postscript: Smoke test: load postscript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('/hello { (Hello) show } def', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_powershell: Smoke test: load powershell and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('Write-Host \'hello\'', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_printf: Smoke test: load printf and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('%d %s', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_prisma: Smoke test: load prisma and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('model User { id Int @id }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_prolog: Smoke test: load prolog and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('hello :- write(\'hello\'), nl.', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_promql: Smoke test: load promql and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_properties: Smoke test: load properties and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('key=value', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_proto: Smoke test: load proto and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('syntax = "proto3";', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_prql: Smoke test: load prql and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_psv: Smoke test: load psv and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("a|b|c\n1|2|3", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_pug: Smoke test: load pug and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_puppet: Smoke test: load puppet and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('notify { \'hello\': }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_purescript: Smoke test: load purescript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('module Main where', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_pymanifest: Smoke test: load pymanifest and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('include *.txt', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_python: Smoke test: load python and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('print(\'hello\')', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ql: Smoke test: load ql and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_qmldir: Smoke test: load qmldir and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('module Example', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_qmljs: Smoke test: load qmljs and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("import QtQuick 2.0\nItem {}", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_query: Smoke test: load query and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(identifier) @name', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_r: Smoke test: load r and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('print(\'hello\')', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_racket: Smoke test: load racket and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("\#lang racket\n(define x 1)", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_rasi: Smoke test: load rasi and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_razor: Smoke test: load razor and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_rbs: Smoke test: load rbs and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_re2c: Smoke test: load re2c and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("/*!re2c\n  [a-z]+ { return; }\n*/", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_readline: Smoke test: load readline and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('set editing-mode vi', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_regex: Smoke test: load regex and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_rego: Smoke test: load rego and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("package main\ndefault allow = false", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_requirements: Smoke test: load requirements and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('flask>=2.0', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_rescript: Smoke test: load rescript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('let x = 1', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_robot: Smoke test: load robot and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_roc: Smoke test: load roc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ron: Smoke test: load ron and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(key: "value")', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_rst: Smoke test: load rst and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("Hello\n=====\n\nWorld", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_rtf: Smoke test: load rtf and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{\\rtf1 hello}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ruby: Smoke test: load ruby and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('puts \'hello\'', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_rust: Smoke test: load rust and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('fn main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_scala: Smoke test: load scala and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('object Main', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_scheme: Smoke test: load scheme and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(define x 1)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_scss: Smoke test: load scss and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("$color: red;\nbody { color: $color; }", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_slang: Smoke test: load slang and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_smali: Smoke test: load smali and parse a simple snippet' do
    result = TreeSitterLanguagePack.process(".class public LMain;\n.super Ljava/lang/Object;", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_smalltalk: Smoke test: load smalltalk and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_smithy: Smoke test: load smithy and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("namespace example\nstring MyString", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_sml: Smoke test: load sml and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_snakemake: Smoke test: load snakemake and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_solidity: Smoke test: load solidity and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("pragma solidity ^0.8.0;\ncontract Main {}", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_souffle: Smoke test: load souffle and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_sourcepawn: Smoke test: load sourcepawn and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_sparql: Smoke test: load sparql and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('SELECT ?s WHERE { ?s ?p ?o }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_sql: Smoke test: load sql and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('SELECT 1;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_sql_bigquery: Smoke test: load sql_bigquery and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_squirrel: Smoke test: load squirrel and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('function main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ssh_config: Smoke test: load ssh_config and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("Host example\n  HostName example.com", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_stan: Smoke test: load stan and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_starlark: Smoke test: load starlark and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('def hello(): pass', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_superhtml: Smoke test: load superhtml and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_svelte: Smoke test: load svelte and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<script>let x = 1;</script>', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_sway: Smoke test: load sway and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_swift: Smoke test: load swift and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('print("hello")', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_systemverilog: Smoke test: load systemverilog and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tablegen: Smoke test: load tablegen and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('def Hello : Base {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tact: Smoke test: load tact and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tcl: Smoke test: load tcl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('puts hello', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_teal: Smoke test: load teal and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_templ: Smoke test: load templ and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tera: Smoke test: load tera and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_terraform: Smoke test: load terraform and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('resource "null_resource" "main" {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_test: Smoke test: load test and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("===========\nTest\n===========\n---\n(node)", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_textproto: Smoke test: load textproto and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('key: "value"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_thrift: Smoke test: load thrift and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('service HelloService {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tlaplus: Smoke test: load tlaplus and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("---- MODULE Main ----\n====", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tmux: Smoke test: load tmux and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_todotxt: Smoke test: load todotxt and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_toml: Smoke test: load toml and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('key = "value"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tsv: Smoke test: load tsv and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("a\tb\tc\n1\t2\t3", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_tsx: Smoke test: load tsx and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('const App = () => <div />;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_turtle: Smoke test: load turtle and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_twig: Smoke test: load twig and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('{{ variable }}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_typescript: Smoke test: load typescript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('const x: number = 42;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_typespec: Smoke test: load typespec and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_typoscript: Smoke test: load typoscript and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_typst: Smoke test: load typst and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('#let x = 1', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_udev: Smoke test: load udev and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('ACTION=="add", KERNEL=="sd*"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ungrammar: Smoke test: load ungrammar and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("Root = Item*\nItem = 'token'", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_uxntal: Smoke test: load uxntal and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('|0100 LIT 01', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_v: Smoke test: load v and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('fn main() {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_vb: Smoke test: load vb and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("Module Main\nEnd Module", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_verilog: Smoke test: load verilog and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('module main; endmodule', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_vhdl: Smoke test: load vhdl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('entity main is end main;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_vhs: Smoke test: load vhs and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_vim: Smoke test: load vim and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('echo \'hello\'', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_vimdoc: Smoke test: load vimdoc and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_vrl: Smoke test: load vrl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_vue: Smoke test: load vue and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<template><div>hello</div></template>', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_wast: Smoke test: load wast and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(module)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_wat: Smoke test: load wat and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(module)', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_wgsl: Smoke test: load wgsl and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('@vertex fn main() -> @builtin(position) vec4f { return vec4f(); }', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_wgsl_bevy: Smoke test: load wgsl_bevy and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_wit: Smoke test: load wit and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('package example:pkg;', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_wolfram: Smoke test: load wolfram and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_x86asm: Smoke test: load x86asm and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_xcompose: Smoke test: load xcompose and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('<Multi_key> <a> : "a"', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_xml: Smoke test: load xml and parse a simple snippet' do
    result = TreeSitterLanguagePack.process("<?xml version=\"1.0\"?>\n<root>hello</root>", nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_yaml: Smoke test: load yaml and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('key: value', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_yuck: Smoke test: load yuck and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('(defwidget main [] (label :text "hi"))', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_zig: Smoke test: load zig and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('pub fn main() void {}', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ziggy: Smoke test: load ziggy and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_ziggy_schema: Smoke test: load ziggy_schema and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('x', nil)
    # TODO: unsupported assertion type: method_result
  end

  it 'smoke_zsh: Smoke test: load zsh and parse a simple snippet' do
    result = TreeSitterLanguagePack.process('echo hello', nil)
    # TODO: unsupported assertion type: method_result
  end
end
