// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import TreeSitterLanguagePack

/// E2e tests for category: parsing.
final class ParsingTests: XCTestCase {
    func testParsingGoFunction() throws {
        // Parse a Go function declaration and assert node type
        let tree = try parseString("go", "package main\nfunc main() {}")
        // method_result assertions not yet implemented for Swift
    }

    func testParsingHtmlElement() throws {
        // Parse an HTML element and assert node type
        let tree = try parseString("html", "<div>hello</div>")
        // method_result assertions not yet implemented for Swift
    }

    func testParsingJavascriptClass() throws {
        // Parse a JavaScript class declaration.
        let tree = try parseString("javascript", "class Foo { bar() {} }")
        XCTAssertGreaterThanOrEqual(tree.root_child_count, 1)
        // method_result assertions not yet implemented for Swift
    }

    func testParsingJavascriptVariable() throws {
        // Parse a JavaScript variable declaration and assert node type
        let tree = try parseString("javascript", "const x = 1;")
        // method_result assertions not yet implemented for Swift
    }

    func testParsingPythonFunction() throws {
        // Parse a Python function definition and assert node type
        let tree = try parseString("python", "def hello(): pass")
        // method_result assertions not yet implemented for Swift
    }

    func testParsingRustFunction() throws {
        // Parse a Rust function definition and assert node type
        let tree = try parseString("rust", "fn main() {}")
        // method_result assertions not yet implemented for Swift
    }

    func testParsingRustStruct() throws {
        // Parse a Rust struct definition.
        let tree = try parseString("rust", "struct Point { x: f64, y: f64 }")
        XCTAssertGreaterThanOrEqual(tree.root_child_count, 1)
    }

}
