// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: language-detection

use tree_sitter_language_pack::process;

#[test]
fn test_ambiguity_h_extension() {
    // The .h extension is ambiguous (could be C, C++, or Objective-C)
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert!(!result.is_empty(), "expected non-empty value");
}

#[test]
fn test_ambiguity_py_extension() {
    // The .py extension is NOT ambiguous (only maps to python)
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert!(result.is_empty(), "expected empty value");
}

#[test]
fn test_ambiguity_unknown_extension() {
    // Unknown extension returns empty (no ambiguity data)
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert!(result.is_empty(), "expected empty value");
}

#[test]
fn test_detect_content_bash_shebang() {
    // detect_language_from_content recognizes #!/bin/bash shebang
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"bash"#, "equals assertion failed");
}

#[test]
fn test_detect_content_no_shebang() {
    // detect_language_from_content returns None when no shebang present
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert!(result.is_empty(), "expected empty value");
}

#[test]
fn test_detect_content_python_shebang() {
    // detect_language_from_content recognizes #!/usr/bin/env python3 shebang
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"python"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_cpp() {
    // detect_language_from_extension recognizes .cpp as cpp
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"cpp"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_go() {
    // detect_language_from_extension recognizes .go as go
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"go"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_java() {
    // detect_language_from_extension recognizes .java as java
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"java"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_javascript() {
    // detect_language_from_extension recognizes .js as javascript
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"javascript"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_php() {
    // detect_language_from_extension recognizes .php as php
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"php"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_python() {
    // detect_language_from_extension recognizes .py as python
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"python"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_ruby() {
    // detect_language_from_extension recognizes .rb as ruby
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"ruby"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_rust() {
    // detect_language_from_extension recognizes .rs as rust
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"rust"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_typescript() {
    // detect_language_from_extension recognizes .ts as typescript
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"typescript"#, "equals assertion failed");
}

#[test]
fn test_detect_ext_unknown() {
    // detect_language_from_extension returns None for unknown extension .xyz
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert!(result.is_empty(), "expected empty value");
}

#[test]
fn test_detect_path_dotfile() {
    // detect_language_from_path returns None for dotfile .gitignore (no standard extension)
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert!(result.is_empty(), "expected empty value");
}

#[test]
fn test_detect_path_go_nested() {
    // detect_language_from_path extracts extension from nested path lib/server.go
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"go"#, "equals assertion failed");
}

#[test]
fn test_detect_path_java_root() {
    // detect_language_from_path recognizes Main.java in root directory
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"java"#, "equals assertion failed");
}

#[test]
fn test_detect_path_js_root() {
    // detect_language_from_path recognizes app.js in root directory
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"javascript"#, "equals assertion failed");
}

#[test]
fn test_detect_path_nested() {
    // detect_language_from_path extracts extension from nested path src/main.py
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"python"#, "equals assertion failed");
}

#[test]
fn test_detect_path_no_extension() {
    // detect_language_from_path returns None for extensionless file Makefile
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert!(result.is_empty(), "expected empty value");
}

#[test]
fn test_detect_path_rust_src() {
    // detect_language_from_path extracts extension from nested path src/main.rs
    let source = String::new();
    let config = None;
    let result = process(&source, config).expect("should succeed");
    assert_eq!(result.trim(), r#"rust"#, "equals assertion failed");
}
