// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:35f4e6ffcc8758e0c8014dca6f91f82474be64376a4aac819d3e765ded27bb21
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

/** Configuration for an extraction run against a single language. */
public record ExtractionConfig(String language, String patterns) {
	public static ExtractionConfigBuilder builder() {
		return new ExtractionConfigBuilder();
	}
}
