// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fd99bd602ab9cd8561d70bed181199e3d5f10d2dc2747457d10b6800aed6ef2d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

/**
 * Thread-safe registry of tree-sitter language parsers.
 *
 * Manages both statically compiled and dynamically loaded language grammars.
 * Use [`LanguageRegistry::new()`] for the default registry, or access the
 * global instance via the module-level convenience functions
 * ([`crate::get_language`], [`crate::available_languages`], etc.).
 *
 * # Example
 *
 * ```no_run use tree_sitter_language_pack::{LanguageRegistry, ProcessConfig};
 *
 * let registry = LanguageRegistry::new(); let langs =
 * registry.available_languages(); println!("Available: {:?}", langs);
 *
 * let config = ProcessConfig::new("python").all(); let result =
 * registry.process("def hello(): pass", &config).unwrap(); println!("Structure:
 * {:?}", result.structure); ```
 */
public class LanguageRegistry implements AutoCloseable {
	private final MemorySegment handle;

	LanguageRegistry(MemorySegment handle) {
		this.handle = handle;
	}

	MemorySegment handle() {
		return this.handle;
	}

	@Override
	public void close() {
		if (handle != null && !handle.equals(MemorySegment.NULL)) {
			try {
				NativeLib.TS_PACK_LANGUAGE_REGISTRY_FREE.invoke(handle);
			} catch (Throwable e) {
				throw new RuntimeException("Failed to free LanguageRegistry: " + e.getMessage(), e);
			}
		}
	}
}
