// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2b089373e3cc76054c4c647d8280cff66395b22ec690168f512b36311d2e3906
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * Configuration for the {@code process()} function.
 *
 * <p>
 * Controls which analysis features are enabled and whether chunking is
 * performed.
 *
 * <p>
 * # Examples
 *
 * <p>
 * {@code }{@code } use tree_sitter_language_pack::ProcessConfig;
 *
 * <p>
 * // Defaults: structure + imports + exports enabled let config =
 * ProcessConfig::new("python");
 *
 * <p>
 * // With chunking let config =
 * ProcessConfig::new("python").with_chunking(1000);
 *
 * <p>
 * // Everything enabled let config = ProcessConfig::new("python").all();
 * {@code }{@code }
 */
public record ProcessConfig(
		/** Language name (required). */
		String language,
		/** Extract structural items (functions, classes, etc.). Default: true. */
		boolean structure,
		/** Extract import statements. Default: true. */
		boolean imports,
		/** Extract export statements. Default: true. */
		boolean exports,
		/** Extract comments. Default: false. */
		boolean comments,
		/** Extract docstrings. Default: false. */
		boolean docstrings,
		/** Extract symbol definitions. Default: false. */
		boolean symbols,
		/** Include parse diagnostics. Default: false. */
		boolean diagnostics,
		/** Maximum chunk size in bytes. {@code None} disables chunking. */
		@JsonProperty("chunk_max_size") Optional<Long> chunkMaxSize,
		/** Custom extraction patterns to run against the parsed tree. */
		Optional<String> extractions) {
	public static ProcessConfigBuilder builder() {
		return new ProcessConfigBuilder();
	}
}
