// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d49c94717b108d8efa9ec233dcb8fce7a662cdc796b68219f67e61c88a533f9e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;

/**
 * A single match from a tree-sitter query, with captured nodes.
 */
public class QueryMatchBuilder {

	private long patternIndex = 0;
	private List<String> captures = List.of();

	/** Sets the patternIndex field. */
	public QueryMatchBuilder withPatternIndex(final long value) {
		this.patternIndex = value;
		return this;
	}

	/** Sets the captures field. */
	public QueryMatchBuilder withCaptures(final List<String> value) {
		this.captures = value;
		return this;
	}

	/** Builds the QueryMatch instance. */
	public QueryMatch build() {
		return new QueryMatch(patternIndex, captures);
	}
}
