// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:79dad767bdf0add54ca825bbf76c6979e52f10bb2f3562771f6046fe7349f9f8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;

public final class TreeSitterLanguagePack {
	private TreeSitterLanguagePack() {
	}

	/**
	 * Detect language name from a file extension (without leading dot).
	 *
	 * <p>
	 * Returns `None` for unrecognized extensions. The match is case-insensitive.
	 *
	 * <p>
	 * ``` use tree_sitter_language_pack::detect_language_from_extension;
	 * assert_eq!(detect_language_from_extension("py"), Some("python"));
	 * assert_eq!(detect_language_from_extension("RS"), Some("rust"));
	 * assert_eq!(detect_language_from_extension("xyz"), None); ```
	 */
	public static String detectLanguageFromExtension(final String ext) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(ext, "ext must not be null");
		return TreeSitterLanguagePackRs.detectLanguageFromExtension(ext).orElseThrow();
	}

	/**
	 * Detect language name from a file path.
	 *
	 * <p>
	 * Extracts the file extension and looks it up. Returns `None` if the path has
	 * no extension or the extension is not recognized.
	 *
	 * <p>
	 * ``` use tree_sitter_language_pack::detect_language_from_path;
	 * assert_eq!(detect_language_from_path("src/main.rs"), Some("rust"));
	 * assert_eq!(detect_language_from_path("README.md"), Some("markdown"));
	 * assert_eq!(detect_language_from_path("Makefile"), None); ```
	 */
	public static String detectLanguageFromPath(final String path) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(path, "path must not be null");
		return TreeSitterLanguagePackRs.detectLanguageFromPath(path).orElseThrow();
	}

	/**
	 * Detect language name from file content using the shebang line (`#!`).
	 *
	 * <p>
	 * Inspects only the first line of `content`. If it begins with `#!`, the
	 * interpreter name is extracted and mapped to a language name.
	 *
	 * <p>
	 * Handles common patterns: - `#!/usr/bin/env python3` → `"python"` -
	 * `#!/bin/bash` → `"bash"` - `#!/usr/bin/env node` → `"javascript"`
	 *
	 * <p>
	 * The `-S` flag accepted by some `env` implementations is skipped
	 * automatically. Version suffixes (e.g. `python3.11`, `ruby3.2`) are stripped
	 * before matching.
	 *
	 * <p>
	 * Returns `None` when content does not start with `#!`, the shebang is
	 * malformed, or the interpreter is not recognised.
	 *
	 * <p>
	 * ``` use tree_sitter_language_pack::detect_language_from_content;
	 * assert_eq!(detect_language_from_content("#!/usr/bin/env python3\npass"),
	 * Some("python")); assert_eq!(detect_language_from_content("#!/bin/bash\necho
	 * hi"), Some("bash")); assert_eq!(detect_language_from_content("no shebang
	 * here"), None); ```
	 */
	public static String detectLanguageFromContent(final String content) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(content, "content must not be null");
		return TreeSitterLanguagePackRs.detectLanguageFromContent(content).orElseThrow();
	}

	/** Get a `NodeInfo` snapshot of the root node. */
	public static NodeInfo rootNodeInfo(final Tree tree) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		return TreeSitterLanguagePackRs.rootNodeInfo(tree);
	}

	/**
	 * Find all nodes matching the given type name, returning their `NodeInfo`.
	 *
	 * <p>
	 * Performs a depth-first traversal. Returns an empty vec if no matches.
	 */
	public static List<NodeInfo> findNodesByType(final Tree tree, final String nodeType)
			throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		java.util.Objects.requireNonNull(nodeType, "nodeType must not be null");
		return TreeSitterLanguagePackRs.findNodesByType(tree, nodeType);
	}

	/**
	 * Get `NodeInfo` for all named children of the root node.
	 *
	 * <p>
	 * Useful for understanding the top-level structure of a file (e.g., list of
	 * function definitions, class declarations, imports).
	 */
	public static List<NodeInfo> namedChildrenInfo(final Tree tree) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		return TreeSitterLanguagePackRs.namedChildrenInfo(tree);
	}

	/**
	 * Parse source code with the named language, returning the syntax tree.
	 *
	 * <p>
	 * Uses the global registry to look up the language by name. Caches parsers
	 * per-thread so repeated calls for the same language avoid re-creating the
	 * parser.
	 *
	 * <p>
	 * # Examples
	 *
	 * <p>
	 * ```no_run let tree = tree_sitter_language_pack::parse_string("python", b"def
	 * hello(): pass").unwrap(); assert_eq!(tree.root_node().kind(), "module"); ```
	 */
	public static Tree parseString(final String language, final byte[] source)
			throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(language, "language must not be null");
		java.util.Objects.requireNonNull(source, "source must not be null");
		return TreeSitterLanguagePackRs.parseString(language, source);
	}

	/**
	 * Check whether any node in the tree matches the given type name.
	 *
	 * <p>
	 * Performs a depth-first traversal using `TreeCursor`.
	 */
	public static boolean treeContainsNodeType(final Tree tree, final String nodeType)
			throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		java.util.Objects.requireNonNull(nodeType, "nodeType must not be null");
		return TreeSitterLanguagePackRs.treeContainsNodeType(tree, nodeType);
	}

	/**
	 * Check whether the tree contains any ERROR or MISSING nodes.
	 *
	 * <p>
	 * Useful for determining if the parse was clean or had syntax errors.
	 */
	public static boolean treeHasErrorNodes(final Tree tree) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		return TreeSitterLanguagePackRs.treeHasErrorNodes(tree);
	}

	/**
	 * Return the S-expression representation of the entire tree.
	 *
	 * <p>
	 * This is the standard tree-sitter debug format, useful for logging, snapshot
	 * testing, and debugging grammars.
	 */
	public static String treeToSexp(final Tree tree) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		return TreeSitterLanguagePackRs.treeToSexp(tree);
	}

	/**
	 * Count the number of ERROR and MISSING nodes in the tree.
	 *
	 * <p>
	 * Returns 0 for a clean parse.
	 */
	public static long treeErrorCount(final Tree tree) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		return TreeSitterLanguagePackRs.treeErrorCount(tree);
	}

	/**
	 * Get the highlights query for a language, if bundled.
	 *
	 * <p>
	 * Returns the contents of `highlights.scm` as a static string, or `None` if no
	 * highlights query is bundled for this language.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ``` use tree_sitter_language_pack::get_highlights_query;
	 *
	 * <p>
	 * // Returns Some(...) for languages with bundled queries let query =
	 * get_highlights_query("python"); // Returns None for languages without bundled
	 * highlights queries let missing = get_highlights_query("nonexistent_lang");
	 * assert!(missing.is_none()); ```
	 */
	public static String getHighlightsQuery(final String language) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(language, "language must not be null");
		return TreeSitterLanguagePackRs.getHighlightsQuery(language).orElseThrow();
	}

	/**
	 * Get the injections query for a language, if bundled.
	 *
	 * <p>
	 * Returns the contents of `injections.scm` as a static string, or `None` if no
	 * injections query is bundled for this language.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ``` use tree_sitter_language_pack::get_injections_query;
	 *
	 * <p>
	 * let query = get_injections_query("markdown"); // Returns None for languages
	 * without bundled injections queries let missing =
	 * get_injections_query("nonexistent_lang"); assert!(missing.is_none()); ```
	 */
	public static String getInjectionsQuery(final String language) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(language, "language must not be null");
		return TreeSitterLanguagePackRs.getInjectionsQuery(language).orElseThrow();
	}

	/**
	 * Get the locals query for a language, if bundled.
	 *
	 * <p>
	 * Returns the contents of `locals.scm` as a static string, or `None` if no
	 * locals query is bundled for this language.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ``` use tree_sitter_language_pack::get_locals_query;
	 *
	 * <p>
	 * let query = get_locals_query("python"); // Returns None for languages without
	 * bundled locals queries let missing = get_locals_query("nonexistent_lang");
	 * assert!(missing.is_none()); ```
	 */
	public static String getLocalsQuery(final String language) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(language, "language must not be null");
		return TreeSitterLanguagePackRs.getLocalsQuery(language).orElseThrow();
	}

	/**
	 * Execute a tree-sitter query pattern against a parsed tree.
	 *
	 * <p>
	 * The `query_source` is an S-expression pattern like: ```text
	 * (function_definition name: (identifier) @name) ```
	 *
	 * <p>
	 * Returns all matches with their captured nodes.
	 *
	 * <p>
	 * # Arguments
	 *
	 * <p>
	 * * `tree` - The parsed syntax tree to query. * `language` - Language name
	 * (used to compile the query pattern). * `query_source` - The tree-sitter query
	 * pattern string. * `source` - The original source code bytes (needed for
	 * capture resolution).
	 *
	 * <p>
	 * # Examples
	 *
	 * <p>
	 * ```no_run let tree = tree_sitter_language_pack::parse_string("python", b"def
	 * hello(): pass").unwrap(); let matches = tree_sitter_language_pack::run_query(
	 * &tree, "python", "(function_definition name: (identifier) @fn_name)", b"def
	 * hello(): pass", ).unwrap(); assert!(!matches.is_empty()); ```
	 */
	public static List<QueryMatch> runQuery(final Tree tree, final String language, final String querySource,
			final byte[] source) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(tree, "tree must not be null");
		java.util.Objects.requireNonNull(language, "language must not be null");
		java.util.Objects.requireNonNull(querySource, "querySource must not be null");
		java.util.Objects.requireNonNull(source, "source must not be null");
		return TreeSitterLanguagePackRs.runQuery(tree, language, querySource, source);
	}

	/**
	 * Get a tree-sitter [`Language`] by name using the global registry.
	 *
	 * <p>
	 * Resolves language aliases (e.g., `"shell"` maps to `"bash"`). When the
	 * `download` feature is enabled (default), automatically downloads the parser
	 * from GitHub releases if not found locally.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns [`Error::LanguageNotFound`] if the language is not recognized, or
	 * [`Error::Download`] if auto-download fails.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::get_language;
	 *
	 * <p>
	 * let lang = get_language("python").unwrap(); // Use the Language with a
	 * tree-sitter Parser let mut parser = tree_sitter::Parser::new();
	 * parser.set_language(&lang).unwrap(); let tree = parser.parse("x = 1",
	 * None).unwrap(); assert_eq!(tree.root_node().kind(), "module"); ```
	 */
	public static Language getLanguage(final String name) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(name, "name must not be null");
		return TreeSitterLanguagePackRs.getLanguage(name);
	}

	/**
	 * Get a tree-sitter [`Parser`] pre-configured for the given language.
	 *
	 * <p>
	 * This is a convenience function that calls [`get_language`] and configures a
	 * new parser in one step.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns [`Error::LanguageNotFound`] if the language is not recognized, or
	 * [`Error::ParserSetup`] if the language cannot be applied to the parser.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::get_parser;
	 *
	 * <p>
	 * let mut parser = get_parser("rust").unwrap(); let tree = parser.parse("fn
	 * main() {}", None).unwrap(); assert!(!tree.root_node().has_error()); ```
	 */
	public static Parser getParser(final String name) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(name, "name must not be null");
		return TreeSitterLanguagePackRs.getParser(name);
	}

	/**
	 * List all available language names (sorted, deduplicated, includes aliases).
	 *
	 * <p>
	 * Returns names of both statically compiled and dynamically loadable languages,
	 * plus any configured aliases.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::available_languages;
	 *
	 * <p>
	 * let langs = available_languages(); for name in &langs { println!("{}", name);
	 * } ```
	 */
	public static List<String> availableLanguages() throws TreeSitterLanguagePackRsException {
		return TreeSitterLanguagePackRs.availableLanguages();
	}

	/**
	 * Check if a language is available by name or alias.
	 *
	 * <p>
	 * Returns `true` if the language can be loaded (statically compiled,
	 * dynamically available, or a known alias for one of these).
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::has_language;
	 *
	 * <p>
	 * assert!(has_language("python")); assert!(has_language("shell")); // alias for
	 * "bash" assert!(!has_language("nonexistent_language")); ```
	 */
	public static boolean hasLanguage(final String name) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(name, "name must not be null");
		return TreeSitterLanguagePackRs.hasLanguage(name);
	}

	/**
	 * Return the number of available languages.
	 *
	 * <p>
	 * Includes statically compiled languages, dynamically loadable languages, and
	 * aliases.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::language_count;
	 *
	 * <p>
	 * let count = language_count(); println!("{} languages available", count); ```
	 */
	public static long languageCount() throws TreeSitterLanguagePackRsException {
		return TreeSitterLanguagePackRs.languageCount();
	}

	/**
	 * Process source code and extract file intelligence using the global registry.
	 *
	 * <p>
	 * Parses the source with tree-sitter and extracts metrics, structure, imports,
	 * exports, comments, docstrings, symbols, diagnostics, and/or chunks based on
	 * the flags set in [`ProcessConfig`].
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the language is not found or parsing fails.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::{ProcessConfig, process};
	 *
	 * <p>
	 * let config = ProcessConfig::new("python").all(); let result = process("def
	 * hello(): pass", &config).unwrap(); println!("Language: {}", result.language);
	 * println!("Lines: {}", result.metrics.total_lines); println!("Structures: {}",
	 * result.structure.len()); ```
	 */
	public static ProcessResult process(final String source, final ProcessConfig config)
			throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(source, "source must not be null");
		java.util.Objects.requireNonNull(config, "config must not be null");
		return TreeSitterLanguagePackRs.process(source, config);
	}

	/**
	 * Run extraction patterns against source code.
	 *
	 * <p>
	 * Convenience wrapper around [`extract::extract`].
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the language is not found, parsing fails, or a query
	 * pattern is invalid.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use ahash::AHashMap; use
	 * tree_sitter_language_pack::{ExtractionConfig, ExtractionPattern,
	 * CaptureOutput, extract_patterns};
	 *
	 * <p>
	 * let mut patterns = AHashMap::new(); patterns.insert("fns".to_string(),
	 * ExtractionPattern { query: "(function_definition name:
	 * (identifier) @fn_name)".to_string(), capture_output:
	 * CaptureOutput::default(), child_fields: Vec::new(), max_results: None,
	 * byte_range: None, }); let config = ExtractionConfig { language:
	 * "python".to_string(), patterns }; let result = extract_patterns("def hello():
	 * pass", &config).unwrap(); ```
	 */
	public static ExtractionResult extractPatterns(final String source, final ExtractionConfig config)
			throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(source, "source must not be null");
		java.util.Objects.requireNonNull(config, "config must not be null");
		return TreeSitterLanguagePackRs.extractPatterns(source, config);
	}

	/**
	 * Validate extraction patterns without running them.
	 *
	 * <p>
	 * Convenience wrapper around [`extract::validate_extraction`].
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the language cannot be loaded.
	 */
	public static ValidationResult validateExtraction(final ExtractionConfig config)
			throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(config, "config must not be null");
		return TreeSitterLanguagePackRs.validateExtraction(config);
	}

	/**
	 * Initialize the language pack with the given configuration.
	 *
	 * <p>
	 * Applies any custom cache directory, then downloads all languages and groups
	 * specified in the config. This is the recommended entry point when you want to
	 * pre-warm the cache before use.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if configuration cannot be applied or if downloads fail.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::{PackConfig, init};
	 *
	 * <p>
	 * let config = PackConfig { cache_dir: None, languages:
	 * Some(vec!["python".to_string(), "rust".to_string()]), groups: None, };
	 * init(&config).unwrap(); ```
	 */
	public static void init(final PackConfig config) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(config, "config must not be null");
		TreeSitterLanguagePackRs.init(config);
	}

	/**
	 * Apply download configuration without downloading anything.
	 *
	 * <p>
	 * Use this to set a custom cache directory before the first call to
	 * [`get_language`] or any download function. Changing the cache dir after
	 * languages have been registered has no effect on already-loaded languages.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the lock cannot be acquired.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use std::path::PathBuf; use tree_sitter_language_pack::{PackConfig,
	 * configure};
	 *
	 * <p>
	 * let config = PackConfig { cache_dir: Some(PathBuf::from("/tmp/my-parsers")),
	 * languages: None, groups: None, }; configure(&config).unwrap(); ```
	 */
	public static void configure(final PackConfig config) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(config, "config must not be null");
		TreeSitterLanguagePackRs.configure(config);
	}

	/**
	 * Download specific languages to the local cache.
	 *
	 * <p>
	 * Returns the number of newly downloaded languages (languages that were already
	 * cached are not counted).
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if any language is not available in the manifest or if the
	 * download fails.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::download;
	 *
	 * <p>
	 * let count = download(&["python", "rust", "typescript"]).unwrap();
	 * println!("Downloaded {} new languages", count); ```
	 */
	public static long download(final List<String> names) throws TreeSitterLanguagePackRsException {
		java.util.Objects.requireNonNull(names, "names must not be null");
		return TreeSitterLanguagePackRs.download(names);
	}

	/**
	 * Download all available languages from the remote manifest.
	 *
	 * <p>
	 * Returns the number of newly downloaded languages.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the manifest cannot be fetched or a download fails.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::download_all;
	 *
	 * <p>
	 * let count = download_all().unwrap(); println!("Downloaded {} languages",
	 * count); ```
	 */
	public static long downloadAll() throws TreeSitterLanguagePackRsException {
		return TreeSitterLanguagePackRs.downloadAll();
	}

	/**
	 * Return all language names available in the remote manifest (305).
	 *
	 * <p>
	 * Fetches (and caches) the remote manifest to discover the full list of
	 * downloadable languages. Use [`downloaded_languages`] to list what is already
	 * cached locally.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the manifest cannot be fetched.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::manifest_languages;
	 *
	 * <p>
	 * let langs = manifest_languages().unwrap(); println!("{} languages available
	 * for download", langs.len()); ```
	 */
	public static List<String> manifestLanguages() throws TreeSitterLanguagePackRsException {
		return TreeSitterLanguagePackRs.manifestLanguages();
	}

	/**
	 * Return languages that are already downloaded and cached locally.
	 *
	 * <p>
	 * Does not perform any network requests. Returns an empty list if the cache
	 * directory does not exist or cannot be read.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::downloaded_languages;
	 *
	 * <p>
	 * let langs = downloaded_languages(); println!("{} languages already cached",
	 * langs.len()); ```
	 */
	public static List<String> downloadedLanguages() throws TreeSitterLanguagePackRsException {
		return TreeSitterLanguagePackRs.downloadedLanguages();
	}

	/**
	 * Delete all cached parser shared libraries.
	 *
	 * <p>
	 * Resets the cache registration so the next call to [`get_language`] or a
	 * download function will re-register the (now empty) cache directory.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the cache directory cannot be removed.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::clean_cache;
	 *
	 * <p>
	 * clean_cache().unwrap(); println!("Cache cleared"); ```
	 */
	public static void cleanCache() throws TreeSitterLanguagePackRsException {
		TreeSitterLanguagePackRs.cleanCache();
	}

	/**
	 * Return the effective cache directory path.
	 *
	 * <p>
	 * This is either the custom path set via [`configure`] / [`init`] or the
	 * default: `~/.cache/tree-sitter-language-pack/v{version}/libs/`.
	 *
	 * <p>
	 * # Errors
	 *
	 * <p>
	 * Returns an error if the system cache directory cannot be determined.
	 *
	 * <p>
	 * # Example
	 *
	 * <p>
	 * ```no_run use tree_sitter_language_pack::cache_dir;
	 *
	 * <p>
	 * let dir = cache_dir().unwrap(); println!("Cache directory: {}",
	 * dir.display()); ```
	 */
	public static java.nio.file.Path cacheDir() throws TreeSitterLanguagePackRsException {
		return TreeSitterLanguagePackRs.cacheDir();
	}
}
