// Generated by alef. Do not edit by hand.
// alef:hash:60cbb132261b095585a925a455bb881a5ddbd8105bceeb452a13f0d6b7ed6861
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package io.xberg.tslp.android

@Suppress("TooManyFunctions")
object TreeSitterLanguagePackBridge {
    init { System.loadLibrary("ts_pack_jni") }

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeAvailableLanguages(): String

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeDetectLanguage(path: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeDetectLanguageFromContent(content: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeDetectLanguageFromExtension(ext: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeDetectLanguageFromPath(path: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetFoldsQuery(language: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetHighlightsQuery(language: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetIndentsQuery(language: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetInjectionsQuery(language: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetLanguage(name: String): Long

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetLocalsQuery(language: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetParser(name: String): Long

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeGetTagsQuery(language: String): String?

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeHasLanguage(name: String): Boolean

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeLanguageCount(): Long

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativePrefetch(languages: String)

    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeProcess(source: String, config: String): String

    // JNI external funs for client instance methods.
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeLanguageRegistryGetLanguage(handle: Long, requestJson: String): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeLanguageRegistryAvailableLanguages(handle: Long): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeLanguageRegistryHasParser(handle: Long, requestJson: String): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeLanguageRegistryHasLanguage(handle: Long, requestJson: String): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeLanguageRegistryLanguageCount(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeLanguageRegistryProcess(handle: Long, requestJson: String): String
    external fun nativeFreeLanguageRegistry(handle: Long)
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeKind(handle: Long): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeKindId(handle: Long): Short
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeStartByte(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeEndByte(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeByteRange(handle: Long): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeStartPosition(handle: Long): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeEndPosition(handle: Long): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeIsNamed(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeIsError(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeIsMissing(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeIsExtra(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeHasError(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeParent(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeChild(handle: Long, requestJson: String): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeChildCount(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeNamedChild(handle: Long, requestJson: String): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeNamedChildCount(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeChildByFieldName(handle: Long, requestJson: String): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeToSexp(handle: Long): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeNodeWalk(handle: Long): Long
    external fun nativeFreeNode(handle: Long)
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeParserSetMaxSourceBytes(handle: Long, requestJson: String)
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeParserSetParseTimeoutMs(handle: Long, requestJson: String)
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeParserSetLanguage(handle: Long, requestJson: String)
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeParserParse(handle: Long, requestJson: String): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeParserParseBytes(handle: Long, source: ByteArray): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeParserReset(handle: Long)
    external fun nativeFreeParser(handle: Long)
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeTreeRootNode(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeTreeWalk(handle: Long): Long
    external fun nativeFreeTree(handle: Long)
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeTreeCursorNode(handle: Long): Long
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeTreeCursorGotoFirstChild(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeTreeCursorGotoParent(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeTreeCursorGotoNextSibling(handle: Long): Boolean
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeTreeCursorFieldName(handle: Long): String?
    external fun nativeFreeTreeCursor(handle: Long)

    // JNI external funs for data-class instance methods.
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeProcessConfigWithChunking(selfJson: String, requestJson: String): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeProcessConfigAll(selfJson: String): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeProcessConfigMinimal(selfJson: String): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeProcessConfigWithDataExtraction(selfJson: String, requestJson: String): String
    @Throws(TreeSitterLanguagePackBridgeException::class)
    external fun nativeProcessConfigValidate(selfJson: String)
}
