// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:913692c7ef72542801bd881a2cce6f8dffcdc965e201426a739987ca86e45d52
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { process, parse_string, treeContainsNodeType } from '@kreuzberg/tree-sitter-language-pack';

describe('parsing', () => {
  it('parsing_go_function: Parse a Go function declaration and assert node type', () => {
    const tree = parse_string("go", "package main\nfunc main() {}");
    expect(treeContainsNodeType(tree, "function_declaration")).toBe(true);
  });

  it('parsing_html_element: Parse an HTML element and assert node type', () => {
    const tree = parse_string("html", "<div>hello</div>");
    expect(treeContainsNodeType(tree, "element")).toBe(true);
  });

  it('parsing_javascript_class: Parse a JavaScript class declaration.', () => {
    const tree = parse_string("javascript", "class Foo { bar() {} }");
    expect(tree.rootChildCount).toBeGreaterThanOrEqual(1);
    expect(treeContainsNodeType(tree, "class_declaration")).toBe(true);
  });

  it('parsing_javascript_variable: Parse a JavaScript variable declaration and assert node type', () => {
    const tree = parse_string("javascript", "const x = 1;");
    expect(treeContainsNodeType(tree, "lexical_declaration")).toBe(true);
  });

  it('parsing_python_function: Parse a Python function definition and assert node type', () => {
    const tree = parse_string("python", "def hello(): pass");
    expect(treeContainsNodeType(tree, "function_definition")).toBe(true);
  });

  it('parsing_rust_function: Parse a Rust function definition and assert node type', () => {
    const tree = parse_string("rust", "fn main() {}");
    expect(treeContainsNodeType(tree, "function_item")).toBe(true);
  });

  it('parsing_rust_struct: Parse a Rust struct definition.', () => {
    const tree = parse_string("rust", "struct Point { x: f64, y: f64 }");
    expect(tree.rootChildCount).toBeGreaterThanOrEqual(1);
  });
});
