// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b54e2240278e8493a342056aee7df0a4874f0de6510b4843a4ad0b09b82b58e1
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
