// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.tslp;

import java.util.*;

public record DocstringInfo(String text, DocstringFormat format, Span span, Optional<String> associatedItem, java.util.List<DocSection> parsedSections) {}
