// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.tslp;

import java.util.List;
import java.util.Optional;

public record ImportInfo(String source, List<String> items, Optional<String> alias, boolean isWildcard, Span span) { }
