// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.tslp;

import java.util.List;

public record ProcessResult(String language, FileMetrics metrics, List<StructureItem> structure, List<ImportInfo> imports, List<ExportInfo> exports, List<CommentInfo> comments, List<DocstringInfo> docstrings, List<SymbolInfo> symbols, List<Diagnostic> diagnostics, List<CodeChunk> chunks, String extractions) { }
