// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.tslp;

import java.util.*;

public record StructureItem(StructureKind kind, Optional<String> name, Optional<String> visibility, Span span, java.util.List<StructureItem> children, java.util.List<String> decorators, Optional<String> docComment, Optional<String> signature, Optional<Span> bodySpan) {}
