# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ad2c61a4a33c0a846543a76ea7eaf53475027c1f9f775b884ebb5affaa0ffd8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: parsing

test_that("parsing_go_function: Parse a Go function declaration and assert node type", {
  tree <- parse_string(language = "go", source = "package main\nfunc main() {}")
  expect_true(tree_contains_node_type(tree, "function_declaration"))
})

test_that("parsing_html_element: Parse an HTML element and assert node type", {
  tree <- parse_string(language = "html", source = "<div>hello</div>")
  expect_true(tree_contains_node_type(tree, "element"))
})

test_that("parsing_javascript_class: Parse a JavaScript class declaration.", {
  tree <- parse_string(language = "javascript", source = "class Foo { bar() {} }")
  expect_true(tree$root_child_count >= 1)
  expect_true(tree_contains_node_type(tree, "class_declaration"))
})

test_that("parsing_javascript_variable: Parse a JavaScript variable declaration and assert node type", {
  tree <- parse_string(language = "javascript", source = "const x = 1;")
  expect_true(tree_contains_node_type(tree, "lexical_declaration"))
})

test_that("parsing_python_function: Parse a Python function definition and assert node type", {
  tree <- parse_string(language = "python", source = "def hello(): pass")
  expect_true(tree_contains_node_type(tree, "function_definition"))
})

test_that("parsing_rust_function: Parse a Rust function definition and assert node type", {
  tree <- parse_string(language = "rust", source = "fn main() {}")
  expect_true(tree_contains_node_type(tree, "function_item"))
})

test_that("parsing_rust_struct: Parse a Rust struct definition.", {
  tree <- parse_string(language = "rust", source = "struct Point { x: f64, y: f64 }")
  expect_true(tree$root_child_count >= 1)
})
