# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: process

test_that("process_javascript_exports_detail: JavaScript with exports, verify export count", {
  result <- process(source = "export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n")
  expect_equal(trimws(result$language), "javascript")
  expect_true(length(result$exports) >= 1)
})

test_that("process_python_comments: Python with comments, verify comment count", {
  result <- process(source = "# This is a comment\n# Another comment\ndef hello():\n    # inline comment\n    pass\n")
  expect_equal(trimws(result$language), "python")
  expect_true(length(result$comments) >= 1)
})

test_that("process_python_imports_detail: Python with multiple imports, verify imports contain specific source", {
  result <- process(source = "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n")
  expect_equal(trimws(result$language), "python")
  expect_true(length(result$imports) >= 2)
  expect_true(grepl("os", result$import_sources, fixed = TRUE))
})

test_that("process_python_metrics_detail: Python code with metrics assertions", {
  result <- process(source = "# module docstring\nimport os\n\ndef hello():\n    # greeting\n    print('hello')\n\ndef world():\n    print('world')\n")
  expect_equal(trimws(result$language), "python")
  expect_true(result$metrics$code_lines >= 4)
  expect_true(result$metrics$comment_lines >= 1)
  expect_true(result$metrics$max_depth >= 1)
})

test_that("process_rust_structure_name: Rust struct with name, verify structure name contains value", {
  result <- process(source = "pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n")
  expect_equal(trimws(result$language), "rust")
  expect_true(length(result$structure) >= 1)
  expect_true(grepl("MyConfig", result$structure_names, fixed = TRUE))
})
