// DO NOT EDIT - auto-generated by alef
// alef:hash:f4f73779a91bc161c92a26978aa8931015478925fd154815ba9dd5314ba30577
package io.xberg.treesitterlanguagepack;

/**
 * The downloaded file's SHA-256 digest did not match the manifest's expected value.
 */
public class ChecksumMismatchException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ChecksumMismatchException with the given message. */
  public ChecksumMismatchException(final String message) {
    super(message);
  }

  /** Creates a new ChecksumMismatchException with the given message and cause. */
  public ChecksumMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
