// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5ce1453e504927c24991df7e7b65eaf9ddfaac0e0478d0e868ea7643dcdf9e83
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.treesitterlanguagepack;

/** Exception thrown when the Rust core reports an unknown error. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class CoreErrorException extends TreeSitterLanguagePackRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CoreErrorException. */
  public CoreErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new CoreErrorException with a cause. */
  public CoreErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
