// DO NOT EDIT - auto-generated by alef
package io.xberg.treesitterlanguagepack;

/**
 * Errors that can occur when using the tree-sitter language pack.
 *
 * Covers language lookup failures, parse errors, query errors, and I/O issues.
 * Feature-gated variants are included when `config`, `download`, or related
 * features are enabled.
 * # Matching on `Error`
 *
 * The set of variants is not stable: new failure modes are added in minor
 * releases, and `Io`, `Json`, and `Toml` exist only under certain feature
 * combinations, so the variant set a downstream crate sees depends on which
 * features it enables. Downstream `match`es must therefore carry a `_` arm;
 * `#[non_exhaustive]` makes the compiler enforce that instead of letting a
 * feature change silently break a build. ~keep
 */
public class ErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ErrorException with the given message. */
  public ErrorException(final String message) {
    super(message);
  }

  /** Creates a new ErrorException with the given message and cause. */
  public ErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
