// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:147c9d37ef6bf71750442b8fe9f8c13612abd7e47bf28a1ab426d1e8a7c47142
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.treesitterlanguagepack;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends TreeSitterLanguagePackRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException. */
  public InvalidInputException(final String message) {
    super(1, message);
  }

  /** Creates a new InvalidInputException with a cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
