// DO NOT EDIT - auto-generated by alef
// alef:hash:b45674e13ee56b8858795345e26cf1d73295ebad5442ec233b70cce09fad27c6
package io.xberg.treesitterlanguagepack;

/**
 * The requested language name (or alias) was not found in the registry.
 */
public class LanguageNotFoundException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LanguageNotFoundException with the given message. */
  public LanguageNotFoundException(final String message) {
    super(message);
  }

  /** Creates a new LanguageNotFoundException with the given message and cause. */
  public LanguageNotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
