// DO NOT EDIT - auto-generated by alef
// alef:hash:e0c0374fa7aa8dd58e747759a64ca48a18dee6948cf36f65aed766f4333c8090
package io.xberg.treesitterlanguagepack;

/**
 * An internal `RwLock` or `Mutex` was poisoned by a previous panic.
 */
public class LockPoisonedException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LockPoisonedException with the given message. */
  public LockPoisonedException(final String message) {
    super(message);
  }

  /** Creates a new LockPoisonedException with the given message and cause. */
  public LockPoisonedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
