// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2c9671e66af208a52973138ec2e377c21be97bc1813febae7f8c63fbc4e45857
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.treesitterlanguagepack;

/** Exception thrown when a Rust panic is contained at the FFI boundary. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class PanicException extends TreeSitterLanguagePackRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PanicException. */
  public PanicException(final String message) {
    super(3, message);
  }

  /** Creates a new PanicException with a cause. */
  public PanicException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
