// DO NOT EDIT - auto-generated by alef
// alef:hash:e3da620bf68c6c2554734349c7799cf6a8b3eb23bc756cf09f450178d3d709e0
package io.xberg.treesitterlanguagepack;

/**
 * The parse was cancelled because it exceeded its configured wall-clock budget.
 *
 * Raised only when a budget is configured — see
 * [`ProcessConfig::parse_timeout_ms`](crate::ProcessConfig::parse_timeout_ms),
 * which defaults to `None`.
 */
public class ParseTimeoutException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseTimeoutException with the given message. */
  public ParseTimeoutException(final String message) {
    super(message);
  }

  /** Creates a new ParseTimeoutException with the given message and cause. */
  public ParseTimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
