// DO NOT EDIT - auto-generated by alef
// alef:hash:1201f6634046b8fef843c2d9fc98d981463ace56a7d7cc7134c2f363208e2515
package io.xberg.treesitterlanguagepack;

/**
 * The language could not be applied to the parser (e.g., ABI version mismatch).
 */
public class ParserSetupException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParserSetupException with the given message. */
  public ParserSetupException(final String message) {
    super(message);
  }

  /** Creates a new ParserSetupException with the given message and cause. */
  public ParserSetupException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
