from tree_sitter import Language, Parser

def get_binding(name: str) -> object: ...
def get_language(name: str) -> Language: ...
def get_parser(name: str) -> Parser: ...
def available_languages() -> list[str]: ...
def has_language(name: str) -> bool: ...
