from __future__ import annotations

GRAPH_NODE_LABELS: dict[str, str] = {
    "file": "File",
    "import": "Import",
    "model": "Model",
    "external_api": "ExternalAPI",
    "external_symbol": "ExternalSymbol",
    "resource": "Resource",
    "xcode_target": "XcodeTarget",
    "xcode_workspace": "XcodeWorkspace",
    "xcode_scheme": "XcodeScheme",
    "cargo_crate": "CargoCrate",
    "cargo_workspace": "CargoWorkspace",
    "clone_group": "CloneGroup",
    "file_clone_group": "FileCloneGroup",
    "api_route": "ApiRoute",
}

GRAPH_REL_TYPES: dict[str, str] = {
    "contains": "CONTAINS",
    "calls": "CALLS",
    "calls_inferred": "CALLS_INFERRED",
    "calls_db": "CALLS_DB",
    "calls_db_model": "CALLS_DB_MODEL",
    "calls_api": "CALLS_API",
    "calls_service": "CALLS_SERVICE",
    "calls_api_external": "CALLS_API_EXTERNAL",
    "calls_external_symbol": "CALLS_EXTERNAL_SYMBOL",
    "imports": "IMPORTS",
    "imports_symbol": "IMPORTS_SYMBOL",
    "implicit_imports_symbol": "IMPLICIT_IMPORTS_SYMBOL",
    "exports_symbol": "EXPORTS_SYMBOL",
    "exports_symbol_as": "EXPORTS_SYMBOL_AS",
    "calls_api_route": "CALLS_API_ROUTE",
    "handled_by": "HANDLED_BY",
    "backed_by_file": "BACKED_BY_FILE",
    "bundled_in_target": "BUNDLED_IN_TARGET",
    "bundles_file": "BUNDLES_FILE",
    "references_project": "REFERENCES_PROJECT",
    "builds_target": "BUILDS_TARGET",
    "defined_in_file": "DEFINED_IN_FILE",
    "has_package": "HAS_PACKAGE",
    "depends_on_package": "DEPENDS_ON_PACKAGE",
    "implements_trait": "IMPLEMENTS_TRAIT",
    "implements_type": "IMPLEMENTS_TYPE",
    "member_of_clone_group": "MEMBER_OF_CLONE_GROUP",
    "member_of_file_clone_group": "MEMBER_OF_FILE_CLONE_GROUP",
    "has_canonical": "HAS_CANONICAL",
    "launches": "LAUNCHES",
    "asset_links": "ASSET_LINKS",
}
