// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7ac1e5fdd85f636dee41a1a791d212f2fd084a0c88cc89f2b920918dcca5c248
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const tree_sitter_language_pack = @import("tree_sitter_language_pack");

// E2e tests for category: query

test "highlights_query_rust" {
    // get_highlights_query returns non-empty string for rust
    const result = try tree_sitter_language_pack.get_highlights_query("rust");
    try testing.expect(result != null);
}

test "injections_query_rust" {
    // get_injections_query returns non-empty for rust
    const result = try tree_sitter_language_pack.get_injections_query("rust");
    try testing.expect(result != null);
}

test "tags_query_kotlin" {
    // get_tags_query returns non-empty string for kotlin
    const result = try tree_sitter_language_pack.get_tags_query("kotlin");
    try testing.expect(result != null);
}

test "tags_query_rust" {
    // get_tags_query returns non-empty string for rust
    const result = try tree_sitter_language_pack.get_tags_query("rust");
    try testing.expect(result != null);
}
