// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';
import { process } from '@kreuzberg/tree-sitter-language-pack';

describe('error-handling', () => {
  it('error_empty_language_name: Parsing with empty language name should error', async () => {
    await expect(async () => {
      await process("hello", null);
    }).rejects.toThrow();
  });

  it('error_handling_empty_source: Parsing an empty string should still produce a tree.', () => {
    process("", null);
  });

  it('error_handling_invalid_syntax: Parsing invalid syntax should produce a tree with error nodes.', () => {
    const result = process("function function function @@@ %%%", null);
    // TODO: unsupported assertion type: method_result
  });

  it('error_handling_unknown_language: Loading a nonexistent language should produce an error.', async () => {
    await expect(async () => {
      await process("", null);
    }).rejects.toThrow();
  });

  it('parse_empty_language: parse_string() returns error with empty language name', async () => {
    await expect(async () => {
      await process("x = 1", null);
    }).rejects.toThrow();
  });

  it('process_unknown_language: process() returns error when config language is unknown', async () => {
    await expect(async () => {
      await process("x = 1", { language: "nonexistent_xyz" });
    }).rejects.toThrow();
  });
});
