// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';
import { process, parse_string, findNodesByType, treeHasErrorNodes, treeErrorCount, treeToSexp } from '@kreuzberg/tree-sitter-language-pack';

describe('tree-inspection', () => {
  it('split_code_python: parse_string() Python code with multiple functions finds all function_definition nodes', () => {
    const tree = parse_string("python", "def foo():\n    pass\n\ndef bar():\n    pass\n\ndef baz():\n    pass\n");
    expect(findNodesByType(tree, "function_definition").length).toBeGreaterThanOrEqual(3);
  });

  it('tree_error_count_broken: Parse broken Python code and verify error count >= 1', () => {
    const tree = parse_string("python", "def (broken syntax @@@ !!!");
    expect(treeHasErrorNodes(tree)).toBe(true);
  });

  it('tree_error_count_multiple: parse_string() with multiple syntax errors counts all error nodes', () => {
    const tree = parse_string("python", "def (\ndef (\n");
    expect(treeErrorCount(tree)).toBeGreaterThanOrEqual(2);
  });

  it('tree_error_count_valid: Parse valid Python code and verify zero error count', () => {
    const tree = parse_string("python", "x = 1\ny = 2\n");
    expect(treeErrorCount(tree)).toBe(0);
  });

  it('tree_find_nodes_no_match: Parse Python with no class definitions and verify find_nodes_by_type returns 0', () => {
    const tree = parse_string("python", "x = 1\n");
    expect(findNodesByType(tree, "class_definition")).toBe(0);
  });

  it('tree_find_nodes_two_functions: Parse Python with 2 functions and verify find_nodes_by_type count', () => {
    const tree = parse_string("python", "def foo():\n    pass\n\ndef bar():\n    pass\n");
    expect(findNodesByType(tree, "function_definition").length).toBeGreaterThanOrEqual(2);
  });

  it('tree_has_error_nodes_broken_syntax: tree_has_error_nodes returns true for syntactically broken code', () => {
    const tree = parse_string("python", "def broken(\n    x = \n");
    expect(treeHasErrorNodes(tree)).toBe(true);
  });

  it('tree_has_error_nodes_valid_code: tree_has_error_nodes returns false for valid Python code', () => {
    const tree = parse_string("python", "def greet(name):\n    return f'Hello {name}'\n");
    expect(treeHasErrorNodes(tree)).toBe(false);
  });

  it('tree_named_children_class_and_function: Parse Python with class and function, verify named children count', () => {
    const tree = parse_string("python", "class Foo:\n    pass\n\ndef bar():\n    pass\n");
    expect(tree.rootNode.namedChildCount).toBeGreaterThanOrEqual(2);
  });

  it('tree_root_node_info_javascript: Parse JavaScript source and verify root node type is program', () => {
    const tree = parse_string("javascript", "const x = 1;\n");
    expect(tree.rootNode.type).toBe("program");
  });

  it('tree_root_node_info_python: Parse Python source and verify root node info', () => {
    const tree = parse_string("python", "def hello():\n    pass\n");
    expect(tree.rootNode.type).toBe("module");
  });

  it('tree_to_sexp_python: Parse Python and verify tree_to_sexp returns valid S-expression containing module', () => {
    const tree = parse_string("python", "x = 1\n");
    expect(treeToSexp(tree)).toContain("module");
  });
});
