// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith

/** E2e tests for category: extraction. */
class ExtractionTest {
    @Test
    fun testExtractInvalidByteRange() {
        // extract_patterns() with out-of-bounds byte_range returns empty results
        val result = TreeSitterLanguagePack.extractPatterns("x = 1\n", "{\"language\":\"python\",\"patterns\":{\"funcs\":{\"byte_range\":[9999,99999],\"capture_output\":\"Full\",\"query\":\"(expression_statement) @e\"}}}")
        assertEquals(0, result.results.funcs.matches.size, "expected exactly 0 elements")
    }

    @Test
    fun testExtractPatternsNoMatches() {
        // Extraction query that matches nothing returns empty results
        val result = TreeSitterLanguagePack.extractPatterns("x = 1\ny = 2\n", "{\"language\":\"python\",\"patterns\":{\"classes\":{\"capture_output\":\"Full\",\"query\":\"(class_definition name: (identifier) @name)\"}}}")
        assertEquals(0, result.results.classes.matches.size, "expected exactly 0 elements")
    }

    @Test
    fun testExtractPatternsPythonFunctions() {
        // Extract function definitions from Python source using tree-sitter query
        val result = TreeSitterLanguagePack.extractPatterns("def hello():\n    pass\n\ndef world(x):\n    return x * 2\n", "{\"language\":\"python\",\"patterns\":{\"functions\":{\"capture_output\":\"Full\",\"query\":\"(function_definition name: (identifier) @name)\"}}}")
        assertEquals("python", result.language.trim())
        assertTrue(result.results.functions.matches.size >= 2, "expected at least 2 elements")
    }

    @Test
    fun testValidateEmptyPatterns() {
        // validate_extraction() with empty patterns returns valid
        val result = TreeSitterLanguagePack.validateExtraction("{\"language\":\"python\",\"patterns\":{}}")
        assertEquals(true, result.valid)
    }

    @Test
    fun testValidateExtractionInvalidQuery() {
        // Invalid query syntax fails validation
        assertFailsWith<Exception> { TreeSitterLanguagePack.validateExtraction("{\"language\":\"python\",\"patterns\":{\"broken\":{\"capture_output\":\"Full\",\"query\":\"(this_is_not_a_valid_node @x\"}}}") }
    }

    @Test
    fun testValidateExtractionValidConfig() {
        // Valid extraction config passes validation
        val result = TreeSitterLanguagePack.validateExtraction("{\"language\":\"python\",\"patterns\":{\"functions\":{\"capture_output\":\"Full\",\"query\":\"(function_definition name: (identifier) @name)\"}}}")
        assertEquals(true, result.valid)
    }

}
