// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bd04d835a8ac1f990205db3ae59ca9a3f2bdd0b9912b69d1f8544f7c7ef610c5
// Re-generate with: alef generate
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(
    clippy::too_many_arguments,
    clippy::let_unit_value,
    clippy::needless_borrow,
    clippy::map_identity,
    clippy::just_underscores_and_digits,
    clippy::unnecessary_cast,
    clippy::unused_unit,
    clippy::unwrap_or_default,
    clippy::derivable_impls,
    clippy::needless_borrows_for_generic_args,
    clippy::unnecessary_fallible_conversions
)]

use napi::*;
use napi_derive::napi;
use std::collections::HashMap;
use std::sync::Arc;

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsExtractionPattern {
    pub query: Option<String>,
    #[napi(js_name = "captureOutput")]
    pub capture_output: Option<JsCaptureOutput>,
    #[napi(js_name = "childFields")]
    pub child_fields: Option<Vec<String>>,
    #[napi(js_name = "maxResults")]
    pub max_results: Option<i64>,
    #[napi(js_name = "byteRange")]
    pub byte_range: Option<Vec<i64>>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsExtractionConfig {
    pub language: Option<String>,
    pub patterns: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsCaptureResult {
    pub name: Option<String>,
    pub node: Option<JsNodeInfo>,
    pub text: Option<String>,
    #[napi(js_name = "childFields")]
    pub child_fields: Option<String>,
    #[napi(js_name = "startByte")]
    pub start_byte: Option<i64>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsMatchResult {
    #[napi(js_name = "patternIndex")]
    pub pattern_index: Option<i64>,
    pub captures: Option<Vec<JsCaptureResult>>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsPatternResult {
    pub matches: Option<Vec<JsMatchResult>>,
    #[napi(js_name = "totalCount")]
    pub total_count: Option<i64>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsExtractionResult {
    pub language: Option<String>,
    pub results: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsPatternValidation {
    pub valid: Option<bool>,
    #[napi(js_name = "captureNames")]
    pub capture_names: Option<Vec<String>>,
    #[napi(js_name = "patternCount")]
    pub pattern_count: Option<i64>,
    pub warnings: Option<Vec<String>>,
    pub errors: Option<Vec<String>>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsValidationResult {
    pub valid: Option<bool>,
    pub patterns: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsSpan {
    #[napi(js_name = "startByte")]
    pub start_byte: Option<i64>,
    #[napi(js_name = "endByte")]
    pub end_byte: Option<i64>,
    #[napi(js_name = "startLine")]
    pub start_line: Option<i64>,
    #[napi(js_name = "startColumn")]
    pub start_column: Option<i64>,
    #[napi(js_name = "endLine")]
    pub end_line: Option<i64>,
    #[napi(js_name = "endColumn")]
    pub end_column: Option<i64>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsProcessResult {
    pub language: Option<String>,
    pub metrics: Option<JsFileMetrics>,
    pub structure: Option<Vec<JsStructureItem>>,
    pub imports: Option<Vec<JsImportInfo>>,
    pub exports: Option<Vec<JsExportInfo>>,
    pub comments: Option<Vec<JsCommentInfo>>,
    pub docstrings: Option<Vec<JsDocstringInfo>>,
    pub symbols: Option<Vec<JsSymbolInfo>>,
    pub diagnostics: Option<Vec<JsDiagnostic>>,
    pub chunks: Option<Vec<JsCodeChunk>>,
    pub extractions: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsFileMetrics {
    #[napi(js_name = "totalLines")]
    pub total_lines: Option<i64>,
    #[napi(js_name = "codeLines")]
    pub code_lines: Option<i64>,
    #[napi(js_name = "commentLines")]
    pub comment_lines: Option<i64>,
    #[napi(js_name = "blankLines")]
    pub blank_lines: Option<i64>,
    #[napi(js_name = "totalBytes")]
    pub total_bytes: Option<i64>,
    #[napi(js_name = "nodeCount")]
    pub node_count: Option<i64>,
    #[napi(js_name = "errorCount")]
    pub error_count: Option<i64>,
    #[napi(js_name = "maxDepth")]
    pub max_depth: Option<i64>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsStructureItem {
    pub kind: Option<JsStructureKind>,
    pub name: Option<String>,
    pub visibility: Option<String>,
    pub span: Option<JsSpan>,
    pub children: Option<Vec<JsStructureItem>>,
    pub decorators: Option<Vec<String>>,
    #[napi(js_name = "docComment")]
    pub doc_comment: Option<String>,
    pub signature: Option<String>,
    #[napi(js_name = "bodySpan")]
    pub body_span: Option<JsSpan>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsCommentInfo {
    pub text: Option<String>,
    pub kind: Option<JsCommentKind>,
    pub span: Option<JsSpan>,
    #[napi(js_name = "associatedNode")]
    pub associated_node: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsDocstringInfo {
    pub text: Option<String>,
    pub format: Option<JsDocstringFormat>,
    pub span: Option<JsSpan>,
    #[napi(js_name = "associatedItem")]
    pub associated_item: Option<String>,
    #[napi(js_name = "parsedSections")]
    pub parsed_sections: Option<Vec<JsDocSection>>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsDocSection {
    pub kind: Option<String>,
    pub name: Option<String>,
    pub description: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsImportInfo {
    pub source: Option<String>,
    pub items: Option<Vec<String>>,
    pub alias: Option<String>,
    #[napi(js_name = "isWildcard")]
    pub is_wildcard: Option<bool>,
    pub span: Option<JsSpan>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsExportInfo {
    pub name: Option<String>,
    pub kind: Option<JsExportKind>,
    pub span: Option<JsSpan>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsSymbolInfo {
    pub name: Option<String>,
    pub kind: Option<JsSymbolKind>,
    pub span: Option<JsSpan>,
    #[napi(js_name = "typeAnnotation")]
    pub type_annotation: Option<String>,
    pub doc: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsDiagnostic {
    pub message: Option<String>,
    pub severity: Option<JsDiagnosticSeverity>,
    pub span: Option<JsSpan>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsCodeChunk {
    pub content: Option<String>,
    #[napi(js_name = "startByte")]
    pub start_byte: Option<i64>,
    #[napi(js_name = "endByte")]
    pub end_byte: Option<i64>,
    #[napi(js_name = "startLine")]
    pub start_line: Option<i64>,
    #[napi(js_name = "endLine")]
    pub end_line: Option<i64>,
    pub metadata: Option<JsChunkContext>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsChunkContext {
    pub language: Option<String>,
    #[napi(js_name = "chunkIndex")]
    pub chunk_index: Option<i64>,
    #[napi(js_name = "totalChunks")]
    pub total_chunks: Option<i64>,
    #[napi(js_name = "nodeTypes")]
    pub node_types: Option<Vec<String>>,
    #[napi(js_name = "contextPath")]
    pub context_path: Option<Vec<String>>,
    #[napi(js_name = "symbolsDefined")]
    pub symbols_defined: Option<Vec<String>>,
    pub comments: Option<Vec<JsCommentInfo>>,
    pub docstrings: Option<Vec<JsDocstringInfo>>,
    #[napi(js_name = "hasErrorNodes")]
    pub has_error_nodes: Option<bool>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsNodeInfo {
    pub kind: Option<String>,
    #[napi(js_name = "isNamed")]
    pub is_named: Option<bool>,
    #[napi(js_name = "startByte")]
    pub start_byte: Option<i64>,
    #[napi(js_name = "endByte")]
    pub end_byte: Option<i64>,
    #[napi(js_name = "startRow")]
    pub start_row: Option<i64>,
    #[napi(js_name = "startCol")]
    pub start_col: Option<i64>,
    #[napi(js_name = "endRow")]
    pub end_row: Option<i64>,
    #[napi(js_name = "endCol")]
    pub end_col: Option<i64>,
    #[napi(js_name = "namedChildCount")]
    pub named_child_count: Option<i64>,
    #[napi(js_name = "isError")]
    pub is_error: Option<bool>,
    #[napi(js_name = "isMissing")]
    pub is_missing: Option<bool>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsPackConfig {
    #[napi(js_name = "cacheDir")]
    pub cache_dir: Option<String>,
    pub languages: Option<Vec<String>>,
    pub groups: Option<Vec<String>>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsProcessConfig {
    pub language: Option<String>,
    pub structure: Option<bool>,
    pub imports: Option<bool>,
    pub exports: Option<bool>,
    pub comments: Option<bool>,
    pub docstrings: Option<bool>,
    pub symbols: Option<bool>,
    pub diagnostics: Option<bool>,
    #[napi(js_name = "chunkMaxSize")]
    pub chunk_max_size: Option<i64>,
    pub extractions: Option<String>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsQueryMatch {
    #[napi(js_name = "patternIndex")]
    pub pattern_index: Option<i64>,
    pub captures: Option<Vec<String>>,
}

#[derive(Clone)]
#[napi]
pub struct JsLanguageRegistry {
    inner: Arc<tree_sitter_language_pack::LanguageRegistry>,
}

#[napi]
impl JsLanguageRegistry {
    #[napi(js_name = "addExtraLibsDir")]
    pub fn add_extra_libs_dir(&self, dir: String) -> () {
        self.inner.add_extra_libs_dir(std::path::PathBuf::from(dir))
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi(js_name = "getLanguage")]
    pub fn get_language(&self, name: String) -> Result<JsLanguage> {
        let result = self
            .inner
            .get_language(&name)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(JsLanguage {
            inner: Arc::new(result),
        })
    }

    #[napi(js_name = "availableLanguages")]
    pub fn available_languages(&self) -> Vec<String> {
        self.inner.available_languages()
    }

    #[napi(js_name = "hasLanguage")]
    pub fn has_language(&self, name: String) -> bool {
        self.inner.has_language(&name)
    }

    #[napi(js_name = "languageCount")]
    pub fn language_count(&self) -> i64 {
        self.inner.language_count() as i64
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi]
    pub fn process(&self, source: String, config: JsProcessConfig) -> Result<JsProcessResult> {
        let config_core: tree_sitter_language_pack::ProcessConfig = config.into();
        let result = self
            .inner
            .process(&source, &config_core)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(result.into())
    }

    #[napi(js_name = "withLibsDir")]
    pub fn with_libs_dir(libs_dir: String) -> JsLanguageRegistry {
        Self {
            inner: Arc::new(tree_sitter_language_pack::LanguageRegistry::with_libs_dir(
                std::path::PathBuf::from(libs_dir),
            )),
        }
    }

    #[allow(clippy::should_implement_trait)]
    #[napi]
    pub fn default() -> JsLanguageRegistry {
        Self {
            inner: Arc::new(tree_sitter_language_pack::LanguageRegistry::default()),
        }
    }
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsParserManifest {
    pub version: String,
    pub platforms: HashMap<String, JsPlatformBundle>,
    pub languages: HashMap<String, JsLanguageInfo>,
    pub groups: HashMap<String, Vec<String>>,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsPlatformBundle {
    pub url: String,
    pub sha256: String,
    pub size: i64,
}

#[derive(Clone, Default, serde::Serialize, serde::Deserialize)]
#[napi(object)]
pub struct JsLanguageInfo {
    pub group: String,
    pub size: i64,
}

#[derive(Clone)]
#[napi]
pub struct JsDownloadManager {
    inner: Arc<tree_sitter_language_pack::DownloadManager>,
}

#[napi]
impl JsDownloadManager {
    #[napi(js_name = "cacheDir")]
    pub fn cache_dir(&self) -> String {
        self.inner.cache_dir().to_string_lossy().to_string()
    }

    #[napi(js_name = "installedLanguages")]
    pub fn installed_languages(&self) -> Vec<String> {
        self.inner.installed_languages()
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi(js_name = "ensureLanguages")]
    pub fn ensure_languages(&self, names: Vec<String>) -> Result<()> {
        let names_refs: Vec<&str> = names.iter().map(|s| s.as_str()).collect();
        self.inner
            .ensure_languages(&names_refs)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(())
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi(js_name = "ensureGroup")]
    pub fn ensure_group(&self, group: String) -> Result<()> {
        self.inner
            .ensure_group(&group)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(())
    }

    #[napi(js_name = "libPath")]
    pub fn lib_path(&self, name: String) -> String {
        self.inner.lib_path(&name).to_string_lossy().to_string()
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi(js_name = "fetchManifest")]
    pub fn fetch_manifest(&self) -> Result<JsParserManifest> {
        let result = self
            .inner
            .fetch_manifest()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(result.into())
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi(js_name = "cleanCache")]
    pub fn clean_cache(&self) -> Result<()> {
        self.inner
            .clean_cache()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(())
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi]
    pub fn new(version: String) -> Result<JsDownloadManager> {
        tree_sitter_language_pack::DownloadManager::new(&version)
            .map(|val| Self { inner: Arc::new(val) })
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
    }

    #[napi(js_name = "withCacheDir")]
    pub fn with_cache_dir(version: String, cache_dir: String) -> JsDownloadManager {
        Self {
            inner: Arc::new(tree_sitter_language_pack::DownloadManager::with_cache_dir(
                &version,
                std::path::PathBuf::from(cache_dir),
            )),
        }
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi(js_name = "defaultCacheDir")]
    pub fn default_cache_dir(version: String) -> Result<String> {
        tree_sitter_language_pack::DownloadManager::default_cache_dir(&version)
            .map(|val| val.to_string_lossy().to_string())
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
    }
}

#[derive(Clone)]
#[napi]
pub struct JsLanguage {
    inner: Arc<tree_sitter_language_pack::Language>,
}

#[napi]
impl JsLanguage {}

#[derive(Clone)]
#[napi]
pub struct JsParser {
    inner: Arc<tree_sitter_language_pack::Parser>,
}

#[napi]
impl JsParser {}

#[derive(Clone)]
#[napi]
pub struct JsTree {
    inner: Arc<tree_sitter_language_pack::Tree>,
}

#[napi]
impl JsTree {}

#[napi(string_enum)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub enum JsCaptureOutput {
    Text,
    Node,
    Full,
}

#[allow(clippy::derivable_impls)]
impl Default for JsCaptureOutput {
    fn default() -> Self {
        Self::Text
    }
}

#[napi(string_enum)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub enum JsStructureKind {
    Function,
    Method,
    Class,
    Struct,
    Interface,
    Enum,
    Module,
    Trait,
    Impl,
    Namespace,
    Other,
}

#[allow(clippy::derivable_impls)]
impl Default for JsStructureKind {
    fn default() -> Self {
        Self::Function
    }
}

#[napi(string_enum)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub enum JsCommentKind {
    Line,
    Block,
    Doc,
}

#[allow(clippy::derivable_impls)]
impl Default for JsCommentKind {
    fn default() -> Self {
        Self::Line
    }
}

#[napi(string_enum)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub enum JsDocstringFormat {
    PythonTripleQuote,
    JSDoc,
    Rustdoc,
    GoDoc,
    JavaDoc,
    Other,
}

#[allow(clippy::derivable_impls)]
impl Default for JsDocstringFormat {
    fn default() -> Self {
        Self::PythonTripleQuote
    }
}

#[napi(string_enum)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub enum JsExportKind {
    Named,
    Default,
    ReExport,
}

#[allow(clippy::derivable_impls)]
impl Default for JsExportKind {
    fn default() -> Self {
        Self::Named
    }
}

#[napi(string_enum)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub enum JsSymbolKind {
    Variable,
    Constant,
    Function,
    Class,
    Type,
    Interface,
    Enum,
    Module,
    Other,
}

#[allow(clippy::derivable_impls)]
impl Default for JsSymbolKind {
    fn default() -> Self {
        Self::Variable
    }
}

#[napi(string_enum)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub enum JsDiagnosticSeverity {
    Error,
    Warning,
    Info,
}

#[allow(clippy::derivable_impls)]
impl Default for JsDiagnosticSeverity {
    fn default() -> Self {
        Self::Error
    }
}

#[napi(js_name = "detectLanguageFromExtension")]
pub fn detect_language_from_extension(ext: String) -> Option<String> {
    tree_sitter_language_pack::detect_language_from_extension(&ext).map(Into::into)
}

#[napi(js_name = "detectLanguageFromPath")]
pub fn detect_language_from_path(path: String) -> Option<String> {
    tree_sitter_language_pack::detect_language_from_path(&path).map(Into::into)
}

#[napi(js_name = "detectLanguageFromContent")]
pub fn detect_language_from_content(content: String) -> Option<String> {
    tree_sitter_language_pack::detect_language_from_content(&content).map(Into::into)
}

#[napi(js_name = "rootNodeInfo")]
pub fn root_node_info(tree: &JsTree) -> JsNodeInfo {
    tree_sitter_language_pack::root_node_info(&tree.inner).into()
}

#[napi(js_name = "findNodesByType")]
pub fn find_nodes_by_type(tree: &JsTree, node_type: String) -> Vec<JsNodeInfo> {
    tree_sitter_language_pack::find_nodes_by_type(&tree.inner, &node_type)
        .into_iter()
        .map(Into::into)
        .collect()
}

#[napi(js_name = "namedChildrenInfo")]
pub fn named_children_info(tree: &JsTree) -> Vec<JsNodeInfo> {
    tree_sitter_language_pack::named_children_info(&tree.inner)
        .into_iter()
        .map(Into::into)
        .collect()
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "parseString")]
pub fn parse_string(language: String, source: Vec<u8>) -> Result<JsTree> {
    tree_sitter_language_pack::parse_string(&language, &source)
        .map(|val| JsTree { inner: Arc::new(val) })
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[napi(js_name = "treeContainsNodeType")]
pub fn tree_contains_node_type(tree: &JsTree, node_type: String) -> bool {
    tree_sitter_language_pack::tree_contains_node_type(&tree.inner, &node_type)
}

#[napi(js_name = "treeHasErrorNodes")]
pub fn tree_has_error_nodes(tree: &JsTree) -> bool {
    tree_sitter_language_pack::tree_has_error_nodes(&tree.inner)
}

#[napi(js_name = "treeToSexp")]
pub fn tree_to_sexp(tree: &JsTree) -> String {
    tree_sitter_language_pack::tree_to_sexp(&tree.inner)
}

#[napi(js_name = "treeErrorCount")]
pub fn tree_error_count(tree: &JsTree) -> i64 {
    tree_sitter_language_pack::tree_error_count(&tree.inner) as i64
}

#[napi(js_name = "getHighlightsQuery")]
pub fn get_highlights_query(language: String) -> Option<String> {
    tree_sitter_language_pack::get_highlights_query(&language).map(Into::into)
}

#[napi(js_name = "getInjectionsQuery")]
pub fn get_injections_query(language: String) -> Option<String> {
    tree_sitter_language_pack::get_injections_query(&language).map(Into::into)
}

#[napi(js_name = "getLocalsQuery")]
pub fn get_locals_query(language: String) -> Option<String> {
    tree_sitter_language_pack::get_locals_query(&language).map(Into::into)
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "runQuery")]
pub fn run_query(tree: &JsTree, language: String, query_source: String, source: Vec<u8>) -> Result<Vec<JsQueryMatch>> {
    tree_sitter_language_pack::run_query(&tree.inner, &language, &query_source, &source)
        .map(|val| val.into_iter().map(Into::into).collect())
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "getLanguage")]
pub fn get_language(name: String) -> Result<JsLanguage> {
    tree_sitter_language_pack::get_language(&name)
        .map(|val| JsLanguage { inner: Arc::new(val) })
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "getParser")]
pub fn get_parser(name: String) -> Result<JsParser> {
    tree_sitter_language_pack::get_parser(&name)
        .map(|val| JsParser { inner: Arc::new(val) })
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[napi(js_name = "availableLanguages")]
pub fn available_languages() -> Vec<String> {
    tree_sitter_language_pack::available_languages()
}

#[napi(js_name = "hasLanguage")]
pub fn has_language(name: String) -> bool {
    tree_sitter_language_pack::has_language(&name)
}

#[napi(js_name = "languageCount")]
pub fn language_count() -> i64 {
    tree_sitter_language_pack::language_count() as i64
}

#[allow(clippy::missing_errors_doc)]
#[napi]
pub fn process(source: String, config: JsProcessConfig) -> Result<JsProcessResult> {
    let config_json =
        serde_json::to_string(&config).map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    let config_core: tree_sitter_language_pack::ProcessConfig = serde_json::from_str(&config_json)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    tree_sitter_language_pack::process(&source, &config_core)
        .map(|val| val.into())
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "extractPatterns")]
pub fn extract_patterns(source: String, config: JsExtractionConfig) -> Result<JsExtractionResult> {
    let config_json =
        serde_json::to_string(&config).map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    let config_core: tree_sitter_language_pack::ExtractionConfig = serde_json::from_str(&config_json)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    tree_sitter_language_pack::extract_patterns(&source, &config_core)
        .map(|val| val.into())
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "validateExtraction")]
pub fn validate_extraction(config: JsExtractionConfig) -> Result<JsValidationResult> {
    let config_json =
        serde_json::to_string(&config).map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    let config_core: tree_sitter_language_pack::ExtractionConfig = serde_json::from_str(&config_json)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    tree_sitter_language_pack::validate_extraction(&config_core)
        .map(|val| val.into())
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi]
pub fn init(config: JsPackConfig) -> Result<()> {
    let config_json =
        serde_json::to_string(&config).map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    let config_core: tree_sitter_language_pack::PackConfig = serde_json::from_str(&config_json)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    tree_sitter_language_pack::init(&config_core)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    Ok(())
}

#[allow(clippy::missing_errors_doc)]
#[napi]
pub fn configure(config: JsPackConfig) -> Result<()> {
    let config_json =
        serde_json::to_string(&config).map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    let config_core: tree_sitter_language_pack::PackConfig = serde_json::from_str(&config_json)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    tree_sitter_language_pack::configure(&config_core)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    Ok(())
}

#[allow(clippy::missing_errors_doc)]
#[napi]
pub fn download(names: Vec<String>) -> Result<i64> {
    let names_refs: Vec<&str> = names.iter().map(|s| s.as_str()).collect();
    tree_sitter_language_pack::download(&names_refs)
        .map(|val| val as i64)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "downloadAll")]
pub fn download_all() -> Result<i64> {
    tree_sitter_language_pack::download_all()
        .map(|val| val as i64)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "manifestLanguages")]
pub fn manifest_languages() -> Result<Vec<String>> {
    tree_sitter_language_pack::manifest_languages()
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[napi(js_name = "downloadedLanguages")]
pub fn downloaded_languages() -> Vec<String> {
    tree_sitter_language_pack::downloaded_languages()
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "cleanCache")]
pub fn clean_cache() -> Result<()> {
    tree_sitter_language_pack::clean_cache().map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

#[allow(clippy::missing_errors_doc)]
#[napi(js_name = "cacheDir")]
pub fn cache_dir() -> Result<String> {
    tree_sitter_language_pack::cache_dir()
        .map(|val| val.to_string_lossy().to_string())
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
}

impl From<tree_sitter_language_pack::ExtractionPattern> for JsExtractionPattern {
    fn from(val: tree_sitter_language_pack::ExtractionPattern) -> Self {
        Self {
            query: Some(val.query),
            capture_output: Some(val.capture_output.into()),
            child_fields: Some(val.child_fields),
            max_results: val.max_results.map(|v| v as i64),
            byte_range: val.byte_range.map(|t| {
                let arr: Vec<_> = [t.0, t.1].into_iter().map(|v| v as _).collect();
                arr
            }),
        }
    }
}

impl From<JsExtractionConfig> for tree_sitter_language_pack::ExtractionConfig {
    fn from(val: JsExtractionConfig) -> Self {
        Self {
            language: val.language.unwrap_or_default(),
            patterns: Default::default(),
        }
    }
}

impl From<tree_sitter_language_pack::ExtractionConfig> for JsExtractionConfig {
    fn from(val: tree_sitter_language_pack::ExtractionConfig) -> Self {
        Self {
            language: Some(val.language),
            patterns: Some(format!("{:?}", val.patterns)),
        }
    }
}

impl From<tree_sitter_language_pack::CaptureResult> for JsCaptureResult {
    fn from(val: tree_sitter_language_pack::CaptureResult) -> Self {
        Self {
            name: Some(val.name),
            node: val.node.map(Into::into),
            text: val.text,
            child_fields: Some(format!("{:?}", val.child_fields)),
            start_byte: Some(val.start_byte as i64),
        }
    }
}

impl From<tree_sitter_language_pack::MatchResult> for JsMatchResult {
    fn from(val: tree_sitter_language_pack::MatchResult) -> Self {
        Self {
            pattern_index: Some(val.pattern_index as i64),
            captures: Some(val.captures.into_iter().map(Into::into).collect()),
        }
    }
}

impl From<tree_sitter_language_pack::PatternResult> for JsPatternResult {
    fn from(val: tree_sitter_language_pack::PatternResult) -> Self {
        Self {
            matches: Some(val.matches.into_iter().map(Into::into).collect()),
            total_count: Some(val.total_count as i64),
        }
    }
}

impl From<JsExtractionResult> for tree_sitter_language_pack::ExtractionResult {
    fn from(val: JsExtractionResult) -> Self {
        Self {
            language: val.language.unwrap_or_default(),
            results: Default::default(),
        }
    }
}

impl From<tree_sitter_language_pack::ExtractionResult> for JsExtractionResult {
    fn from(val: tree_sitter_language_pack::ExtractionResult) -> Self {
        Self {
            language: Some(val.language),
            results: Some(format!("{:?}", val.results)),
        }
    }
}

impl From<tree_sitter_language_pack::PatternValidation> for JsPatternValidation {
    fn from(val: tree_sitter_language_pack::PatternValidation) -> Self {
        Self {
            valid: Some(val.valid),
            capture_names: Some(val.capture_names),
            pattern_count: Some(val.pattern_count as i64),
            warnings: Some(val.warnings),
            errors: Some(val.errors),
        }
    }
}

impl From<JsValidationResult> for tree_sitter_language_pack::ValidationResult {
    fn from(val: JsValidationResult) -> Self {
        Self {
            valid: val.valid.unwrap_or_default(),
            patterns: Default::default(),
        }
    }
}

impl From<tree_sitter_language_pack::ValidationResult> for JsValidationResult {
    fn from(val: tree_sitter_language_pack::ValidationResult) -> Self {
        Self {
            valid: Some(val.valid),
            patterns: Some(format!("{:?}", val.patterns)),
        }
    }
}

impl From<JsSpan> for tree_sitter_language_pack::Span {
    fn from(val: JsSpan) -> Self {
        Self {
            start_byte: val.start_byte.map(|v| v as usize).unwrap_or_default(),
            end_byte: val.end_byte.map(|v| v as usize).unwrap_or_default(),
            start_line: val.start_line.map(|v| v as usize).unwrap_or_default(),
            start_column: val.start_column.map(|v| v as usize).unwrap_or_default(),
            end_line: val.end_line.map(|v| v as usize).unwrap_or_default(),
            end_column: val.end_column.map(|v| v as usize).unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::Span> for JsSpan {
    fn from(val: tree_sitter_language_pack::Span) -> Self {
        Self {
            start_byte: Some(val.start_byte as i64),
            end_byte: Some(val.end_byte as i64),
            start_line: Some(val.start_line as i64),
            start_column: Some(val.start_column as i64),
            end_line: Some(val.end_line as i64),
            end_column: Some(val.end_column as i64),
        }
    }
}

impl From<JsProcessResult> for tree_sitter_language_pack::ProcessResult {
    fn from(val: JsProcessResult) -> Self {
        Self {
            language: val.language.unwrap_or_default(),
            metrics: val.metrics.map(Into::into).unwrap_or_default(),
            structure: val
                .structure
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            imports: val
                .imports
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            exports: val
                .exports
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            comments: val
                .comments
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            docstrings: val
                .docstrings
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            symbols: val
                .symbols
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            diagnostics: val
                .diagnostics
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            chunks: val
                .chunks
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            extractions: Default::default(),
        }
    }
}

impl From<tree_sitter_language_pack::ProcessResult> for JsProcessResult {
    fn from(val: tree_sitter_language_pack::ProcessResult) -> Self {
        Self {
            language: Some(val.language),
            metrics: Some(val.metrics.into()),
            structure: Some(val.structure.into_iter().map(Into::into).collect()),
            imports: Some(val.imports.into_iter().map(Into::into).collect()),
            exports: Some(val.exports.into_iter().map(Into::into).collect()),
            comments: Some(val.comments.into_iter().map(Into::into).collect()),
            docstrings: Some(val.docstrings.into_iter().map(Into::into).collect()),
            symbols: Some(val.symbols.into_iter().map(Into::into).collect()),
            diagnostics: Some(val.diagnostics.into_iter().map(Into::into).collect()),
            chunks: Some(val.chunks.into_iter().map(Into::into).collect()),
            extractions: Some(format!("{:?}", val.extractions)),
        }
    }
}

impl From<JsFileMetrics> for tree_sitter_language_pack::FileMetrics {
    fn from(val: JsFileMetrics) -> Self {
        Self {
            total_lines: val.total_lines.map(|v| v as usize).unwrap_or_default(),
            code_lines: val.code_lines.map(|v| v as usize).unwrap_or_default(),
            comment_lines: val.comment_lines.map(|v| v as usize).unwrap_or_default(),
            blank_lines: val.blank_lines.map(|v| v as usize).unwrap_or_default(),
            total_bytes: val.total_bytes.map(|v| v as usize).unwrap_or_default(),
            node_count: val.node_count.map(|v| v as usize).unwrap_or_default(),
            error_count: val.error_count.map(|v| v as usize).unwrap_or_default(),
            max_depth: val.max_depth.map(|v| v as usize).unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::FileMetrics> for JsFileMetrics {
    fn from(val: tree_sitter_language_pack::FileMetrics) -> Self {
        Self {
            total_lines: Some(val.total_lines as i64),
            code_lines: Some(val.code_lines as i64),
            comment_lines: Some(val.comment_lines as i64),
            blank_lines: Some(val.blank_lines as i64),
            total_bytes: Some(val.total_bytes as i64),
            node_count: Some(val.node_count as i64),
            error_count: Some(val.error_count as i64),
            max_depth: Some(val.max_depth as i64),
        }
    }
}

impl From<JsStructureItem> for tree_sitter_language_pack::StructureItem {
    fn from(val: JsStructureItem) -> Self {
        Self {
            kind: val.kind.map(Into::into).unwrap_or_default(),
            name: val.name,
            visibility: val.visibility,
            span: val.span.map(Into::into).unwrap_or_default(),
            children: val
                .children
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            decorators: val.decorators.unwrap_or_default(),
            doc_comment: val.doc_comment,
            signature: val.signature,
            body_span: val.body_span.map(Into::into),
        }
    }
}

impl From<tree_sitter_language_pack::StructureItem> for JsStructureItem {
    fn from(val: tree_sitter_language_pack::StructureItem) -> Self {
        Self {
            kind: Some(val.kind.into()),
            name: val.name,
            visibility: val.visibility,
            span: Some(val.span.into()),
            children: Some(val.children.into_iter().map(Into::into).collect()),
            decorators: Some(val.decorators),
            doc_comment: val.doc_comment,
            signature: val.signature,
            body_span: val.body_span.map(Into::into),
        }
    }
}

impl From<JsCommentInfo> for tree_sitter_language_pack::CommentInfo {
    fn from(val: JsCommentInfo) -> Self {
        Self {
            text: val.text.unwrap_or_default(),
            kind: val.kind.map(Into::into).unwrap_or_default(),
            span: val.span.map(Into::into).unwrap_or_default(),
            associated_node: val.associated_node,
        }
    }
}

impl From<tree_sitter_language_pack::CommentInfo> for JsCommentInfo {
    fn from(val: tree_sitter_language_pack::CommentInfo) -> Self {
        Self {
            text: Some(val.text),
            kind: Some(val.kind.into()),
            span: Some(val.span.into()),
            associated_node: val.associated_node,
        }
    }
}

impl From<JsDocstringInfo> for tree_sitter_language_pack::DocstringInfo {
    fn from(val: JsDocstringInfo) -> Self {
        Self {
            text: val.text.unwrap_or_default(),
            format: val.format.map(Into::into).unwrap_or_default(),
            span: val.span.map(Into::into).unwrap_or_default(),
            associated_item: val.associated_item,
            parsed_sections: val
                .parsed_sections
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::DocstringInfo> for JsDocstringInfo {
    fn from(val: tree_sitter_language_pack::DocstringInfo) -> Self {
        Self {
            text: Some(val.text),
            format: Some(val.format.into()),
            span: Some(val.span.into()),
            associated_item: val.associated_item,
            parsed_sections: Some(val.parsed_sections.into_iter().map(Into::into).collect()),
        }
    }
}

impl From<JsDocSection> for tree_sitter_language_pack::DocSection {
    fn from(val: JsDocSection) -> Self {
        Self {
            kind: val.kind.unwrap_or_default(),
            name: val.name,
            description: val.description.unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::DocSection> for JsDocSection {
    fn from(val: tree_sitter_language_pack::DocSection) -> Self {
        Self {
            kind: Some(val.kind),
            name: val.name,
            description: Some(val.description),
        }
    }
}

impl From<JsImportInfo> for tree_sitter_language_pack::ImportInfo {
    fn from(val: JsImportInfo) -> Self {
        Self {
            source: val.source.unwrap_or_default(),
            items: val.items.unwrap_or_default(),
            alias: val.alias,
            is_wildcard: val.is_wildcard.unwrap_or_default(),
            span: val.span.map(Into::into).unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::ImportInfo> for JsImportInfo {
    fn from(val: tree_sitter_language_pack::ImportInfo) -> Self {
        Self {
            source: Some(val.source),
            items: Some(val.items),
            alias: val.alias,
            is_wildcard: Some(val.is_wildcard),
            span: Some(val.span.into()),
        }
    }
}

impl From<JsExportInfo> for tree_sitter_language_pack::ExportInfo {
    fn from(val: JsExportInfo) -> Self {
        Self {
            name: val.name.unwrap_or_default(),
            kind: val.kind.map(Into::into).unwrap_or_default(),
            span: val.span.map(Into::into).unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::ExportInfo> for JsExportInfo {
    fn from(val: tree_sitter_language_pack::ExportInfo) -> Self {
        Self {
            name: Some(val.name),
            kind: Some(val.kind.into()),
            span: Some(val.span.into()),
        }
    }
}

impl From<JsSymbolInfo> for tree_sitter_language_pack::SymbolInfo {
    fn from(val: JsSymbolInfo) -> Self {
        Self {
            name: val.name.unwrap_or_default(),
            kind: val.kind.map(Into::into).unwrap_or_default(),
            span: val.span.map(Into::into).unwrap_or_default(),
            type_annotation: val.type_annotation,
            doc: val.doc,
        }
    }
}

impl From<tree_sitter_language_pack::SymbolInfo> for JsSymbolInfo {
    fn from(val: tree_sitter_language_pack::SymbolInfo) -> Self {
        Self {
            name: Some(val.name),
            kind: Some(val.kind.into()),
            span: Some(val.span.into()),
            type_annotation: val.type_annotation,
            doc: val.doc,
        }
    }
}

impl From<JsDiagnostic> for tree_sitter_language_pack::Diagnostic {
    fn from(val: JsDiagnostic) -> Self {
        Self {
            message: val.message.unwrap_or_default(),
            severity: val.severity.map(Into::into).unwrap_or_default(),
            span: val.span.map(Into::into).unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::Diagnostic> for JsDiagnostic {
    fn from(val: tree_sitter_language_pack::Diagnostic) -> Self {
        Self {
            message: Some(val.message),
            severity: Some(val.severity.into()),
            span: Some(val.span.into()),
        }
    }
}

impl From<JsCodeChunk> for tree_sitter_language_pack::CodeChunk {
    fn from(val: JsCodeChunk) -> Self {
        Self {
            content: val.content.unwrap_or_default(),
            start_byte: val.start_byte.map(|v| v as usize).unwrap_or_default(),
            end_byte: val.end_byte.map(|v| v as usize).unwrap_or_default(),
            start_line: val.start_line.map(|v| v as usize).unwrap_or_default(),
            end_line: val.end_line.map(|v| v as usize).unwrap_or_default(),
            metadata: val.metadata.map(Into::into).unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::CodeChunk> for JsCodeChunk {
    fn from(val: tree_sitter_language_pack::CodeChunk) -> Self {
        Self {
            content: Some(val.content),
            start_byte: Some(val.start_byte as i64),
            end_byte: Some(val.end_byte as i64),
            start_line: Some(val.start_line as i64),
            end_line: Some(val.end_line as i64),
            metadata: Some(val.metadata.into()),
        }
    }
}

impl From<JsChunkContext> for tree_sitter_language_pack::ChunkContext {
    fn from(val: JsChunkContext) -> Self {
        Self {
            language: val.language.unwrap_or_default(),
            chunk_index: val.chunk_index.map(|v| v as usize).unwrap_or_default(),
            total_chunks: val.total_chunks.map(|v| v as usize).unwrap_or_default(),
            node_types: val.node_types.unwrap_or_default(),
            context_path: val.context_path.unwrap_or_default(),
            symbols_defined: val.symbols_defined.unwrap_or_default(),
            comments: val
                .comments
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            docstrings: val
                .docstrings
                .map(|v| v.into_iter().map(Into::into).collect())
                .unwrap_or_default(),
            has_error_nodes: val.has_error_nodes.unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::ChunkContext> for JsChunkContext {
    fn from(val: tree_sitter_language_pack::ChunkContext) -> Self {
        Self {
            language: Some(val.language),
            chunk_index: Some(val.chunk_index as i64),
            total_chunks: Some(val.total_chunks as i64),
            node_types: Some(val.node_types),
            context_path: Some(val.context_path),
            symbols_defined: Some(val.symbols_defined),
            comments: Some(val.comments.into_iter().map(Into::into).collect()),
            docstrings: Some(val.docstrings.into_iter().map(Into::into).collect()),
            has_error_nodes: Some(val.has_error_nodes),
        }
    }
}

impl From<JsNodeInfo> for tree_sitter_language_pack::NodeInfo {
    fn from(val: JsNodeInfo) -> Self {
        Self {
            kind: Default::default(),
            is_named: val.is_named.unwrap_or_default(),
            start_byte: val.start_byte.map(|v| v as usize).unwrap_or_default(),
            end_byte: val.end_byte.map(|v| v as usize).unwrap_or_default(),
            start_row: val.start_row.map(|v| v as usize).unwrap_or_default(),
            start_col: val.start_col.map(|v| v as usize).unwrap_or_default(),
            end_row: val.end_row.map(|v| v as usize).unwrap_or_default(),
            end_col: val.end_col.map(|v| v as usize).unwrap_or_default(),
            named_child_count: val.named_child_count.map(|v| v as usize).unwrap_or_default(),
            is_error: val.is_error.unwrap_or_default(),
            is_missing: val.is_missing.unwrap_or_default(),
        }
    }
}

impl From<tree_sitter_language_pack::NodeInfo> for JsNodeInfo {
    fn from(val: tree_sitter_language_pack::NodeInfo) -> Self {
        Self {
            kind: Some(format!("{:?}", val.kind)),
            is_named: Some(val.is_named),
            start_byte: Some(val.start_byte as i64),
            end_byte: Some(val.end_byte as i64),
            start_row: Some(val.start_row as i64),
            start_col: Some(val.start_col as i64),
            end_row: Some(val.end_row as i64),
            end_col: Some(val.end_col as i64),
            named_child_count: Some(val.named_child_count as i64),
            is_error: Some(val.is_error),
            is_missing: Some(val.is_missing),
        }
    }
}

impl From<JsPackConfig> for tree_sitter_language_pack::PackConfig {
    fn from(val: JsPackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir.map(Into::into),
            languages: val.languages,
            groups: val.groups,
        }
    }
}

impl From<tree_sitter_language_pack::PackConfig> for JsPackConfig {
    fn from(val: tree_sitter_language_pack::PackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir.map(|p| p.to_string_lossy().to_string()),
            languages: val.languages,
            groups: val.groups,
        }
    }
}

impl From<JsProcessConfig> for tree_sitter_language_pack::ProcessConfig {
    fn from(val: JsProcessConfig) -> Self {
        Self {
            language: Default::default(),
            structure: val.structure.unwrap_or_default(),
            imports: val.imports.unwrap_or_default(),
            exports: val.exports.unwrap_or_default(),
            comments: val.comments.unwrap_or_default(),
            docstrings: val.docstrings.unwrap_or_default(),
            symbols: val.symbols.unwrap_or_default(),
            diagnostics: val.diagnostics.unwrap_or_default(),
            chunk_max_size: val.chunk_max_size.map(|v| v as usize),
            extractions: Default::default(),
        }
    }
}

impl From<tree_sitter_language_pack::ProcessConfig> for JsProcessConfig {
    fn from(val: tree_sitter_language_pack::ProcessConfig) -> Self {
        Self {
            language: Some(format!("{:?}", val.language)),
            structure: Some(val.structure),
            imports: Some(val.imports),
            exports: Some(val.exports),
            comments: Some(val.comments),
            docstrings: Some(val.docstrings),
            symbols: Some(val.symbols),
            diagnostics: Some(val.diagnostics),
            chunk_max_size: val.chunk_max_size.map(|v| v as i64),
            extractions: val.extractions.as_ref().map(|v| format!("{v:?}")),
        }
    }
}

impl From<JsQueryMatch> for tree_sitter_language_pack::QueryMatch {
    fn from(val: JsQueryMatch) -> Self {
        Self {
            pattern_index: val.pattern_index.map(|v| v as usize).unwrap_or_default(),
            captures: Default::default(),
        }
    }
}

impl From<tree_sitter_language_pack::QueryMatch> for JsQueryMatch {
    fn from(val: tree_sitter_language_pack::QueryMatch) -> Self {
        Self {
            pattern_index: Some(val.pattern_index as i64),
            captures: Some(val.captures.iter().map(|i| format!("{:?}", i)).collect()),
        }
    }
}

impl From<JsParserManifest> for tree_sitter_language_pack::download::ParserManifest {
    fn from(val: JsParserManifest) -> Self {
        Self {
            version: val.version,
            platforms: val.platforms.into_iter().map(|(k, v)| (k, v.into())).collect(),
            languages: val.languages.into_iter().map(|(k, v)| (k, v.into())).collect(),
            groups: val.groups.into_iter().collect(),
        }
    }
}

impl From<tree_sitter_language_pack::download::ParserManifest> for JsParserManifest {
    fn from(val: tree_sitter_language_pack::download::ParserManifest) -> Self {
        Self {
            version: val.version,
            platforms: val.platforms.into_iter().map(|(k, v)| (k, v.into())).collect(),
            languages: val.languages.into_iter().map(|(k, v)| (k, v.into())).collect(),
            groups: val.groups.into_iter().collect(),
        }
    }
}

impl From<JsPlatformBundle> for tree_sitter_language_pack::download::PlatformBundle {
    fn from(val: JsPlatformBundle) -> Self {
        Self {
            url: val.url,
            sha256: val.sha256,
            size: val.size as u64,
        }
    }
}

impl From<tree_sitter_language_pack::download::PlatformBundle> for JsPlatformBundle {
    fn from(val: tree_sitter_language_pack::download::PlatformBundle) -> Self {
        Self {
            url: val.url,
            sha256: val.sha256,
            size: val.size as i64,
        }
    }
}

impl From<JsLanguageInfo> for tree_sitter_language_pack::download::LanguageInfo {
    fn from(val: JsLanguageInfo) -> Self {
        Self {
            group: val.group,
            size: val.size as u64,
        }
    }
}

impl From<tree_sitter_language_pack::download::LanguageInfo> for JsLanguageInfo {
    fn from(val: tree_sitter_language_pack::download::LanguageInfo) -> Self {
        Self {
            group: val.group,
            size: val.size as i64,
        }
    }
}

impl From<tree_sitter_language_pack::CaptureOutput> for JsCaptureOutput {
    fn from(val: tree_sitter_language_pack::CaptureOutput) -> Self {
        match val {
            tree_sitter_language_pack::CaptureOutput::Text => Self::Text,
            tree_sitter_language_pack::CaptureOutput::Node => Self::Node,
            tree_sitter_language_pack::CaptureOutput::Full => Self::Full,
        }
    }
}

impl From<JsStructureKind> for tree_sitter_language_pack::StructureKind {
    fn from(val: JsStructureKind) -> Self {
        match val {
            JsStructureKind::Function => Self::Function,
            JsStructureKind::Method => Self::Method,
            JsStructureKind::Class => Self::Class,
            JsStructureKind::Struct => Self::Struct,
            JsStructureKind::Interface => Self::Interface,
            JsStructureKind::Enum => Self::Enum,
            JsStructureKind::Module => Self::Module,
            JsStructureKind::Trait => Self::Trait,
            JsStructureKind::Impl => Self::Impl,
            JsStructureKind::Namespace => Self::Namespace,
            JsStructureKind::Other => Self::Other(Default::default()),
        }
    }
}

impl From<tree_sitter_language_pack::StructureKind> for JsStructureKind {
    fn from(val: tree_sitter_language_pack::StructureKind) -> Self {
        match val {
            tree_sitter_language_pack::StructureKind::Function => Self::Function,
            tree_sitter_language_pack::StructureKind::Method => Self::Method,
            tree_sitter_language_pack::StructureKind::Class => Self::Class,
            tree_sitter_language_pack::StructureKind::Struct => Self::Struct,
            tree_sitter_language_pack::StructureKind::Interface => Self::Interface,
            tree_sitter_language_pack::StructureKind::Enum => Self::Enum,
            tree_sitter_language_pack::StructureKind::Module => Self::Module,
            tree_sitter_language_pack::StructureKind::Trait => Self::Trait,
            tree_sitter_language_pack::StructureKind::Impl => Self::Impl,
            tree_sitter_language_pack::StructureKind::Namespace => Self::Namespace,
            tree_sitter_language_pack::StructureKind::Other(..) => Self::Other,
        }
    }
}

impl From<JsCommentKind> for tree_sitter_language_pack::CommentKind {
    fn from(val: JsCommentKind) -> Self {
        match val {
            JsCommentKind::Line => Self::Line,
            JsCommentKind::Block => Self::Block,
            JsCommentKind::Doc => Self::Doc,
        }
    }
}

impl From<tree_sitter_language_pack::CommentKind> for JsCommentKind {
    fn from(val: tree_sitter_language_pack::CommentKind) -> Self {
        match val {
            tree_sitter_language_pack::CommentKind::Line => Self::Line,
            tree_sitter_language_pack::CommentKind::Block => Self::Block,
            tree_sitter_language_pack::CommentKind::Doc => Self::Doc,
        }
    }
}

impl From<JsDocstringFormat> for tree_sitter_language_pack::DocstringFormat {
    fn from(val: JsDocstringFormat) -> Self {
        match val {
            JsDocstringFormat::PythonTripleQuote => Self::PythonTripleQuote,
            JsDocstringFormat::JSDoc => Self::JSDoc,
            JsDocstringFormat::Rustdoc => Self::Rustdoc,
            JsDocstringFormat::GoDoc => Self::GoDoc,
            JsDocstringFormat::JavaDoc => Self::JavaDoc,
            JsDocstringFormat::Other => Self::Other(Default::default()),
        }
    }
}

impl From<tree_sitter_language_pack::DocstringFormat> for JsDocstringFormat {
    fn from(val: tree_sitter_language_pack::DocstringFormat) -> Self {
        match val {
            tree_sitter_language_pack::DocstringFormat::PythonTripleQuote => Self::PythonTripleQuote,
            tree_sitter_language_pack::DocstringFormat::JSDoc => Self::JSDoc,
            tree_sitter_language_pack::DocstringFormat::Rustdoc => Self::Rustdoc,
            tree_sitter_language_pack::DocstringFormat::GoDoc => Self::GoDoc,
            tree_sitter_language_pack::DocstringFormat::JavaDoc => Self::JavaDoc,
            tree_sitter_language_pack::DocstringFormat::Other(..) => Self::Other,
        }
    }
}

impl From<JsExportKind> for tree_sitter_language_pack::ExportKind {
    fn from(val: JsExportKind) -> Self {
        match val {
            JsExportKind::Named => Self::Named,
            JsExportKind::Default => Self::Default,
            JsExportKind::ReExport => Self::ReExport,
        }
    }
}

impl From<tree_sitter_language_pack::ExportKind> for JsExportKind {
    fn from(val: tree_sitter_language_pack::ExportKind) -> Self {
        match val {
            tree_sitter_language_pack::ExportKind::Named => Self::Named,
            tree_sitter_language_pack::ExportKind::Default => Self::Default,
            tree_sitter_language_pack::ExportKind::ReExport => Self::ReExport,
        }
    }
}

impl From<JsSymbolKind> for tree_sitter_language_pack::SymbolKind {
    fn from(val: JsSymbolKind) -> Self {
        match val {
            JsSymbolKind::Variable => Self::Variable,
            JsSymbolKind::Constant => Self::Constant,
            JsSymbolKind::Function => Self::Function,
            JsSymbolKind::Class => Self::Class,
            JsSymbolKind::Type => Self::Type,
            JsSymbolKind::Interface => Self::Interface,
            JsSymbolKind::Enum => Self::Enum,
            JsSymbolKind::Module => Self::Module,
            JsSymbolKind::Other => Self::Other(Default::default()),
        }
    }
}

impl From<tree_sitter_language_pack::SymbolKind> for JsSymbolKind {
    fn from(val: tree_sitter_language_pack::SymbolKind) -> Self {
        match val {
            tree_sitter_language_pack::SymbolKind::Variable => Self::Variable,
            tree_sitter_language_pack::SymbolKind::Constant => Self::Constant,
            tree_sitter_language_pack::SymbolKind::Function => Self::Function,
            tree_sitter_language_pack::SymbolKind::Class => Self::Class,
            tree_sitter_language_pack::SymbolKind::Type => Self::Type,
            tree_sitter_language_pack::SymbolKind::Interface => Self::Interface,
            tree_sitter_language_pack::SymbolKind::Enum => Self::Enum,
            tree_sitter_language_pack::SymbolKind::Module => Self::Module,
            tree_sitter_language_pack::SymbolKind::Other(..) => Self::Other,
        }
    }
}

impl From<JsDiagnosticSeverity> for tree_sitter_language_pack::DiagnosticSeverity {
    fn from(val: JsDiagnosticSeverity) -> Self {
        match val {
            JsDiagnosticSeverity::Error => Self::Error,
            JsDiagnosticSeverity::Warning => Self::Warning,
            JsDiagnosticSeverity::Info => Self::Info,
        }
    }
}

impl From<tree_sitter_language_pack::DiagnosticSeverity> for JsDiagnosticSeverity {
    fn from(val: tree_sitter_language_pack::DiagnosticSeverity) -> Self {
        match val {
            tree_sitter_language_pack::DiagnosticSeverity::Error => Self::Error,
            tree_sitter_language_pack::DiagnosticSeverity::Warning => Self::Warning,
            tree_sitter_language_pack::DiagnosticSeverity::Info => Self::Info,
        }
    }
}

// Error variant name constants
pub const ERROR_ERROR_LANGUAGE_NOT_FOUND: &str = "LanguageNotFound";
pub const ERROR_ERROR_DYNAMIC_LOAD: &str = "DynamicLoad";
pub const ERROR_ERROR_NULL_LANGUAGE_POINTER: &str = "NullLanguagePointer";
pub const ERROR_ERROR_PARSER_SETUP: &str = "ParserSetup";
pub const ERROR_ERROR_LOCK_POISONED: &str = "LockPoisoned";
pub const ERROR_ERROR_CONFIG: &str = "Config";
pub const ERROR_ERROR_PARSE_FAILED: &str = "ParseFailed";
pub const ERROR_ERROR_QUERY_ERROR: &str = "QueryError";
pub const ERROR_ERROR_INVALID_RANGE: &str = "InvalidRange";
pub const ERROR_ERROR_IO: &str = "Io";

/// Convert a `tree_sitter_language_pack::error::Error` error to a NAPI error.
#[allow(dead_code)]
fn error_to_napi_err(e: tree_sitter_language_pack::error::Error) -> napi::Error {
    let msg = e.to_string();
    #[allow(unreachable_patterns)]
    match &e {
        tree_sitter_language_pack::error::Error::LanguageNotFound(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[LanguageNotFound] {}", msg))
        }
        tree_sitter_language_pack::error::Error::DynamicLoad(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[DynamicLoad] {}", msg))
        }
        tree_sitter_language_pack::error::Error::NullLanguagePointer(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[NullLanguagePointer] {}", msg))
        }
        tree_sitter_language_pack::error::Error::ParserSetup(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[ParserSetup] {}", msg))
        }
        tree_sitter_language_pack::error::Error::LockPoisoned(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[LockPoisoned] {}", msg))
        }
        tree_sitter_language_pack::error::Error::Config(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[Config] {}", msg))
        }
        tree_sitter_language_pack::error::Error::ParseFailed => {
            napi::Error::new(napi::Status::GenericFailure, format!("[ParseFailed] {}", msg))
        }
        tree_sitter_language_pack::error::Error::QueryError(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[QueryError] {}", msg))
        }
        tree_sitter_language_pack::error::Error::InvalidRange(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[InvalidRange] {}", msg))
        }
        tree_sitter_language_pack::error::Error::Io(..) => {
            napi::Error::new(napi::Status::GenericFailure, format!("[Io] {}", msg))
        }
        _ => napi::Error::new(napi::Status::GenericFailure, msg),
    }
}
