// This file is auto-generated by skif. DO NOT EDIT.
// Re-generate with: skif generate
#![allow(clippy::too_many_arguments)]
#![allow(clippy::missing_errors_doc)]

use rustler::prelude::*;
use std::collections::HashMap;
use ts_pack_core;
use std::sync::Arc;

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ExtractionPattern {
    pub query: String,
    pub capture_output: CaptureOutput,
    pub child_fields: Vec<String>,
    pub max_results: Option<usize>,
    pub byte_range: Option<String>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ExtractionConfig {
    pub language: String,
    pub patterns: String,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct CaptureResult {
    pub name: String,
    pub node: Option<NodeInfo>,
    pub text: Option<String>,
    pub child_fields: String,
    pub start_byte: usize,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct MatchResult {
    pub pattern_index: usize,
    pub captures: Vec<CaptureResult>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct PatternResult {
    pub matches: Vec<MatchResult>,
    pub total_count: usize,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ExtractionResult {
    pub language: String,
    pub results: String,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct PatternValidation {
    pub valid: bool,
    pub capture_names: Vec<String>,
    pub pattern_count: usize,
    pub warnings: Vec<String>,
    pub errors: Vec<String>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ValidationResult {
    pub valid: bool,
    pub patterns: String,
}

#[derive(Clone)]
pub struct CompiledExtraction {
    inner: std::sync::Arc<ts_pack_core::CompiledExtraction>,
}

impl rustler::Resource for CompiledExtraction {}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct Span {
    pub start_byte: usize,
    pub end_byte: usize,
    pub start_line: usize,
    pub start_column: usize,
    pub end_line: usize,
    pub end_column: usize,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ProcessResult {
    pub language: String,
    pub metrics: FileMetrics,
    pub structure: Vec<StructureItem>,
    pub imports: Vec<ImportInfo>,
    pub exports: Vec<ExportInfo>,
    pub comments: Vec<CommentInfo>,
    pub docstrings: Vec<DocstringInfo>,
    pub symbols: Vec<SymbolInfo>,
    pub diagnostics: Vec<Diagnostic>,
    pub chunks: Vec<CodeChunk>,
    pub extractions: String,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct FileMetrics {
    pub total_lines: usize,
    pub code_lines: usize,
    pub comment_lines: usize,
    pub blank_lines: usize,
    pub total_bytes: usize,
    pub node_count: usize,
    pub error_count: usize,
    pub max_depth: usize,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct StructureItem {
    pub kind: StructureKind,
    pub name: Option<String>,
    pub visibility: Option<String>,
    pub span: Span,
    pub children: Vec<StructureItem>,
    pub decorators: Vec<String>,
    pub doc_comment: Option<String>,
    pub signature: Option<String>,
    pub body_span: Option<Span>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct CommentInfo {
    pub text: String,
    pub kind: CommentKind,
    pub span: Span,
    pub associated_node: Option<String>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct DocstringInfo {
    pub text: String,
    pub format: DocstringFormat,
    pub span: Span,
    pub associated_item: Option<String>,
    pub parsed_sections: Vec<DocSection>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct DocSection {
    pub kind: String,
    pub name: Option<String>,
    pub description: String,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ImportInfo {
    pub source: String,
    pub items: Vec<String>,
    pub alias: Option<String>,
    pub is_wildcard: bool,
    pub span: Span,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ExportInfo {
    pub name: String,
    pub kind: ExportKind,
    pub span: Span,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct SymbolInfo {
    pub name: String,
    pub kind: SymbolKind,
    pub span: Span,
    pub type_annotation: Option<String>,
    pub doc: Option<String>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct Diagnostic {
    pub message: String,
    pub severity: DiagnosticSeverity,
    pub span: Span,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct CodeChunk {
    pub content: String,
    pub start_byte: usize,
    pub end_byte: usize,
    pub start_line: usize,
    pub end_line: usize,
    pub metadata: ChunkContext,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ChunkContext {
    pub language: String,
    pub chunk_index: usize,
    pub total_chunks: usize,
    pub node_types: Vec<String>,
    pub context_path: Vec<String>,
    pub symbols_defined: Vec<String>,
    pub comments: Vec<CommentInfo>,
    pub docstrings: Vec<DocstringInfo>,
    pub has_error_nodes: bool,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct NodeInfo {
    pub kind: String,
    pub is_named: bool,
    pub start_byte: usize,
    pub end_byte: usize,
    pub start_row: usize,
    pub start_col: usize,
    pub end_row: usize,
    pub end_col: usize,
    pub named_child_count: usize,
    pub is_error: bool,
    pub is_missing: bool,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct PackConfig {
    pub cache_dir: Option<String>,
    pub languages: Option<Vec<String>>,
    pub groups: Option<Vec<String>>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ProcessConfig {
    pub language: String,
    pub structure: bool,
    pub imports: bool,
    pub exports: bool,
    pub comments: bool,
    pub docstrings: bool,
    pub symbols: bool,
    pub diagnostics: bool,
    pub chunk_max_size: Option<usize>,
    pub extractions: Option<String>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct QueryMatch {
    pub pattern_index: usize,
    pub captures: Vec<String>,
}

#[derive(Clone)]
pub struct LanguageRegistry {
    inner: std::sync::Arc<ts_pack_core::LanguageRegistry>,
}

impl rustler::Resource for LanguageRegistry {}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct Config {
    pub language_pack: LanguagePackConfig,
    pub languages: LanguagesConfig,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct LanguagePackConfig {
    pub cache_dir: Option<String>,
    pub definitions: Option<String>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct LanguagesConfig {
    pub include: Vec<String>,
    pub exclude: Vec<String>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct LanguageDefinition {
    pub repo: String,
    pub rev: Option<String>,
    pub branch: Option<String>,
    pub directory: Option<String>,
    pub generate: Option<bool>,
    pub abi_version: Option<u32>,
    pub extensions: Vec<String>,
    pub c_symbol: Option<String>,
    pub ambiguous: std::collections::HashMap<String, Vec<String>>,
}

#[derive(Clone)]
pub struct LanguageDefinitions {
    inner: std::sync::Arc<ts_pack_core::LanguageDefinitions>,
}

impl rustler::Resource for LanguageDefinitions {}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct ParserManifest {
    pub version: String,
    pub platforms: std::collections::HashMap<String, PlatformBundle>,
    pub languages: std::collections::HashMap<String, LanguageInfo>,
    pub groups: std::collections::HashMap<String, Vec<String>>,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct PlatformBundle {
    pub url: String,
    pub sha256: String,
    pub size: u64,
}

#[derive(Clone, Debug)]
#[rustler::NifStruct(module = "TreeSitterLanguagePack")]
pub struct LanguageInfo {
    pub group: String,
    pub size: u64,
}

#[derive(Clone)]
pub struct DownloadManager {
    inner: std::sync::Arc<ts_pack_core::DownloadManager>,
}

impl rustler::Resource for DownloadManager {}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum Error {
    LanguageNotFound,
    DynamicLoad,
    NullLanguagePointer,
    ParserSetup,
    LockPoisoned,
    Config,
    ParseFailed,
    QueryError,
    InvalidRange,
    Io,
    Json,
    Toml,
    Download,
    ChecksumMismatch,
}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum CaptureOutput {
    Text,
    Node,
    Full,
}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum StructureKind {
    Function,
    Method,
    Class,
    Struct,
    Interface,
    Enum,
    Module,
    Trait,
    Impl,
    Namespace,
    Other,
}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum CommentKind {
    Line,
    Block,
    Doc,
}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum DocstringFormat {
    PythonTripleQuote,
    JSDoc,
    Rustdoc,
    GoDoc,
    JavaDoc,
    Other,
}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum ExportKind {
    Named,
    Default,
    ReExport,
}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum SymbolKind {
    Variable,
    Constant,
    Function,
    Class,
    Type,
    Interface,
    Enum,
    Module,
    Other,
}

#[derive(NifUnitEnum)]
#[derive(Clone, Copy)]
pub enum DiagnosticSeverity {
    Error,
    Warning,
    Info,
}

#[rustler::nif]
pub fn detect_language_from_extension(ext: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn detect_language_from_path(path: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn extension_ambiguity(ext: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn extension_ambiguity_json(ext: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn detect_language_from_content(content: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn extract(source: String, config: ExtractionConfig) -> Result<ExtractionResult, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn validate_extraction(config: ExtractionConfig) -> Result<ValidationResult, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn chunk_source(source: String, language: String, max_chunk_size: usize, _lang: String, tree: String) -> Vec<CodeChunk> {
    todo!("call into core")
}

#[rustler::nif]
pub fn extract_intelligence(source: String, language: String, tree: String) -> ProcessResult {
    todo!("call into core")
}

#[rustler::nif]
pub fn process(source: String, config: ProcessConfig, registry: LanguageRegistry) -> Result<ProcessResult, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn snake_to_camel(val: String) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn camel_to_snake(val: String) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn node_info_from_node(node: String) -> NodeInfo {
    todo!("call into core")
}

#[rustler::nif]
pub fn root_node_info(tree: String) -> NodeInfo {
    todo!("call into core")
}

#[rustler::nif]
pub fn find_nodes_by_type(tree: String, node_type: String) -> Vec<NodeInfo> {
    todo!("call into core")
}

#[rustler::nif]
pub fn named_children_info(tree: String) -> Vec<NodeInfo> {
    todo!("call into core")
}

#[rustler::nif]
pub fn parse_string(language: String, source: Vec<u8>) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn tree_contains_node_type(tree: String, node_type: String) -> bool {
    todo!("call into core")
}

#[rustler::nif]
pub fn tree_has_error_nodes(tree: String) -> bool {
    todo!("call into core")
}

#[rustler::nif]
pub fn tree_to_sexp(tree: String) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn tree_error_count(tree: String) -> usize {
    todo!("call into core")
}

#[rustler::nif]
pub fn get_highlights_query(language: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn get_injections_query(language: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn get_locals_query(language: String) -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn run_query(tree: String, language: String, query_source: String, source: Vec<u8>) -> Result<Vec<QueryMatch>, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn split_code(source: String, tree: String, max_chunk_size: usize) -> Vec<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn load_definitions(json: String) -> Result<LanguageDefinitions, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn get_language(name: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn get_parser(name: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn available_languages() -> Vec<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn has_language(name: String) -> bool {
    todo!("call into core")
}

#[rustler::nif]
pub fn language_count() -> usize {
    todo!("call into core")
}

#[rustler::nif]
pub fn extract_patterns(source: String, config: ExtractionConfig) -> Result<ExtractionResult, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn init(config: PackConfig) -> Result<(), String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn configure(config: PackConfig) -> Result<(), String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn download(names: Vec<String>) -> Result<usize, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn download_all() -> Result<usize, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn manifest_languages() -> Result<Vec<String>, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloaded_languages() -> Vec<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn clean_cache() -> Result<(), String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn cache_dir() -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn compiledextraction_fmt(resource: ResourceArc<CompiledExtraction>, f: String) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn compiledextraction_compile(config: ExtractionConfig) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn compiledextraction_compile_with_language(language: String, language_name: String, extraction_patterns: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn compiledextraction_extract(resource: ResourceArc<CompiledExtraction>, source: String) -> Result<ExtractionResult, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn compiledextraction_extract_from_tree(resource: ResourceArc<CompiledExtraction>, tree: String, source: Vec<u8>) -> Result<ExtractionResult, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn packconfig_from_toml_file(path: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn packconfig_discover() -> Option<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn processconfig_default() -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn processconfig_with_chunking(resource: ResourceArc<ProcessConfig>, max_size: usize) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn processconfig_all(resource: ResourceArc<ProcessConfig>) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn processconfig_minimal(resource: ResourceArc<ProcessConfig>) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_with_libs_dir(libs_dir: String) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_add_extra_libs_dir(resource: ResourceArc<LanguageRegistry>, dir: String) -> () {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_get_language(resource: ResourceArc<LanguageRegistry>, name: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_available_languages(resource: ResourceArc<LanguageRegistry>) -> Vec<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_has_language(resource: ResourceArc<LanguageRegistry>, name: String) -> bool {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_language_count(resource: ResourceArc<LanguageRegistry>) -> usize {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_process(resource: ResourceArc<LanguageRegistry>, source: String, config: ProcessConfig) -> Result<ProcessResult, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn languageregistry_default() -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn config_load(path: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn config_discover() -> Result<Option<String>, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_new(version: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_with_cache_dir(version: String, cache_dir: String) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_default_cache_dir(version: String) -> Result<String, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_cache_dir(resource: ResourceArc<DownloadManager>) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_installed_languages(resource: ResourceArc<DownloadManager>) -> Vec<String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_ensure_languages(resource: ResourceArc<DownloadManager>, names: Vec<String>) -> Result<(), String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_ensure_group(resource: ResourceArc<DownloadManager>, group: String) -> Result<(), String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_lib_path(resource: ResourceArc<DownloadManager>, name: String) -> String {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_fetch_manifest(resource: ResourceArc<DownloadManager>) -> Result<ParserManifest, String> {
    todo!("call into core")
}

#[rustler::nif]
pub fn downloadmanager_clean_cache(resource: ResourceArc<DownloadManager>) -> Result<(), String> {
    todo!("call into core")
}

impl From<PatternValidation> for ts_pack_core::PatternValidation {
    fn from(val: PatternValidation) -> Self {
        Self {
            valid: val.valid,
            capture_names: val.capture_names,
            pattern_count: val.pattern_count,
            warnings: val.warnings,
            errors: val.errors,
        }
    }
}

impl From<ts_pack_core::PatternValidation> for PatternValidation {
    fn from(val: ts_pack_core::PatternValidation) -> Self {
        Self {
            valid: val.valid,
            capture_names: val.capture_names,
            pattern_count: val.pattern_count,
            warnings: val.warnings,
            errors: val.errors,
        }
    }
}

impl From<Span> for ts_pack_core::Span {
    fn from(val: Span) -> Self {
        Self {
            start_byte: val.start_byte,
            end_byte: val.end_byte,
            start_line: val.start_line,
            start_column: val.start_column,
            end_line: val.end_line,
            end_column: val.end_column,
        }
    }
}

impl From<ts_pack_core::Span> for Span {
    fn from(val: ts_pack_core::Span) -> Self {
        Self {
            start_byte: val.start_byte,
            end_byte: val.end_byte,
            start_line: val.start_line,
            start_column: val.start_column,
            end_line: val.end_line,
            end_column: val.end_column,
        }
    }
}

impl From<FileMetrics> for ts_pack_core::FileMetrics {
    fn from(val: FileMetrics) -> Self {
        Self {
            total_lines: val.total_lines,
            code_lines: val.code_lines,
            comment_lines: val.comment_lines,
            blank_lines: val.blank_lines,
            total_bytes: val.total_bytes,
            node_count: val.node_count,
            error_count: val.error_count,
            max_depth: val.max_depth,
        }
    }
}

impl From<ts_pack_core::FileMetrics> for FileMetrics {
    fn from(val: ts_pack_core::FileMetrics) -> Self {
        Self {
            total_lines: val.total_lines,
            code_lines: val.code_lines,
            comment_lines: val.comment_lines,
            blank_lines: val.blank_lines,
            total_bytes: val.total_bytes,
            node_count: val.node_count,
            error_count: val.error_count,
            max_depth: val.max_depth,
        }
    }
}

impl From<DocSection> for ts_pack_core::DocSection {
    fn from(val: DocSection) -> Self {
        Self {
            kind: val.kind,
            name: val.name,
            description: val.description,
        }
    }
}

impl From<ts_pack_core::DocSection> for DocSection {
    fn from(val: ts_pack_core::DocSection) -> Self {
        Self {
            kind: val.kind,
            name: val.name,
            description: val.description,
        }
    }
}

impl From<PackConfig> for ts_pack_core::PackConfig {
    fn from(val: PackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir,
            languages: val.languages,
            groups: val.groups,
        }
    }
}

impl From<ts_pack_core::PackConfig> for PackConfig {
    fn from(val: ts_pack_core::PackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir,
            languages: val.languages,
            groups: val.groups,
        }
    }
}

impl From<LanguagePackConfig> for ts_pack_core::LanguagePackConfig {
    fn from(val: LanguagePackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir,
            definitions: val.definitions,
        }
    }
}

impl From<ts_pack_core::LanguagePackConfig> for LanguagePackConfig {
    fn from(val: ts_pack_core::LanguagePackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir,
            definitions: val.definitions,
        }
    }
}

impl From<LanguagesConfig> for ts_pack_core::LanguagesConfig {
    fn from(val: LanguagesConfig) -> Self {
        Self {
            include: val.include,
            exclude: val.exclude,
        }
    }
}

impl From<ts_pack_core::LanguagesConfig> for LanguagesConfig {
    fn from(val: ts_pack_core::LanguagesConfig) -> Self {
        Self {
            include: val.include,
            exclude: val.exclude,
        }
    }
}

impl From<LanguageDefinition> for ts_pack_core::LanguageDefinition {
    fn from(val: LanguageDefinition) -> Self {
        Self {
            repo: val.repo,
            rev: val.rev,
            branch: val.branch,
            directory: val.directory,
            generate: val.generate,
            abi_version: val.abi_version,
            extensions: val.extensions,
            c_symbol: val.c_symbol,
            ambiguous: val.ambiguous,
        }
    }
}

impl From<ts_pack_core::LanguageDefinition> for LanguageDefinition {
    fn from(val: ts_pack_core::LanguageDefinition) -> Self {
        Self {
            repo: val.repo,
            rev: val.rev,
            branch: val.branch,
            directory: val.directory,
            generate: val.generate,
            abi_version: val.abi_version,
            extensions: val.extensions,
            c_symbol: val.c_symbol,
            ambiguous: val.ambiguous,
        }
    }
}

impl From<PlatformBundle> for ts_pack_core::PlatformBundle {
    fn from(val: PlatformBundle) -> Self {
        Self {
            url: val.url,
            sha256: val.sha256,
            size: val.size,
        }
    }
}

impl From<ts_pack_core::PlatformBundle> for PlatformBundle {
    fn from(val: ts_pack_core::PlatformBundle) -> Self {
        Self {
            url: val.url,
            sha256: val.sha256,
            size: val.size,
        }
    }
}

impl From<LanguageInfo> for ts_pack_core::LanguageInfo {
    fn from(val: LanguageInfo) -> Self {
        Self {
            group: val.group,
            size: val.size,
        }
    }
}

impl From<ts_pack_core::LanguageInfo> for LanguageInfo {
    fn from(val: ts_pack_core::LanguageInfo) -> Self {
        Self {
            group: val.group,
            size: val.size,
        }
    }
}

impl From<CaptureOutput> for ts_pack_core::CaptureOutput {
    fn from(val: CaptureOutput) -> Self {
        match val {
            CaptureOutput::Text => Self::Text,
            CaptureOutput::Node => Self::Node,
            CaptureOutput::Full => Self::Full,
        }
    }
}

impl From<ts_pack_core::CaptureOutput> for CaptureOutput {
    fn from(val: ts_pack_core::CaptureOutput) -> Self {
        match val {
            ts_pack_core::CaptureOutput::Text => Self::Text,
            ts_pack_core::CaptureOutput::Node => Self::Node,
            ts_pack_core::CaptureOutput::Full => Self::Full,
        }
    }
}

impl From<CommentKind> for ts_pack_core::CommentKind {
    fn from(val: CommentKind) -> Self {
        match val {
            CommentKind::Line => Self::Line,
            CommentKind::Block => Self::Block,
            CommentKind::Doc => Self::Doc,
        }
    }
}

impl From<ts_pack_core::CommentKind> for CommentKind {
    fn from(val: ts_pack_core::CommentKind) -> Self {
        match val {
            ts_pack_core::CommentKind::Line => Self::Line,
            ts_pack_core::CommentKind::Block => Self::Block,
            ts_pack_core::CommentKind::Doc => Self::Doc,
        }
    }
}

impl From<ExportKind> for ts_pack_core::ExportKind {
    fn from(val: ExportKind) -> Self {
        match val {
            ExportKind::Named => Self::Named,
            ExportKind::Default => Self::Default,
            ExportKind::ReExport => Self::ReExport,
        }
    }
}

impl From<ts_pack_core::ExportKind> for ExportKind {
    fn from(val: ts_pack_core::ExportKind) -> Self {
        match val {
            ts_pack_core::ExportKind::Named => Self::Named,
            ts_pack_core::ExportKind::Default => Self::Default,
            ts_pack_core::ExportKind::ReExport => Self::ReExport,
        }
    }
}

impl From<DiagnosticSeverity> for ts_pack_core::DiagnosticSeverity {
    fn from(val: DiagnosticSeverity) -> Self {
        match val {
            DiagnosticSeverity::Error => Self::Error,
            DiagnosticSeverity::Warning => Self::Warning,
            DiagnosticSeverity::Info => Self::Info,
        }
    }
}

impl From<ts_pack_core::DiagnosticSeverity> for DiagnosticSeverity {
    fn from(val: ts_pack_core::DiagnosticSeverity) -> Self {
        match val {
            ts_pack_core::DiagnosticSeverity::Error => Self::Error,
            ts_pack_core::DiagnosticSeverity::Warning => Self::Warning,
            ts_pack_core::DiagnosticSeverity::Info => Self::Info,
        }
    }
}

rustler::init!("elixir_module", [detect_language_from_extension, detect_language_from_path, extension_ambiguity, extension_ambiguity_json, detect_language_from_content, extract, validate_extraction, chunk_source, extract_intelligence, process, snake_to_camel, camel_to_snake, node_info_from_node, root_node_info, find_nodes_by_type, named_children_info, parse_string, tree_contains_node_type, tree_has_error_nodes, tree_to_sexp, tree_error_count, get_highlights_query, get_injections_query, get_locals_query, run_query, split_code, load_definitions, get_language, get_parser, available_languages, has_language, language_count, extract_patterns, init, configure, download, download_all, manifest_languages, downloaded_languages, clean_cache, cache_dir, compiledextraction_fmt, compiledextraction_compile, compiledextraction_compile_with_language, compiledextraction_extract, compiledextraction_extract_from_tree, packconfig_from_toml_file, packconfig_discover, processconfig_default, processconfig_with_chunking, processconfig_all, processconfig_minimal, languageregistry_with_libs_dir, languageregistry_add_extra_libs_dir, languageregistry_get_language, languageregistry_available_languages, languageregistry_has_language, languageregistry_language_count, languageregistry_process, languageregistry_default, config_load, config_discover, downloadmanager_new, downloadmanager_with_cache_dir, downloadmanager_default_cache_dir, downloadmanager_cache_dir, downloadmanager_installed_languages, downloadmanager_ensure_languages, downloadmanager_ensure_group, downloadmanager_lib_path, downloadmanager_fetch_manifest, downloadmanager_clean_cache]);
