# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:975aee80e787d5784565356ea79fdbc3bcf331796330baaa0ad24bd4656dbcce
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: download."""

from tree_sitter_language_pack import (
    download_all,
    cache_dir,
    clean_cache,
    configure,
    downloaded_languages,
    init,
    manifest_languages,
    download,
)


def test_download_all_languages() -> None:
    """Download all language parsers and verify count is positive."""
    result = download_all()
    assert result > 0  # noqa: S101


def test_download_cache_dir() -> None:
    """Get the cache directory path and verify it is non-empty."""
    result = cache_dir()
    assert result  # noqa: S101


def test_download_clean_cache() -> None:
    """Clean the parser cache directory."""
    _ = clean_cache()


def test_download_configure_custom_dir() -> None:
    """Configure language pack with a custom cache directory."""
    config = {"cache_dir": "/tmp/tslp_test_cache"}  # noqa: S108
    _ = configure(config=config)


def test_download_downloaded_empty() -> None:
    """List downloaded languages (may be empty before any downloads)."""
    _ = downloaded_languages()


def test_download_init_default() -> None:
    """Initialize language pack with default config."""
    config = {}
    _ = init(config=config)


def test_download_manifest_languages() -> None:
    """List manifest languages and verify python is included."""
    result = manifest_languages()
    assert result  # noqa: S101
    assert "python" in result  # noqa: S101


def test_download_single_language() -> None:
    """Download a single language parser and verify count."""
    names = ["python"]
    result = download(names=names)
    assert result >= 1  # noqa: S101
