# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: registry."""
from tree_sitter_language_pack import available_languages, has_language, language_count


def test_registry_has_language_false() -> None:
    """has_language('nonexistent') should return false."""
    name = "nonexistent"
    result = has_language(name=name)
    # TODO: unsupported assertion type: is_false

def test_registry_has_language_true() -> None:
    """has_language('python') should return true."""
    name = "python"
    result = has_language(name=name)
    assert result is True  # noqa: S101

def test_registry_language_count() -> None:
    """language_count returns a value greater than 300."""
    result = language_count()
    assert result >= 300  # noqa: S101

def test_registry_list_languages() -> None:
    """available_languages should return a non-empty list."""
    result = available_languages()
    assert result  # noqa: S101

