// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:69491ca21da2b956702c30af3bf43b43b1af309aabcfd3c9b4a1a4d70fb9ced9
pub const api = @import("tree_sitter_language_pack.zig");
