// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:1fb093c46f79706426a5a2912ecfce571c3ed196d27ca493474c8365d53f4e05
pub const api = @import("tree_sitter_language_pack.zig");
