[build]
incremental = true

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+bulk-memory", "--cfg", "getrandom_backend=\"wasm_js\""]

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"
