# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:041b140d808ddd4209f64b72fd4e47a53e2fa68c0e052414eee3609b9ac58b77
# To regenerate: alef generate
# To verify freshness: alef verify
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The tree_sitter_language_pack package is expected to be installed in the current environment.
