// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0ce5c3689b6a47ad432f905e23ea29dffb55888d18c49decf3b31280cf5a8e7f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using TreeSitterLanguagePack;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: parsing.</summary>
public class ParsingTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_ParsingGoFunction()
    {
        // Parse a Go function declaration and assert node type
        var tree = TreeSitterLanguagePack.ParseString("go", "package main\nfunc main() {}");
        Assert.True(TreeSitterLanguagePack.TreeContainsNodeType(tree, "function_declaration"));
    }

    [Fact]
    public void Test_ParsingHtmlElement()
    {
        // Parse an HTML element and assert node type
        var tree = TreeSitterLanguagePack.ParseString("html", "<div>hello</div>");
        Assert.True(TreeSitterLanguagePack.TreeContainsNodeType(tree, "element"));
    }

    [Fact]
    public void Test_ParsingJavascriptClass()
    {
        // Parse a JavaScript class declaration.
        var tree = TreeSitterLanguagePack.ParseString("javascript", "class Foo { bar() {} }");
        Assert.True(tree.RootChildCount >= 1, "expected >= 1");
        Assert.True(TreeSitterLanguagePack.TreeContainsNodeType(tree, "class_declaration"));
    }

    [Fact]
    public void Test_ParsingJavascriptVariable()
    {
        // Parse a JavaScript variable declaration and assert node type
        var tree = TreeSitterLanguagePack.ParseString("javascript", "const x = 1;");
        Assert.True(TreeSitterLanguagePack.TreeContainsNodeType(tree, "lexical_declaration"));
    }

    [Fact]
    public void Test_ParsingPythonFunction()
    {
        // Parse a Python function definition and assert node type
        var tree = TreeSitterLanguagePack.ParseString("python", "def hello(): pass");
        Assert.True(TreeSitterLanguagePack.TreeContainsNodeType(tree, "function_definition"));
    }

    [Fact]
    public void Test_ParsingRustFunction()
    {
        // Parse a Rust function definition and assert node type
        var tree = TreeSitterLanguagePack.ParseString("rust", "fn main() {}");
        Assert.True(TreeSitterLanguagePack.TreeContainsNodeType(tree, "function_item"));
    }

    [Fact]
    public void Test_ParsingRustStruct()
    {
        // Parse a Rust struct definition.
        var tree = TreeSitterLanguagePack.ParseString("rust", "struct Point { x: f64, y: f64 }");
        Assert.True(tree.RootChildCount >= 1, "expected >= 1");
    }
}
