// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1ad4cf56aed7625da3015f3fec1261c2b2f8a70b90f3a765f51722a915088d2a
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
