// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33d15aec735513ed1afed8a2ccab3371a5ed8808f07b3c3513f8b8fb96803b9b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { process, get_highlights_query, get_injections_query, get_locals_query, parse_string, runQuery } from '@kreuzberg/tree-sitter-language-pack-wasm';

describe('query', () => {
  it('highlights_nonexistent_language: Get highlights query for nonexistent language returns null/empty', () => {
    const result = get_highlights_query("zzz_nonexistent_lang");
    expect(result.trim()).toHaveLength(0);
  });

  it('highlights_query_python: get_highlights_query returns non-empty string for python', () => {
    const result = get_highlights_query("python");
    expect(result.length).toBeGreaterThan(0);
  });

  it('highlights_query_unknown_language: get_highlights_query returns None for unknown language', () => {
    const result = get_highlights_query("nonexistent_language_xyz");
    expect(result.trim()).toHaveLength(0);
  });

  it('injections_query_javascript: get_injections_query returns non-empty for javascript (has embedded languages)', () => {
    const result = get_injections_query("javascript");
    expect(result.length).toBeGreaterThan(0);
  });

  it('injections_query_unknown_language: get_injections_query returns empty for unknown language', () => {
    const result = get_injections_query("nonexistent_xyz");
    expect(result.trim()).toHaveLength(0);
  });

  it('locals_query_python: get_locals_query returns non-empty for python', () => {
    const result = get_locals_query("python");
    expect(result.length).toBeGreaterThan(0);
  });

  it('locals_query_unknown_language: get_locals_query returns empty for unknown language', () => {
    const result = get_locals_query("nonexistent_xyz");
    expect(result.trim()).toHaveLength(0);
  });

  it('run_query_no_matches: Run query that matches no nodes returns empty result', () => {
    const tree = parse_string("python", "x = 1");
    expect(runQuery(tree, "python", "(class_definition name: (identifier) @name)", source).length).toBeGreaterThanOrEqual(0);
  });

  it('run_query_python_functions: Parse Python and run a query to find function definitions', () => {
    const tree = parse_string("python", "def hello():\n    pass\n\ndef world():\n    return 42\n");
    expect(runQuery(tree, "python", "(function_definition name: (identifier) @name)", source).length).toBeGreaterThanOrEqual(2);
  });
});
