// Generated by alef. Do not edit by hand.
// alef:hash:ae3a20b664e329067a906817e889efe88f13651f43060ee7d6a3744ec5a34dbd

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
