<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bef33f14fc9f55eb07e73b7064144e24db5e153b3dacd790e20207901838124d
// To regenerate: alef generate
// To verify freshness: alef verify

declare(strict_types=1);


// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../crates/ts-pack-core-php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
