// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:59d68b3a005095d17a18ef740ba26485d584a3d30ce3265c347a3e8db60c5609
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The cross-process download cache lock file could not be acquired or created.
/// </summary>
public class CacheLockException : ErrorException
{
    public CacheLockException(string message) : base(message) { }

    public CacheLockException(string message, Exception innerException) : base(message, innerException) { }
}
