// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:730dc518b17b2b9a833c2a7ffa3164e6b914cab01ff3d0555d4a784a16c9e39d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The cross-process download cache lock file could not be acquired or created.
/// </summary>
public class CacheLockException : ErrorException
{
    public CacheLockException(string message) : base(message) { }

    public CacheLockException(string message, Exception innerException) : base(message, innerException) { }
}
