// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:53f4264c665f2b7f4f4f67ad6419fa3a535118e1e08c932b3bcbbd599d3ffe7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace TreeSitterLanguagePack;

/// <summary>
/// Controls what data is captured for each query match.
/// </summary>
public enum CaptureOutput
{
    /// <summary>
    /// Capture only the matched text.
    /// </summary>
    [JsonPropertyName("text")]
    Text,
    /// <summary>
    /// Capture only the `NodeInfo`.
    /// </summary>
    [JsonPropertyName("node")]
    Node,
    /// <summary>
    /// Capture both text and `NodeInfo` (default).
    /// </summary>
    [JsonPropertyName("full")]
    Full,
}
