// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:28b964527996b813f2e66e947113760273e2d56c3a908d755dbe7a3ce385d625
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The downloaded file's SHA-256 digest did not match the manifest's expected value.
/// </summary>
public class ChecksumMismatchException : ErrorException
{
    public ChecksumMismatchException(string message) : base(message) { }

    public ChecksumMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
