// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1a2973c0a64993b72e5cf84dd27b3a0cc887e347d0bddf469e8eb840d015a6fc
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
