// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0d51a59da5b6fc6f630e3eb3eb9f86f18679a9080b2ea2fc8b931e66fe6ab2ad
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A configuration file or value was invalid or could not be applied.
/// </summary>
public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
