// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d6fcefee5dfa16b2e9f81f103d6944915a0847e32ed44195abaadca197840e2b
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A configuration file or value was invalid or could not be applied.
/// </summary>
public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
