// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:951f26999642777a7197cecf8265ac17e3466a04056ee53922cc6c09f5020e54
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Severity level of a diagnostic produced during parsing.
///
/// Used to classify parse errors, warnings, and informational messages
/// found in the syntax tree.
/// </summary>
public enum DiagnosticSeverity
{
    [JsonPropertyName("error")]
    Error,
    [JsonPropertyName("warning")]
    Warning,
    [JsonPropertyName("info")]
    Info,
}
