// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:034f4c9b7b4f12dc6ec1b87fd42d718a8a2179b0966613d134258b4e0f5058c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// A diagnostic (syntax error, missing node, etc.) from parsing.
/// </summary>
public sealed class Diagnostic
{
    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

    [JsonPropertyName("severity")]
    public DiagnosticSeverity Severity { get; set; } = default;

    [JsonPropertyName("span")]
    public Span Span { get; set; } = default!;

}
