// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c53a7ffdc8fdc880c3ea04b8522a3b7f1ac34ac78fb7254c15a4a8aaa51cbfb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// A section within a docstring (e.g., Args, Returns, Raises).
/// </summary>
public sealed class DocSection
{
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = "";

    [JsonPropertyName("name")]
    public string? Name { get; set; } = null;

    [JsonPropertyName("description")]
    public string Description { get; set; } = "";

}
