// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A parser download from GitHub releases failed.
/// </summary>
public class DownloadException : ErrorException
{
    public DownloadException(string message) : base(message) { }

    public DownloadException(string message, Exception innerException) : base(message, innerException) { }
}
