// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:284faf7761a730a6f55589d07fee379a4a177ba75f3188f9a9407d84837db6a1
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A parser download from GitHub releases failed.
/// </summary>
public class DownloadException : ErrorException
{
    public DownloadException(string message) : base(message) { }

    public DownloadException(string message, Exception innerException) : base(message, innerException) { }
}
