// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ab4df5cadcf54bb45b29a3b5b15f16afb9d803bc063fb4d219cf2b39216ca0eb
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class DynamicLoadException : ErrorException
{
    public DynamicLoadException(string message) : base(message) { }

    public DynamicLoadException(string message, Exception innerException) : base(message, innerException) { }
}
