// This file is auto-generated by skif. DO NOT EDIT.

namespace TreeSitterLanguagePack;

/// <summary>
/// Errors that can occur when using the tree-sitter language pack.
///
/// Covers language lookup failures, parse errors, query errors, and I/O issues.
/// Feature-gated variants are included when `config`, `download`, or related
/// features are enabled.
/// </summary>
public enum Error
{
    LanguageNotFound,
    DynamicLoad,
    NullLanguagePointer,
    ParserSetup,
    LockPoisoned,
    Config,
    ParseFailed,
    QueryError,
    InvalidRange,
    Io,
    Json,
    Toml,
    Download,
    ChecksumMismatch,
}
