// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0d51a59da5b6fc6f630e3eb3eb9f86f18679a9080b2ea2fc8b931e66fe6ab2ad
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// The kind of an export statement found in source code.
///
/// Covers named exports, default exports, and re-exports from other modules.
/// </summary>
[JsonConverter(typeof(ExportKindJsonConverter))]
public enum ExportKind
{
    /// <summary>
    /// A named export (e.g., `export { foo }`).
    /// </summary>
    [JsonPropertyName("Named")]
    Named,
    /// <summary>
    /// A default export (e.g., `export default foo`).
    /// </summary>
    [JsonPropertyName("Default")]
    Default,
    /// <summary>
    /// A re-export from another module (e.g., `export { foo } from 'bar'`).
    /// </summary>
    [JsonPropertyName("ReExport")]
    ReExport,
}


/// <summary>
/// Custom JSON converter for <see cref="ExportKind"/> that respects explicit variant names.
/// </summary>
internal sealed class ExportKindJsonConverter : JsonConverter<ExportKind>
{
    public override ExportKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Named" => ExportKind.Named,
            "Default" => ExportKind.Default,
            "ReExport" => ExportKind.ReExport,
            _ => throw new JsonException($"Unknown ExportKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ExportKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ExportKind.Named => "Named",
            ExportKind.Default => "Default",
            ExportKind.ReExport => "ReExport",
            _ => throw new JsonException($"Unknown ExportKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
