// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// An export statement extracted from source code.
/// </summary>
public sealed class ExportInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("kind")]
    public ExportKind Kind { get; set; } = default!;

    [JsonPropertyName("span")]
    public Span Span { get; set; } = default!;

}
