// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32f16fa35714c46bbdad5cb5d474bd5ccfe5cc7263bc1287fbe2f5e853d5421b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Configuration for an extraction run against a single language.
/// </summary>
public sealed class ExtractionConfig
{
    /// <summary>
    /// The language name (e.g., `"python"`).
    /// </summary>
    [JsonPropertyName("language")]
    public string Language { get; set; } = "";

    /// <summary>
    /// Named patterns to run. Keys become the keys in `ExtractionResult::results`.
    /// </summary>
    [JsonPropertyName("patterns")]
    public Dictionary<string, ExtractionPattern> Patterns { get; set; } = new Dictionary<string, ExtractionPattern>();

}
