// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:79e30124d287b176aa5125256934d5ac8eb917f84e488c746214e0d293da9c8e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Complete extraction results for all patterns.
/// </summary>
public sealed class ExtractionResult
{
    /// <summary>
    /// The language that was used.
    /// </summary>
    [JsonPropertyName("language")]
    public string Language { get; set; } = "";

    /// <summary>
    /// Results keyed by pattern name.
    /// </summary>
    [JsonPropertyName("results")]
    public string Results { get; set; } = "";

}
