// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Aggregate metrics for a source file.
/// </summary>
public sealed class FileMetrics
{
    [JsonPropertyName("total_lines")]
    public ulong TotalLines { get; set; } = 0;

    [JsonPropertyName("code_lines")]
    public ulong CodeLines { get; set; } = 0;

    [JsonPropertyName("comment_lines")]
    public ulong CommentLines { get; set; } = 0;

    [JsonPropertyName("blank_lines")]
    public ulong BlankLines { get; set; } = 0;

    [JsonPropertyName("total_bytes")]
    public ulong TotalBytes { get; set; } = 0;

    [JsonPropertyName("node_count")]
    public ulong NodeCount { get; set; } = 0;

    [JsonPropertyName("error_count")]
    public ulong ErrorCount { get; set; } = 0;

    [JsonPropertyName("max_depth")]
    public ulong MaxDepth { get; set; } = 0;

}
