// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:09e8c1bee210cfa65ccc69b73c3857131ed10e74bec26ecd0514305d2769ac92
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range was invalid (e.g., end before start, or out of bounds).
/// </summary>
public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
