// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:043d92c8e0db940fd6ccc70983cfb12e32afb3b9435c958a2c03e60d9a0a17aa
using System;

namespace TreeSitterLanguagePack;

public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
