// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5e2360f9d8bf15388603a52cab0280291d764e4fe2217516bce86c2328d1ca96
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range was invalid (e.g., end before start, or out of bounds).
/// </summary>
public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
