// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e767b1c19a8582dffbca547d7edc56901a92128409a45c07b98715d8a4214e02
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The requested language name (or alias) was not found in the registry.
/// </summary>
public class LanguageNotFoundException : ErrorException
{
    public LanguageNotFoundException(string message) : base(message) { }

    public LanguageNotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
