// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2c35f3c1db228389f0c1c0d635a40bf8c3feae99841d621703859c0429b82c31
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The requested language name (or alias) was not found in the registry.
/// </summary>
public class LanguageNotFoundException : ErrorException
{
    public LanguageNotFoundException(string message) : base(message) { }

    public LanguageNotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
