// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7470d7488da95b938f60bdf3553afe66abd935aad6c7326e96c821a3d034926e
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// An internal `RwLock` or `Mutex` was poisoned by a previous panic.
/// </summary>
public class LockPoisonedException : ErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
