// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Lightweight snapshot of a tree-sitter node's properties.
/// 
/// Contains only primitive types for easy cross-language serialization.
/// This is an owned type that can be passed across FFI boundaries, unlike
/// `tree_sitter::Node` which borrows from the tree.
/// </summary>
public sealed class NodeInfo
{
    /// <summary>
    /// The grammar type name (e.g., "function_definition", "identifier").
    /// </summary>
    [JsonPropertyName("kind")]
    public required string Kind { get; set; }

    /// <summary>
    /// Whether this is a named node (vs anonymous like punctuation).
    /// </summary>
    [JsonPropertyName("isNamed")]
    public required bool IsNamed { get; set; }

    /// <summary>
    /// Start byte offset in source.
    /// </summary>
    [JsonPropertyName("startByte")]
    public required nuint StartByte { get; set; }

    /// <summary>
    /// End byte offset in source.
    /// </summary>
    [JsonPropertyName("endByte")]
    public required nuint EndByte { get; set; }

    /// <summary>
    /// Start row (zero-indexed).
    /// </summary>
    [JsonPropertyName("startRow")]
    public required nuint StartRow { get; set; }

    /// <summary>
    /// Start column (zero-indexed).
    /// </summary>
    [JsonPropertyName("startCol")]
    public required nuint StartCol { get; set; }

    /// <summary>
    /// End row (zero-indexed).
    /// </summary>
    [JsonPropertyName("endRow")]
    public required nuint EndRow { get; set; }

    /// <summary>
    /// End column (zero-indexed).
    /// </summary>
    [JsonPropertyName("endCol")]
    public required nuint EndCol { get; set; }

    /// <summary>
    /// Number of named children.
    /// </summary>
    [JsonPropertyName("namedChildCount")]
    public required nuint NamedChildCount { get; set; }

    /// <summary>
    /// Whether this node is an ERROR node.
    /// </summary>
    [JsonPropertyName("isError")]
    public required bool IsError { get; set; }

    /// <summary>
    /// Whether this node is a MISSING node.
    /// </summary>
    [JsonPropertyName("isMissing")]
    public required bool IsMissing { get; set; }

}
