// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6378b26fb320d496d2822fec4e0bb0ff4d59c43588c965c635ffb09715a3c08a
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter language function returned a null pointer for the given language name.
/// </summary>
public class NullLanguagePointerException : ErrorException
{
    public NullLanguagePointerException(string message) : base(message) { }

    public NullLanguagePointerException(string message, Exception innerException) : base(message, innerException) { }
}
