// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:49aa1ae599ec76664adde3fea521b33b40a190fbbb9d256656ffa468d1e3e467
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The parse was cancelled because it exceeded its configured wall-clock budget.
///
/// Raised only when a budget is configured — see
/// `ProcessConfig.parse_timeout_ms`,
/// which defaults to `None`.
/// </summary>
public class ParseTimeoutException : ErrorException
{
    public ParseTimeoutException(string message) : base(message) { }

    public ParseTimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
