// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f34bc70692bdeaca89cc9cb90f3e888b193a0eccd8cd5d98e4fb204e168e36bc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;

namespace TreeSitterLanguagePack;

public sealed class Parser : IDisposable
{
    internal IntPtr Handle { get; }

    internal Parser(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
