// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0a497da07b96601305a97ca913583593c5ed0bf6b464aa6e54638d207cd81efb
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The language could not be applied to the parser (e.g., ABI version mismatch).
/// </summary>
public class ParserSetupException : ErrorException
{
    public ParserSetupException(string message) : base(message) { }

    public ParserSetupException(string message, Exception innerException) : base(message, innerException) { }
}
