// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ad1476a835ddd61d3a59152f02d16d01be102d4c11f23321ffef0931b5daa6e7
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter parser returned no tree for the given source input.
/// </summary>
public class ParseFailedException : ErrorException
{
    public ParseFailedException(string message) : base(message) { }

    public ParseFailedException(string message, Exception innerException) : base(message, innerException) { }
}
