// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace TreeSitterLanguagePack;

/// <summary>
/// The kind of structural item found in source code.
///
/// Categorizes top-level and nested declarations such as functions, classes,
/// structs, enums, traits, and more. Use [`Other`](StructureKind::Other) for
/// language-specific constructs that do not fit a standard category.
/// </summary>
public enum StructureKind
{
    [JsonPropertyName("function")]
    Function,
    [JsonPropertyName("method")]
    Method,
    [JsonPropertyName("class")]
    Class,
    [JsonPropertyName("struct")]
    Struct,
    [JsonPropertyName("interface")]
    Interface,
    [JsonPropertyName("enum")]
    Enum,
    [JsonPropertyName("module")]
    Module,
    [JsonPropertyName("trait")]
    Trait,
    [JsonPropertyName("impl")]
    Impl,
    [JsonPropertyName("namespace")]
    Namespace,
    [JsonPropertyName("other")]
    Other,
}
