// Code generated by e2e-generator. DO NOT EDIT.

using Xunit;
using TreeSitterLanguagePack;

namespace E2E.Tests;

public class LanguageDetectionTests
{

    [Fact]
    public void DetectContentBashShebang()
    {
        // detect_language_from_content recognizes #!/bin/bash shebang
        var detectResult = TsPackClient.DetectLanguageFromContent("#!/bin/bash\necho hi");
        Assert.Equal("bash", detectResult);
    }

    [Fact]
    public void DetectContentNoShebang()
    {
        // detect_language_from_content returns None when no shebang present
        var detectResult = TsPackClient.DetectLanguageFromContent("no shebang here");
        Assert.Null(detectResult);
    }

    [Fact]
    public void DetectContentPythonShebang()
    {
        // detect_language_from_content recognizes #!/usr/bin/env python3 shebang
        var detectResult = TsPackClient.DetectLanguageFromContent("#!/usr/bin/env python3\npass");
        Assert.Equal("python", detectResult);
    }

    [Fact]
    public void DetectExtCpp()
    {
        // detect_language_from_extension recognizes .cpp as cpp
        var detectResult = TsPackClient.DetectLanguage("file.cpp");
        Assert.Equal("cpp", detectResult);
    }

    [Fact]
    public void DetectExtGo()
    {
        // detect_language_from_extension recognizes .go as go
        var detectResult = TsPackClient.DetectLanguage("file.go");
        Assert.Equal("go", detectResult);
    }

    [Fact]
    public void DetectExtJava()
    {
        // detect_language_from_extension recognizes .java as java
        var detectResult = TsPackClient.DetectLanguage("file.java");
        Assert.Equal("java", detectResult);
    }

    [Fact]
    public void DetectExtJavascript()
    {
        // detect_language_from_extension recognizes .js as javascript
        var detectResult = TsPackClient.DetectLanguage("file.js");
        Assert.Equal("javascript", detectResult);
    }

    [Fact]
    public void DetectExtPhp()
    {
        // detect_language_from_extension recognizes .php as php
        var detectResult = TsPackClient.DetectLanguage("file.php");
        Assert.Equal("php", detectResult);
    }

    [Fact]
    public void DetectExtPython()
    {
        // detect_language_from_extension recognizes .py as python
        var detectResult = TsPackClient.DetectLanguage("file.py");
        Assert.Equal("python", detectResult);
    }

    [Fact]
    public void DetectExtRuby()
    {
        // detect_language_from_extension recognizes .rb as ruby
        var detectResult = TsPackClient.DetectLanguage("file.rb");
        Assert.Equal("ruby", detectResult);
    }

    [Fact]
    public void DetectExtRust()
    {
        // detect_language_from_extension recognizes .rs as rust
        var detectResult = TsPackClient.DetectLanguage("file.rs");
        Assert.Equal("rust", detectResult);
    }

    [Fact]
    public void DetectExtTypescript()
    {
        // detect_language_from_extension recognizes .ts as typescript
        var detectResult = TsPackClient.DetectLanguage("file.ts");
        Assert.Equal("typescript", detectResult);
    }

    [Fact]
    public void DetectExtUnknown()
    {
        // detect_language_from_extension returns None for unknown extension .xyz
        var detectResult = TsPackClient.DetectLanguage("file.xyz");
        Assert.Null(detectResult);
    }

    [Fact]
    public void DetectPathDotfile()
    {
        // detect_language_from_path returns None for dotfile .gitignore (no standard extension)
        var detectResult = TsPackClient.DetectLanguage(".gitignore");
        Assert.Null(detectResult);
    }

    [Fact]
    public void DetectPathGoNested()
    {
        // detect_language_from_path extracts extension from nested path lib/server.go
        var detectResult = TsPackClient.DetectLanguage("lib/server.go");
        Assert.Equal("go", detectResult);
    }

    [Fact]
    public void DetectPathJavaRoot()
    {
        // detect_language_from_path recognizes Main.java in root directory
        var detectResult = TsPackClient.DetectLanguage("Main.java");
        Assert.Equal("java", detectResult);
    }

    [Fact]
    public void DetectPathJsRoot()
    {
        // detect_language_from_path recognizes app.js in root directory
        var detectResult = TsPackClient.DetectLanguage("app.js");
        Assert.Equal("javascript", detectResult);
    }

    [Fact]
    public void DetectPathNested()
    {
        // detect_language_from_path extracts extension from nested path src/main.py
        var detectResult = TsPackClient.DetectLanguage("src/main.py");
        Assert.Equal("python", detectResult);
    }

    [Fact]
    public void DetectPathNoExtension()
    {
        // detect_language_from_path returns None for extensionless file Makefile
        var detectResult = TsPackClient.DetectLanguage("Makefile");
        Assert.Null(detectResult);
    }

    [Fact]
    public void DetectPathRustSrc()
    {
        // detect_language_from_path extracts extension from nested path src/main.rs
        var detectResult = TsPackClient.DetectLanguage("src/main.rs");
        Assert.Equal("rust", detectResult);
    }
}
