// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8df29dd605af6a40c15a5c8b4a349e2ba6936f88cebcd95cb2a3f07dc9167da4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:tree_sitter_language_pack/tree_sitter_language_pack.dart';

// E2e tests for category: download
void main() {
  test('Download all language parsers and verify count is positive', () {
    final result = downloadAll();
    expect(result, greaterThan(0));
  });

  test('Get the cache directory path and verify it is non-empty', () {
    final result = cacheDir();
    expect(result, isNotEmpty);
  });

  test('Clean the parser cache directory', () {
    final result = cleanCache();
  });

  test('Configure language pack with a custom cache directory', () {
    final result = configure('{"cache_dir":"/tmp/tslp_test_cache"}');
  });

  test('List downloaded languages (may be empty before any downloads)', () {
    final result = downloadedLanguages();
  });

  test('Initialize language pack with default config', () {
    final result = init('{}');
  });

  test('List manifest languages and verify python is included', () {
    final result = manifestLanguages();
    expect(result, isNotEmpty);
    expect(result, contains('python'));
  });

  test('Download a single language parser and verify count', () {
    final result = download(['python']);
    expect(result, greaterThanOrEqualTo(1));
  });

}
