// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:975aee80e787d5784565356ea79fdbc3bcf331796330baaa0ad24bd4656dbcce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A comment extracted from source code.
 */
public record CommentInfo(
    String text,
    CommentKind kind,
    Span span,
    @JsonProperty("associated_node") Optional<String> associatedNode
) {
    public static CommentInfoBuilder builder() {
        return new CommentInfoBuilder();
    }
}
