// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38cb1fa66e6f3a4ba47db4db86f8b7968ddb8e975d7ed72dd9edb339f498af57
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.Optional;

/**
 * A section within a docstring (e.g., Args, Returns, Raises).
 */
public class DocSectionBuilder {

    private String kind = "";
    private Optional<String> name = Optional.empty();
    private String description = "";

    /** Sets the kind field. */
    public DocSectionBuilder withKind(final String value) {
        this.kind = value;
        return this;
    }

    /** Sets the name field. */
    public DocSectionBuilder withName(final Optional<String> value) {
        this.name = value;
        return this;
    }

    /** Sets the description field. */
    public DocSectionBuilder withDescription(final String value) {
        this.description = value;
        return this;
    }

    /** Builds the DocSection instance. */
    public DocSection build() {
        return new DocSection(
            kind,
            name,
            description
        );
    }
}
