// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import java.util.Optional;

/**
 * Defines a single extraction pattern and its configuration.
 */
public class ExtractionPatternBuilder {

    private String query = "";
    private CaptureOutput captureOutput = null;
    private List<String> childFields = List.of();
    private Optional<Long> maxResults = Optional.empty();
    private Optional<List<Long>> byteRange = Optional.empty();

    /** Sets the query field. */
    public ExtractionPatternBuilder withQuery(final String value) {
        this.query = value;
        return this;
    }

    /** Sets the captureOutput field. */
    public ExtractionPatternBuilder withCaptureOutput(final CaptureOutput value) {
        this.captureOutput = value;
        return this;
    }

    /** Sets the childFields field. */
    public ExtractionPatternBuilder withChildFields(final List<String> value) {
        this.childFields = value;
        return this;
    }

    /** Sets the maxResults field. */
    public ExtractionPatternBuilder withMaxResults(final Optional<Long> value) {
        this.maxResults = value;
        return this;
    }

    /** Sets the byteRange field. */
    public ExtractionPatternBuilder withByteRange(final Optional<List<Long>> value) {
        this.byteRange = value;
        return this;
    }

    /** Builds the ExtractionPattern instance. */
    public ExtractionPattern build() {
        return new ExtractionPattern(
            query,
            captureOutput,
            childFields,
            maxResults,
            byteRange
        );
    }
}
