// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import java.util.Optional;

/**
 * An import statement extracted from source code.
 */
public class ImportInfoBuilder {

    private String source = "";
    private List<String> items = List.of();
    private Optional<String> alias = Optional.empty();
    private boolean isWildcard = false;
    private Span span = null;

    public ImportInfoBuilder withSource(String value) {
        this.source = value;
        return this;
    }

    public ImportInfoBuilder withItems(List<String> value) {
        this.items = value;
        return this;
    }

    public ImportInfoBuilder withAlias(Optional<String> value) {
        this.alias = value;
        return this;
    }

    public ImportInfoBuilder withIsWildcard(boolean value) {
        this.isWildcard = value;
        return this;
    }

    public ImportInfoBuilder withSpan(Span value) {
        this.span = value;
        return this;
    }

    public ImportInfo build() {
        return new ImportInfo(
            source,
            items,
            alias,
            isWildcard,
            span
        );
    }
}
