// DO NOT EDIT - auto-generated by alef
// alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
package dev.kreuzberg.treesitterlanguagepack;

public class InvalidRangeException extends ErrorException {
    /** Creates a new InvalidRangeException with the given message. */
    public InvalidRangeException(final String message) {
        super(message);
    }

    /** Creates a new InvalidRangeException with the given message and cause. */
    public InvalidRangeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
