// DO NOT EDIT - auto-generated by alef
// alef:hash:28b10682140de3ba767b348a698127f0e8c9d97c72e61938c671f76d227ee856
package dev.kreuzberg.treesitterlanguagepack;

public class IoException extends ErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
