// DO NOT EDIT - auto-generated by alef
// alef:hash:70a27eea50d837c86d5c634efc4a5bec15299535ee0e48ec2ea8106e67cf2a17
package dev.kreuzberg.treesitterlanguagepack;

public class LockPoisonedException extends ErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
