// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d6354d64f0aa9c95577e25095f590fadf9b1c7393a4b5d84028b412247adf509
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Results for a single named pattern.
 */
public record PatternResult(
    /** The individual matches. */
    List<MatchResult> matches,
    /** Total number of matches before {@code max_results} truncation. */
    @JsonProperty("total_count") long totalCount
) {
    public static PatternResultBuilder builder() {
        return new PatternResultBuilder();
    }
}
