// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

public record QueryMatch(
    @JsonProperty("pattern_index") long patternIndex,
    List<String> captures
) {
    public static QueryMatchBuilder builder() {
        return new QueryMatchBuilder();
    }
}
