// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;

/**
 * A single match from a tree-sitter query, with captured nodes.
 */
public class QueryMatchBuilder {

    private long patternIndex = 0;
    private List<String> captures = List.of();

    public QueryMatchBuilder withPatternIndex(long value) {
        this.patternIndex = value;
        return this;
    }

    public QueryMatchBuilder withCaptures(List<String> value) {
        this.captures = value;
        return this;
    }

    public QueryMatch build() {
        return new QueryMatch(
            patternIndex,
            captures
        );
    }
}
