// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0389ed0fe359aa35b51573ede14a932561057f0be3c18258b3844116cd2c9ca8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

public class Tree implements AutoCloseable {
    private final MemorySegment handle;

    Tree(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.TS_PACK_TREE_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free Tree: " + e.getMessage(), e);
            }
        }
    }
}
