// Code generated by alef. DO NOT EDIT.

// E2e tests for category: error-handling
package e2e_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go"
)

func Test_ErrorDetectContentEmpty(t *testing.T) {
	// Detect language from empty content returns null
	result, err := tspack.detect_language_from_content(``)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result) != 0 {
		t.Errorf("expected empty value, got %v", result)
	}
}

func Test_ErrorDetectExtensionEmpty(t *testing.T) {
	// Detect language from empty extension returns null
	result, err := tspack.detect_language_from_extension(``)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result) != 0 {
		t.Errorf("expected empty value, got %v", result)
	}
}

func Test_ErrorDetectPathEmpty(t *testing.T) {
	// Detect language from empty path returns null
	result, err := tspack.detect_language_from_path(``)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result) != 0 {
		t.Errorf("expected empty value, got %v", result)
	}
}

func Test_ErrorEmptyLanguageName(t *testing.T) {
	// Parsing with empty language name should error
	_, err := tspack.parse_string(``, `hello`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorExtractUnknownLanguage(t *testing.T) {
	// Extract patterns with unknown language returns error
	_, err := tspack.extract_patterns(`x = 1`, `{"language":"nonexistent_language_xyz","patterns":{}}`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorHandlingEmptySource(t *testing.T) {
	// Parsing an empty string should still produce a tree.
	_, err := tspack.parse_string(`javascript`, ``)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ErrorHandlingInvalidSyntax(t *testing.T) {
	// Parsing invalid syntax should produce a tree with error nodes.
	tree, err := tspack.parse_string(`javascript`, `function function function @@@ %%%`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, *tspack.TreeHasErrorNodes(tree), "expected true")
}

func Test_ErrorHandlingUnknownLanguage(t *testing.T) {
	// Loading a nonexistent language should produce an error.
	_, err := tspack.parse_string(`nonexistent_xyz`, ``)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorProcessEmptySource(t *testing.T) {
	// Process empty source code succeeds with zero metrics
	result, err := tspack.Process(``, `{"language":"python"}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Metrics.TotalLines != 0 {
		t.Errorf("equals mismatch: got %v", result.Metrics.TotalLines)
	}
}

func Test_ErrorRunQueryInvalidSyntax(t *testing.T) {
	// Run query with invalid S-expression syntax produces error
	tree, err := tspack.parse_string(`python`, `x = 1`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	{
		_, methodErr := tspack.RunQuery(tree, `python`, `(((`, []byte(source))
		assert.Error(t, methodErr)
	}
}

func Test_ParseEmptyLanguage(t *testing.T) {
	// parse_string() returns error with empty language name
	_, err := tspack.parse_string(``, `x = 1`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ProcessUnknownLanguage(t *testing.T) {
	// process() returns error when config language is unknown
	_, err := tspack.Process(`x = 1`, `{"language":"nonexistent_xyz"}`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}
