// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9cb4b46479889484cec381f36f9fa378c9df6fdf39b6d5409c8a991ab5fd28e6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: parsing
package e2e_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go"
)

func Test_ParsingGoFunction(t *testing.T) {
	// Parse a Go function declaration and assert node type
	tree, err := tspack.ParseString(`go`, `package main
func main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, *tspack.TreeContainsNodeType(tree, "function_declaration"), "expected true")
}

func Test_ParsingHtmlElement(t *testing.T) {
	// Parse an HTML element and assert node type
	tree, err := tspack.ParseString(`html`, `<div>hello</div>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, *tspack.TreeContainsNodeType(tree, "element"), "expected true")
}

func Test_ParsingJavascriptClass(t *testing.T) {
	// Parse a JavaScript class declaration.
	tree, err := tspack.ParseString(`javascript`, `class Foo { bar() {} }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if tree.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", tree.RootChildCount)
	}
	assert.True(t, *tspack.TreeContainsNodeType(tree, "class_declaration"), "expected true")
}

func Test_ParsingJavascriptVariable(t *testing.T) {
	// Parse a JavaScript variable declaration and assert node type
	tree, err := tspack.ParseString(`javascript`, `const x = 1;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, *tspack.TreeContainsNodeType(tree, "lexical_declaration"), "expected true")
}

func Test_ParsingPythonFunction(t *testing.T) {
	// Parse a Python function definition and assert node type
	tree, err := tspack.ParseString(`python`, `def hello(): pass`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, *tspack.TreeContainsNodeType(tree, "function_definition"), "expected true")
}

func Test_ParsingRustFunction(t *testing.T) {
	// Parse a Rust function definition and assert node type
	tree, err := tspack.ParseString(`rust`, `fn main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, *tspack.TreeContainsNodeType(tree, "function_item"), "expected true")
}

func Test_ParsingRustStruct(t *testing.T) {
	// Parse a Rust struct definition.
	tree, err := tspack.ParseString(`rust`, `struct Point { x: f64, y: f64 }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if tree.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", tree.RootChildCount)
	}
}
