// Code generated by alef. DO NOT EDIT.

// E2e tests for category: smoke
package e2e_test

import (
	"testing"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go"
)

func Test_SmokeAbl(t *testing.T) {
	// Smoke test: load abl and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeActionscript(t *testing.T) {
	// Smoke test: load actionscript and parse a simple snippet
	result, err := tspack.Process(`var x:int = 1;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAda(t *testing.T) {
	// Smoke test: load ada and parse a simple snippet
	result, err := tspack.Process(`procedure Main is begin null; end Main;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAgda(t *testing.T) {
	// Smoke test: load agda and parse a simple snippet
	result, err := tspack.Process(`module Main where`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAl(t *testing.T) {
	// Smoke test: load al and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAngular(t *testing.T) {
	// Smoke test: load angular and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeApex(t *testing.T) {
	// Smoke test: load apex and parse a simple snippet
	result, err := tspack.Process(`public class Main {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeArduino(t *testing.T) {
	// Smoke test: load arduino and parse a simple snippet
	result, err := tspack.Process(`void setup() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAsciidoc(t *testing.T) {
	// Smoke test: load asciidoc and parse a simple snippet
	result, err := tspack.Process(`= Title

Paragraph.`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAsm(t *testing.T) {
	// Smoke test: load asm and parse a simple snippet
	result, err := tspack.Process(`mov eax, 1`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAstro(t *testing.T) {
	// Smoke test: load astro and parse a simple snippet
	result, err := tspack.Process(`---
---
<p>hello</p>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeAwk(t *testing.T) {
	// Smoke test: load awk and parse a simple snippet
	result, err := tspack.Process(`BEGIN { print "hello" }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBash(t *testing.T) {
	// Smoke test: load bash and parse a simple snippet
	result, err := tspack.Process(`echo hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBass(t *testing.T) {
	// Smoke test: load bass and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBatch(t *testing.T) {
	// Smoke test: load batch and parse a simple snippet
	result, err := tspack.Process(`@echo off
echo hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBeancount(t *testing.T) {
	// Smoke test: load beancount and parse a simple snippet
	result, err := tspack.Process(`2024-01-01 open Assets:Bank USD`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBibtex(t *testing.T) {
	// Smoke test: load bibtex and parse a simple snippet
	result, err := tspack.Process(`@article{key, title={A}}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBicep(t *testing.T) {
	// Smoke test: load bicep and parse a simple snippet
	result, err := tspack.Process(`param name string`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBitbake(t *testing.T) {
	// Smoke test: load bitbake and parse a simple snippet
	result, err := tspack.Process(`DESCRIPTION = "hello"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBlade(t *testing.T) {
	// Smoke test: load blade and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBrightscript(t *testing.T) {
	// Smoke test: load brightscript and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeBsl(t *testing.T) {
	// Smoke test: load bsl and parse a simple snippet
	result, err := tspack.Process(`Procedure Main() EndProcedure`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeC(t *testing.T) {
	// Smoke test: load c and parse a simple snippet
	result, err := tspack.Process(`int main() { return 0; }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeC3(t *testing.T) {
	// Smoke test: load c3 and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCaddy(t *testing.T) {
	// Smoke test: load caddy and parse a simple snippet
	result, err := tspack.Process(`:8080 {
	respond "Hello"
}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCairo(t *testing.T) {
	// Smoke test: load cairo and parse a simple snippet
	result, err := tspack.Process(`fn main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCapnp(t *testing.T) {
	// Smoke test: load capnp and parse a simple snippet
	result, err := tspack.Process(`@0xabcdef1234567890;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCedar(t *testing.T) {
	// Smoke test: load cedar and parse a simple snippet
	result, err := tspack.Process(`permit(principal, action, resource);`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCedarschema(t *testing.T) {
	// Smoke test: load cedarschema and parse a simple snippet
	result, err := tspack.Process(`entity User;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCel(t *testing.T) {
	// Smoke test: load cel and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCfml(t *testing.T) {
	// Smoke test: load cfml and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeChatito(t *testing.T) {
	// Smoke test: load chatito and parse a simple snippet
	result, err := tspack.Process(`%[greeting]
    hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeChuck(t *testing.T) {
	// Smoke test: load chuck and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCircom(t *testing.T) {
	// Smoke test: load circom and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeClarity(t *testing.T) {
	// Smoke test: load clarity and parse a simple snippet
	result, err := tspack.Process(`(define-public (hello) (ok true))`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeClojure(t *testing.T) {
	// Smoke test: load clojure and parse a simple snippet
	result, err := tspack.Process(`(def x 1)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCmake(t *testing.T) {
	// Smoke test: load cmake and parse a simple snippet
	result, err := tspack.Process(`cmake_minimum_required(VERSION 3.0)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCobol(t *testing.T) {
	// Smoke test: load cobol and parse a simple snippet
	result, err := tspack.Process(`       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO.`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeComment(t *testing.T) {
	// Smoke test: load comment and parse a simple snippet
	result, err := tspack.Process(`TODO: fix this`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCommonlisp(t *testing.T) {
	// Smoke test: load commonlisp and parse a simple snippet
	result, err := tspack.Process(`(defun hello () (print "hello"))`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCooklang(t *testing.T) {
	// Smoke test: load cooklang and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCorn(t *testing.T) {
	// Smoke test: load corn and parse a simple snippet
	result, err := tspack.Process(`{ key = "value" }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCpon(t *testing.T) {
	// Smoke test: load cpon and parse a simple snippet
	result, err := tspack.Process(`{"key": 1}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCpp(t *testing.T) {
	// Smoke test: load cpp and parse a simple snippet
	result, err := tspack.Process(`int main() { return 0; }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCrystal(t *testing.T) {
	// Smoke test: load crystal and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCsharp(t *testing.T) {
	// Smoke test: load csharp and parse a simple snippet
	result, err := tspack.Process(`class Main {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCss(t *testing.T) {
	// Smoke test: load css and parse a simple snippet
	result, err := tspack.Process(`body { color: red; }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCst(t *testing.T) {
	// Smoke test: load cst and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCsv(t *testing.T) {
	// Smoke test: load csv and parse a simple snippet
	result, err := tspack.Process(`a,b,c
1,2,3`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCuda(t *testing.T) {
	// Smoke test: load cuda and parse a simple snippet
	result, err := tspack.Process(`__global__ void kernel() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCue(t *testing.T) {
	// Smoke test: load cue and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeCylc(t *testing.T) {
	// Smoke test: load cylc and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeD(t *testing.T) {
	// Smoke test: load d and parse a simple snippet
	result, err := tspack.Process(`void main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDart(t *testing.T) {
	// Smoke test: load dart and parse a simple snippet
	result, err := tspack.Process(`void main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDesktop(t *testing.T) {
	// Smoke test: load desktop and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDevicetree(t *testing.T) {
	// Smoke test: load devicetree and parse a simple snippet
	result, err := tspack.Process(`/dts-v1/;
/ { };`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDhall(t *testing.T) {
	// Smoke test: load dhall and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDiff(t *testing.T) {
	// Smoke test: load diff and parse a simple snippet
	result, err := tspack.Process(`--- a/file
+++ b/file
@@ -1 +1 @@
-old
+new`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDjot(t *testing.T) {
	// Smoke test: load djot and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDockerfile(t *testing.T) {
	// Smoke test: load dockerfile and parse a simple snippet
	result, err := tspack.Process(`FROM alpine`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDot(t *testing.T) {
	// Smoke test: load dot and parse a simple snippet
	result, err := tspack.Process(`digraph G { A -> B; }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDoxygen(t *testing.T) {
	// Smoke test: load doxygen and parse a simple snippet
	result, err := tspack.Process(`/** @brief A function */`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeDtd(t *testing.T) {
	// Smoke test: load dtd and parse a simple snippet
	result, err := tspack.Process(`<!ELEMENT note (body)>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeEarthfile(t *testing.T) {
	// Smoke test: load earthfile and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeEbnf(t *testing.T) {
	// Smoke test: load ebnf and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeEditorconfig(t *testing.T) {
	// Smoke test: load editorconfig and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeEds(t *testing.T) {
	// Smoke test: load eds and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeEex(t *testing.T) {
	// Smoke test: load eex and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeElisp(t *testing.T) {
	// Smoke test: load elisp and parse a simple snippet
	result, err := tspack.Process(`(defun hello () (message "hello"))`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeElixir(t *testing.T) {
	// Smoke test: load elixir and parse a simple snippet
	result, err := tspack.Process(`IO.puts("hello")`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeElm(t *testing.T) {
	// Smoke test: load elm and parse a simple snippet
	result, err := tspack.Process(`module Main exposing (..)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeElsa(t *testing.T) {
	// Smoke test: load elsa and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeElvish(t *testing.T) {
	// Smoke test: load elvish and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeEmbeddedtemplate(t *testing.T) {
	// Smoke test: load embeddedtemplate and parse a simple snippet
	result, err := tspack.Process(`<%= value %>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeEnforce(t *testing.T) {
	// Smoke test: load enforce and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeErlang(t *testing.T) {
	// Smoke test: load erlang and parse a simple snippet
	result, err := tspack.Process(`main() -> ok.`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFacility(t *testing.T) {
	// Smoke test: load facility and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFaust(t *testing.T) {
	// Smoke test: load faust and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFennel(t *testing.T) {
	// Smoke test: load fennel and parse a simple snippet
	result, err := tspack.Process(`(fn hello [] (print :hello))`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFidl(t *testing.T) {
	// Smoke test: load fidl and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFirrtl(t *testing.T) {
	// Smoke test: load firrtl and parse a simple snippet
	result, err := tspack.Process(`circuit Main :`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFish(t *testing.T) {
	// Smoke test: load fish and parse a simple snippet
	result, err := tspack.Process(`echo hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFoam(t *testing.T) {
	// Smoke test: load foam and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeForth(t *testing.T) {
	// Smoke test: load forth and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFortran(t *testing.T) {
	// Smoke test: load fortran and parse a simple snippet
	result, err := tspack.Process(`program main
end program main`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFsharp(t *testing.T) {
	// Smoke test: load fsharp and parse a simple snippet
	result, err := tspack.Process(`let x = 1`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFsharpSignature(t *testing.T) {
	// Smoke test: load fsharp_signature and parse a simple snippet
	result, err := tspack.Process(`val x: int`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeFunc(t *testing.T) {
	// Smoke test: load func and parse a simple snippet
	result, err := tspack.Process(`() recv_internal() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGap(t *testing.T) {
	// Smoke test: load gap and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGdscript(t *testing.T) {
	// Smoke test: load gdscript and parse a simple snippet
	result, err := tspack.Process(`extends Node
func _ready():
	pass`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGdshader(t *testing.T) {
	// Smoke test: load gdshader and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGitConfig(t *testing.T) {
	// Smoke test: load git_config and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGitRebase(t *testing.T) {
	// Smoke test: load git_rebase and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGitattributes(t *testing.T) {
	// Smoke test: load gitattributes and parse a simple snippet
	result, err := tspack.Process(`*.txt text`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGitcommit(t *testing.T) {
	// Smoke test: load gitcommit and parse a simple snippet
	result, err := tspack.Process(`feat: add feature

Body text`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGitignore(t *testing.T) {
	// Smoke test: load gitignore and parse a simple snippet
	result, err := tspack.Process(`*.o
*.log`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGleam(t *testing.T) {
	// Smoke test: load gleam and parse a simple snippet
	result, err := tspack.Process(`pub fn main() { }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGlimmer(t *testing.T) {
	// Smoke test: load glimmer and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGlsl(t *testing.T) {
	// Smoke test: load glsl and parse a simple snippet
	result, err := tspack.Process(`void main() { gl_Position = vec4(0.0); }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGn(t *testing.T) {
	// Smoke test: load gn and parse a simple snippet
	result, err := tspack.Process(`group("hello") {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGnuplot(t *testing.T) {
	// Smoke test: load gnuplot and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGo(t *testing.T) {
	// Smoke test: load go and parse a simple snippet
	result, err := tspack.Process(`package main`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGodotResource(t *testing.T) {
	// Smoke test: load godot_resource and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGomod(t *testing.T) {
	// Smoke test: load gomod and parse a simple snippet
	result, err := tspack.Process(`module example.com/hello

go 1.21`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGosum(t *testing.T) {
	// Smoke test: load gosum and parse a simple snippet
	result, err := tspack.Process(`example.com/pkg v1.0.0 h1:abc=`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGotmpl(t *testing.T) {
	// Smoke test: load gotmpl and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGowork(t *testing.T) {
	// Smoke test: load gowork and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGpg(t *testing.T) {
	// Smoke test: load gpg and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGraphql(t *testing.T) {
	// Smoke test: load graphql and parse a simple snippet
	result, err := tspack.Process(`type Query { hello: String }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGren(t *testing.T) {
	// Smoke test: load gren and parse a simple snippet
	result, err := tspack.Process(`module Main exposing (..)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGroovy(t *testing.T) {
	// Smoke test: load groovy and parse a simple snippet
	result, err := tspack.Process(`def x = 1`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeGstlaunch(t *testing.T) {
	// Smoke test: load gstlaunch and parse a simple snippet
	result, err := tspack.Process(`fakesrc ! fakesink`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHack(t *testing.T) {
	// Smoke test: load hack and parse a simple snippet
	result, err := tspack.Process(`<?hh
function main(): void {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHare(t *testing.T) {
	// Smoke test: load hare and parse a simple snippet
	result, err := tspack.Process(`export fn main() void = void;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHaskell(t *testing.T) {
	// Smoke test: load haskell and parse a simple snippet
	result, err := tspack.Process(`main = putStrLn "hello"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHaxe(t *testing.T) {
	// Smoke test: load haxe and parse a simple snippet
	result, err := tspack.Process(`class Main { static function main() {} }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHcl(t *testing.T) {
	// Smoke test: load hcl and parse a simple snippet
	result, err := tspack.Process(`variable "name" { type = string }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHeex(t *testing.T) {
	// Smoke test: load heex and parse a simple snippet
	result, err := tspack.Process(`<%= @greeting %>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHjson(t *testing.T) {
	// Smoke test: load hjson and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHlsl(t *testing.T) {
	// Smoke test: load hlsl and parse a simple snippet
	result, err := tspack.Process(`float4 main() : SV_Target { return 0; }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHocon(t *testing.T) {
	// Smoke test: load hocon and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHoon(t *testing.T) {
	// Smoke test: load hoon and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHtml(t *testing.T) {
	// Smoke test: load html and parse a simple snippet
	result, err := tspack.Process(`<p>hello</p>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHtmldjango(t *testing.T) {
	// Smoke test: load htmldjango and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHttp(t *testing.T) {
	// Smoke test: load http and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHurl(t *testing.T) {
	// Smoke test: load hurl and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeHyprlang(t *testing.T) {
	// Smoke test: load hyprlang and parse a simple snippet
	result, err := tspack.Process(`general { border_size = 1 }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeIdris(t *testing.T) {
	// Smoke test: load idris and parse a simple snippet
	result, err := tspack.Process(`module Main`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeIni(t *testing.T) {
	// Smoke test: load ini and parse a simple snippet
	result, err := tspack.Process(`[section]
key = value`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeIspc(t *testing.T) {
	// Smoke test: load ispc and parse a simple snippet
	result, err := tspack.Process(`export void main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJai(t *testing.T) {
	// Smoke test: load jai and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJanet(t *testing.T) {
	// Smoke test: load janet and parse a simple snippet
	result, err := tspack.Process(`(print "hello")`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJava(t *testing.T) {
	// Smoke test: load java and parse a simple snippet
	result, err := tspack.Process(`class Main {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJavadoc(t *testing.T) {
	// Smoke test: load javadoc and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJavascript(t *testing.T) {
	// Smoke test: load javascript and parse a simple snippet
	result, err := tspack.Process(`console.log('hello');`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJinja2(t *testing.T) {
	// Smoke test: load jinja2 and parse a simple snippet
	result, err := tspack.Process(`{{ variable }}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJq(t *testing.T) {
	// Smoke test: load jq and parse a simple snippet
	result, err := tspack.Process(`.[] | select(.key)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJsdoc(t *testing.T) {
	// Smoke test: load jsdoc and parse a simple snippet
	result, err := tspack.Process(`/** @param {string} name */`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJson(t *testing.T) {
	// Smoke test: load json and parse a simple snippet
	result, err := tspack.Process(`{"key": "value"}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJson5(t *testing.T) {
	// Smoke test: load json5 and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJsonnet(t *testing.T) {
	// Smoke test: load jsonnet and parse a simple snippet
	result, err := tspack.Process(`{ key: 'value' }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJulia(t *testing.T) {
	// Smoke test: load julia and parse a simple snippet
	result, err := tspack.Process(`function main() end`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeJust(t *testing.T) {
	// Smoke test: load just and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeKcl(t *testing.T) {
	// Smoke test: load kcl and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeKconfig(t *testing.T) {
	// Smoke test: load kconfig and parse a simple snippet
	result, err := tspack.Process(`config FOO
	bool "Enable foo"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeKdl(t *testing.T) {
	// Smoke test: load kdl and parse a simple snippet
	result, err := tspack.Process(`node "value"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeKotlin(t *testing.T) {
	// Smoke test: load kotlin and parse a simple snippet
	result, err := tspack.Process(`fun main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLatex(t *testing.T) {
	// Smoke test: load latex and parse a simple snippet
	result, err := tspack.Process(`\documentclass{article}
\begin{document}
Hello
\end{document}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLean(t *testing.T) {
	// Smoke test: load lean and parse a simple snippet
	result, err := tspack.Process(`def main : IO Unit := pure ()`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLedger(t *testing.T) {
	// Smoke test: load ledger and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLess(t *testing.T) {
	// Smoke test: load less and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLinkerscript(t *testing.T) {
	// Smoke test: load linkerscript and parse a simple snippet
	result, err := tspack.Process(`SECTIONS { .text : { *(.text) } }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLiquid(t *testing.T) {
	// Smoke test: load liquid and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLlvm(t *testing.T) {
	// Smoke test: load llvm and parse a simple snippet
	result, err := tspack.Process(`define i32 @main() { ret i32 0 }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLua(t *testing.T) {
	// Smoke test: load lua and parse a simple snippet
	result, err := tspack.Process(`print('hello')`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLuadoc(t *testing.T) {
	// Smoke test: load luadoc and parse a simple snippet
	result, err := tspack.Process(`---@param name string`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLuap(t *testing.T) {
	// Smoke test: load luap and parse a simple snippet
	result, err := tspack.Process(`[a-z]+`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeLuau(t *testing.T) {
	// Smoke test: load luau and parse a simple snippet
	result, err := tspack.Process(`local x: number = 1`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMagik(t *testing.T) {
	// Smoke test: load magik and parse a simple snippet
	result, err := tspack.Process(`_method object.hello
_endmethod`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMake(t *testing.T) {
	// Smoke test: load make and parse a simple snippet
	result, err := tspack.Process(`all:
	echo hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMarkdown(t *testing.T) {
	// Smoke test: load markdown and parse a simple snippet
	result, err := tspack.Process(`# Hello

World`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMarkdownInline(t *testing.T) {
	// Smoke test: load markdown_inline and parse a simple snippet
	result, err := tspack.Process(`**bold** and *italic*`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMatlab(t *testing.T) {
	// Smoke test: load matlab and parse a simple snippet
	result, err := tspack.Process(`function y = hello(x)
y = x;
end`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMermaid(t *testing.T) {
	// Smoke test: load mermaid and parse a simple snippet
	result, err := tspack.Process(`graph TD
A --> B`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMeson(t *testing.T) {
	// Smoke test: load meson and parse a simple snippet
	result, err := tspack.Process(`project('hello', 'c')`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMlir(t *testing.T) {
	// Smoke test: load mlir and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMojo(t *testing.T) {
	// Smoke test: load mojo and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeMove(t *testing.T) {
	// Smoke test: load move and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNasm(t *testing.T) {
	// Smoke test: load nasm and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNetlinx(t *testing.T) {
	// Smoke test: load netlinx and parse a simple snippet
	result, err := tspack.Process(`PROGRAM_NAME='hello'`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNginx(t *testing.T) {
	// Smoke test: load nginx and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNickel(t *testing.T) {
	// Smoke test: load nickel and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNim(t *testing.T) {
	// Smoke test: load nim and parse a simple snippet
	result, err := tspack.Process(`echo "hello"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNinja(t *testing.T) {
	// Smoke test: load ninja and parse a simple snippet
	result, err := tspack.Process(`rule cc
  command = cc $in -o $out`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNix(t *testing.T) {
	// Smoke test: load nix and parse a simple snippet
	result, err := tspack.Process(`{ pkgs ? import <nixpkgs> {} }: pkgs.hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNorg(t *testing.T) {
	// Smoke test: load norg and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNorgMeta(t *testing.T) {
	// Smoke test: load norg_meta and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNqc(t *testing.T) {
	// Smoke test: load nqc and parse a simple snippet
	result, err := tspack.Process(`task main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeNushell(t *testing.T) {
	// Smoke test: load nushell and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeObjc(t *testing.T) {
	// Smoke test: load objc and parse a simple snippet
	result, err := tspack.Process(`@interface Main @end`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeOcaml(t *testing.T) {
	// Smoke test: load ocaml and parse a simple snippet
	result, err := tspack.Process(`let () = print_endline "hello"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeOcamlInterface(t *testing.T) {
	// Smoke test: load ocaml_interface and parse a simple snippet
	result, err := tspack.Process(`val x : int`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeOcamllex(t *testing.T) {
	// Smoke test: load ocamllex and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeOdin(t *testing.T) {
	// Smoke test: load odin and parse a simple snippet
	result, err := tspack.Process(`package main`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeOpenscad(t *testing.T) {
	// Smoke test: load openscad and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeOrg(t *testing.T) {
	// Smoke test: load org and parse a simple snippet
	result, err := tspack.Process(`* Hello
World`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePascal(t *testing.T) {
	// Smoke test: load pascal and parse a simple snippet
	result, err := tspack.Process(`program Hello; begin end.`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePem(t *testing.T) {
	// Smoke test: load pem and parse a simple snippet
	result, err := tspack.Process(`-----BEGIN CERTIFICATE-----
data
-----END CERTIFICATE-----`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePerl(t *testing.T) {
	// Smoke test: load perl and parse a simple snippet
	result, err := tspack.Process(`print 'hello';`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePgn(t *testing.T) {
	// Smoke test: load pgn and parse a simple snippet
	result, err := tspack.Process(`1. e4 e5 *`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePhp(t *testing.T) {
	// Smoke test: load php and parse a simple snippet
	result, err := tspack.Process(`<?php echo 'hello'; ?>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePhpdoc(t *testing.T) {
	// Smoke test: load phpdoc and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePkl(t *testing.T) {
	// Smoke test: load pkl and parse a simple snippet
	result, err := tspack.Process(`name = "hello"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePo(t *testing.T) {
	// Smoke test: load po and parse a simple snippet
	result, err := tspack.Process(`msgid "hello"
msgstr "world"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePoeFilter(t *testing.T) {
	// Smoke test: load poe_filter and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePony(t *testing.T) {
	// Smoke test: load pony and parse a simple snippet
	result, err := tspack.Process(`actor Main
  new create(env: Env) => None`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePostscript(t *testing.T) {
	// Smoke test: load postscript and parse a simple snippet
	result, err := tspack.Process(`/hello { (Hello) show } def`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePowershell(t *testing.T) {
	// Smoke test: load powershell and parse a simple snippet
	result, err := tspack.Process(`Write-Host 'hello'`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePrintf(t *testing.T) {
	// Smoke test: load printf and parse a simple snippet
	result, err := tspack.Process(`%d %s`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePrisma(t *testing.T) {
	// Smoke test: load prisma and parse a simple snippet
	result, err := tspack.Process(`model User { id Int @id }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeProlog(t *testing.T) {
	// Smoke test: load prolog and parse a simple snippet
	result, err := tspack.Process(`hello :- write('hello'), nl.`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePromql(t *testing.T) {
	// Smoke test: load promql and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeProperties(t *testing.T) {
	// Smoke test: load properties and parse a simple snippet
	result, err := tspack.Process(`key=value`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeProto(t *testing.T) {
	// Smoke test: load proto and parse a simple snippet
	result, err := tspack.Process(`syntax = "proto3";`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePrql(t *testing.T) {
	// Smoke test: load prql and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePsv(t *testing.T) {
	// Smoke test: load psv and parse a simple snippet
	result, err := tspack.Process(`a|b|c
1|2|3`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePug(t *testing.T) {
	// Smoke test: load pug and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePuppet(t *testing.T) {
	// Smoke test: load puppet and parse a simple snippet
	result, err := tspack.Process(`notify { 'hello': }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePurescript(t *testing.T) {
	// Smoke test: load purescript and parse a simple snippet
	result, err := tspack.Process(`module Main where`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePymanifest(t *testing.T) {
	// Smoke test: load pymanifest and parse a simple snippet
	result, err := tspack.Process(`include *.txt`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokePython(t *testing.T) {
	// Smoke test: load python and parse a simple snippet
	result, err := tspack.Process(`print('hello')`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeQl(t *testing.T) {
	// Smoke test: load ql and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeQmldir(t *testing.T) {
	// Smoke test: load qmldir and parse a simple snippet
	result, err := tspack.Process(`module Example`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeQmljs(t *testing.T) {
	// Smoke test: load qmljs and parse a simple snippet
	result, err := tspack.Process(`import QtQuick 2.0
Item {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeQuery(t *testing.T) {
	// Smoke test: load query and parse a simple snippet
	result, err := tspack.Process(`(identifier) @name`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeR(t *testing.T) {
	// Smoke test: load r and parse a simple snippet
	result, err := tspack.Process(`print('hello')`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRacket(t *testing.T) {
	// Smoke test: load racket and parse a simple snippet
	result, err := tspack.Process(`#lang racket
(define x 1)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRasi(t *testing.T) {
	// Smoke test: load rasi and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRazor(t *testing.T) {
	// Smoke test: load razor and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRbs(t *testing.T) {
	// Smoke test: load rbs and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRe2c(t *testing.T) {
	// Smoke test: load re2c and parse a simple snippet
	result, err := tspack.Process(`/*!re2c
  [a-z]+ { return; }
*/`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeReadline(t *testing.T) {
	// Smoke test: load readline and parse a simple snippet
	result, err := tspack.Process(`set editing-mode vi`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRegex(t *testing.T) {
	// Smoke test: load regex and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRego(t *testing.T) {
	// Smoke test: load rego and parse a simple snippet
	result, err := tspack.Process(`package main
default allow = false`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRequirements(t *testing.T) {
	// Smoke test: load requirements and parse a simple snippet
	result, err := tspack.Process(`flask>=2.0`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRescript(t *testing.T) {
	// Smoke test: load rescript and parse a simple snippet
	result, err := tspack.Process(`let x = 1`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRobot(t *testing.T) {
	// Smoke test: load robot and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRoc(t *testing.T) {
	// Smoke test: load roc and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRon(t *testing.T) {
	// Smoke test: load ron and parse a simple snippet
	result, err := tspack.Process(`(key: "value")`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRst(t *testing.T) {
	// Smoke test: load rst and parse a simple snippet
	result, err := tspack.Process(`Hello
=====

World`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRtf(t *testing.T) {
	// Smoke test: load rtf and parse a simple snippet
	result, err := tspack.Process(`{\rtf1 hello}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRuby(t *testing.T) {
	// Smoke test: load ruby and parse a simple snippet
	result, err := tspack.Process(`puts 'hello'`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeRust(t *testing.T) {
	// Smoke test: load rust and parse a simple snippet
	result, err := tspack.Process(`fn main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeScala(t *testing.T) {
	// Smoke test: load scala and parse a simple snippet
	result, err := tspack.Process(`object Main`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeScheme(t *testing.T) {
	// Smoke test: load scheme and parse a simple snippet
	result, err := tspack.Process(`(define x 1)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeScss(t *testing.T) {
	// Smoke test: load scss and parse a simple snippet
	result, err := tspack.Process(`$color: red;
body { color: $color; }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSlang(t *testing.T) {
	// Smoke test: load slang and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSmali(t *testing.T) {
	// Smoke test: load smali and parse a simple snippet
	result, err := tspack.Process(`.class public LMain;
.super Ljava/lang/Object;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSmalltalk(t *testing.T) {
	// Smoke test: load smalltalk and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSmithy(t *testing.T) {
	// Smoke test: load smithy and parse a simple snippet
	result, err := tspack.Process(`namespace example
string MyString`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSml(t *testing.T) {
	// Smoke test: load sml and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSnakemake(t *testing.T) {
	// Smoke test: load snakemake and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSolidity(t *testing.T) {
	// Smoke test: load solidity and parse a simple snippet
	result, err := tspack.Process(`pragma solidity ^0.8.0;
contract Main {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSouffle(t *testing.T) {
	// Smoke test: load souffle and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSourcepawn(t *testing.T) {
	// Smoke test: load sourcepawn and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSparql(t *testing.T) {
	// Smoke test: load sparql and parse a simple snippet
	result, err := tspack.Process(`SELECT ?s WHERE { ?s ?p ?o }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSql(t *testing.T) {
	// Smoke test: load sql and parse a simple snippet
	result, err := tspack.Process(`SELECT 1;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSqlBigquery(t *testing.T) {
	// Smoke test: load sql_bigquery and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSquirrel(t *testing.T) {
	// Smoke test: load squirrel and parse a simple snippet
	result, err := tspack.Process(`function main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSshConfig(t *testing.T) {
	// Smoke test: load ssh_config and parse a simple snippet
	result, err := tspack.Process(`Host example
  HostName example.com`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeStan(t *testing.T) {
	// Smoke test: load stan and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeStarlark(t *testing.T) {
	// Smoke test: load starlark and parse a simple snippet
	result, err := tspack.Process(`def hello(): pass`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSuperhtml(t *testing.T) {
	// Smoke test: load superhtml and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSvelte(t *testing.T) {
	// Smoke test: load svelte and parse a simple snippet
	result, err := tspack.Process(`<script>let x = 1;</script>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSway(t *testing.T) {
	// Smoke test: load sway and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSwift(t *testing.T) {
	// Smoke test: load swift and parse a simple snippet
	result, err := tspack.Process(`print("hello")`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeSystemverilog(t *testing.T) {
	// Smoke test: load systemverilog and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTablegen(t *testing.T) {
	// Smoke test: load tablegen and parse a simple snippet
	result, err := tspack.Process(`def Hello : Base {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTact(t *testing.T) {
	// Smoke test: load tact and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTcl(t *testing.T) {
	// Smoke test: load tcl and parse a simple snippet
	result, err := tspack.Process(`puts hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTeal(t *testing.T) {
	// Smoke test: load teal and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTempl(t *testing.T) {
	// Smoke test: load templ and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTera(t *testing.T) {
	// Smoke test: load tera and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTerraform(t *testing.T) {
	// Smoke test: load terraform and parse a simple snippet
	result, err := tspack.Process(`resource "null_resource" "main" {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTest(t *testing.T) {
	// Smoke test: load test and parse a simple snippet
	result, err := tspack.Process(`===========
Test
===========
---
(node)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTextproto(t *testing.T) {
	// Smoke test: load textproto and parse a simple snippet
	result, err := tspack.Process(`key: "value"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeThrift(t *testing.T) {
	// Smoke test: load thrift and parse a simple snippet
	result, err := tspack.Process(`service HelloService {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTlaplus(t *testing.T) {
	// Smoke test: load tlaplus and parse a simple snippet
	result, err := tspack.Process(`---- MODULE Main ----
====`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTmux(t *testing.T) {
	// Smoke test: load tmux and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTodotxt(t *testing.T) {
	// Smoke test: load todotxt and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeToml(t *testing.T) {
	// Smoke test: load toml and parse a simple snippet
	result, err := tspack.Process(`key = "value"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTsv(t *testing.T) {
	// Smoke test: load tsv and parse a simple snippet
	result, err := tspack.Process(`a	b	c
1	2	3`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTsx(t *testing.T) {
	// Smoke test: load tsx and parse a simple snippet
	result, err := tspack.Process(`const App = () => <div />;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTurtle(t *testing.T) {
	// Smoke test: load turtle and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTwig(t *testing.T) {
	// Smoke test: load twig and parse a simple snippet
	result, err := tspack.Process(`{{ variable }}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTypescript(t *testing.T) {
	// Smoke test: load typescript and parse a simple snippet
	result, err := tspack.Process(`const x: number = 42;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTypespec(t *testing.T) {
	// Smoke test: load typespec and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTyposcript(t *testing.T) {
	// Smoke test: load typoscript and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeTypst(t *testing.T) {
	// Smoke test: load typst and parse a simple snippet
	result, err := tspack.Process(`#let x = 1`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeUdev(t *testing.T) {
	// Smoke test: load udev and parse a simple snippet
	result, err := tspack.Process(`ACTION=="add", KERNEL=="sd*"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeUngrammar(t *testing.T) {
	// Smoke test: load ungrammar and parse a simple snippet
	result, err := tspack.Process(`Root = Item*
Item = 'token'`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeUxntal(t *testing.T) {
	// Smoke test: load uxntal and parse a simple snippet
	result, err := tspack.Process(`|0100 LIT 01`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeV(t *testing.T) {
	// Smoke test: load v and parse a simple snippet
	result, err := tspack.Process(`fn main() {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVb(t *testing.T) {
	// Smoke test: load vb and parse a simple snippet
	result, err := tspack.Process(`Module Main
End Module`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVerilog(t *testing.T) {
	// Smoke test: load verilog and parse a simple snippet
	result, err := tspack.Process(`module main; endmodule`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVhdl(t *testing.T) {
	// Smoke test: load vhdl and parse a simple snippet
	result, err := tspack.Process(`entity main is end main;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVhs(t *testing.T) {
	// Smoke test: load vhs and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVim(t *testing.T) {
	// Smoke test: load vim and parse a simple snippet
	result, err := tspack.Process(`echo 'hello'`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVimdoc(t *testing.T) {
	// Smoke test: load vimdoc and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVrl(t *testing.T) {
	// Smoke test: load vrl and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeVue(t *testing.T) {
	// Smoke test: load vue and parse a simple snippet
	result, err := tspack.Process(`<template><div>hello</div></template>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeWast(t *testing.T) {
	// Smoke test: load wast and parse a simple snippet
	result, err := tspack.Process(`(module)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeWat(t *testing.T) {
	// Smoke test: load wat and parse a simple snippet
	result, err := tspack.Process(`(module)`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeWgsl(t *testing.T) {
	// Smoke test: load wgsl and parse a simple snippet
	result, err := tspack.Process(`@vertex fn main() -> @builtin(position) vec4f { return vec4f(); }`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeWgslBevy(t *testing.T) {
	// Smoke test: load wgsl_bevy and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeWit(t *testing.T) {
	// Smoke test: load wit and parse a simple snippet
	result, err := tspack.Process(`package example:pkg;`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeWolfram(t *testing.T) {
	// Smoke test: load wolfram and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeX86asm(t *testing.T) {
	// Smoke test: load x86asm and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeXcompose(t *testing.T) {
	// Smoke test: load xcompose and parse a simple snippet
	result, err := tspack.Process(`<Multi_key> <a> : "a"`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeXml(t *testing.T) {
	// Smoke test: load xml and parse a simple snippet
	result, err := tspack.Process(`<?xml version="1.0"?>
<root>hello</root>`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeYaml(t *testing.T) {
	// Smoke test: load yaml and parse a simple snippet
	result, err := tspack.Process(`key: value`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeYuck(t *testing.T) {
	// Smoke test: load yuck and parse a simple snippet
	result, err := tspack.Process(`(defwidget main [] (label :text "hi"))`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeZig(t *testing.T) {
	// Smoke test: load zig and parse a simple snippet
	result, err := tspack.Process(`pub fn main() void {}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeZiggy(t *testing.T) {
	// Smoke test: load ziggy and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeZiggySchema(t *testing.T) {
	// Smoke test: load ziggy_schema and parse a simple snippet
	result, err := tspack.Process(`x`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}

func Test_SmokeZsh(t *testing.T) {
	// Smoke test: load zsh and parse a simple snippet
	result, err := tspack.Process(`echo hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.RootChildCount < 1 {
		t.Errorf("expected >= 1, got %v", result.RootChildCount)
	}
}
